### ISSUE TITLE
Evolution Journal - Titre Colonne

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#102]
Comme on peut enlever la pagination, il faudrait pouvoir enlever les titres des colonnes.
Cela permet de n'avoir à l'affichage que les éléments importants c'est à dire les heures, ressources, état, acquittement etc.

N'avoir que la donnée (les événements) permet d'être plus souple sur l'aspect graphique environnant pour l'enrobage.

![image](https://user-images.githubusercontent.com/33632664/38136808-37e1958a-3421-11e8-8dbd-5247dfb40969.png)

**Comment by ericvoignier** [comment]
Ajout d'une propriété _entête_ de type checkbox permettant de masquer l'entête du journal
![image](https://user-images.githubusercontent.com/9974702/38630965-b6ffa546-3db8-11e8-9f4f-bdb2e79594b8.png)
En attente déploiement **1.3.5**
