### ISSUE TITLE
Bug Acteur Journal - Nombre d'Evenements

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#103]
Quand on met une valeur **_Null_** dans la propriété spécifique **nombre d'evenement** la scène qui contient l'acteur plante. La scène n'est pas récupérable. 
Je vais la détruire pour la recréer (il n'y a pas grand chose, je n'ai pas besoin d'une restauration :op )
(Maker 1.3.4)

![image](https://user-images.githubusercontent.com/33632664/38137728-a790f3c6-3426-11e8-937e-383dbcb874ce.png)

**Comment by ericvoignier** [comment]
@WITNicolas peux tu préciser quelle propriété _éléments filtrés_ ne semble pas exister
![image](https://user-images.githubusercontent.com/9974702/38137939-1f66f5ca-3428-11e8-952d-1db30eceb0ef.png)

**Comment by WITNicolas** [comment]
**Nombre d'evenements** pardon ... j'avais corrigé le post, mais t as répondu avant.

**Comment by WITNicolas** [comment]
Ok... ce n'est pas la valeur **_Null_** qu'il n'aime pas, mais le **_chiffre 0_**

**Comment by ericvoignier** [comment]
OK reproduit

**Comment by ericvoignier** [comment]
La valeur 0 est désormais impossible
En attente déploiement **1.3.5**
