### ISSUE TITLE
Acteur Zone Incomplet

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#104]
L'**Acteur Zone** ne présente que les zones principales et pas toutes les zones présentes en enfant d'enfant d'enfant, etc....
![image](https://user-images.githubusercontent.com/33632664/38139673-c7a86d38-3430-11e8-84f6-93b2c44b00eb.png)

Cela impacte aussi l'**acteur ETAT** et **JOURNAL** qui n'affichent pas dans les _propriétés spécifiques_ toutes les zones disponibles.
![image](https://user-images.githubusercontent.com/33632664/38139733-0d0adee2-3431-11e8-9c86-c4a524c881f5.png)

Le nombre de zone ainsi que l'imbrication parent/enfant est sans limite...

**Comment by ericvoignier** [comment]
- Récupérer tous les niveaux des zones
- Définir moyen de restitution simple de la hiérarchie.
- Vérifier mécanisme d'inclusion ou pas des enfants dans les requêtes et comportement implémenté dans API

**Comment by ericvoignier** [comment]
Les zones enfants sont désormais affichées
![image](https://user-images.githubusercontent.com/9974702/38628745-69bc3c0a-3db2-11e8-9cf6-057f198e21c7.png)
En attente déploiement **1.3.5**
