### ISSUE TITLE
Slider : Valeur affichée avec décimales

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#107]
Quand on bouge le **SLIDER**, la valeur s'incrémente bien selon l'intervalle saisie, sauf que pour certaines valeurs (aléatoires) la valeur lue prends X décimales.
![image](https://user-images.githubusercontent.com/33632664/38252475-8b5caec6-3754-11e8-8487-96615e3aab71.png)

Avec un intervalle de 1, les décimales doivent être à 0, intervalle de 0.1 pour 1 décimale, etc..

**Comment by ericvoignier** [comment]
Oui c'est un problème inhérent au javascript, nous devons identifier une solution de contournement

**Comment by WITNicolas** [comment]
Pour info
Je me suis affranchi de ce problème aléatoire en mettant un return parseFloat((context.value).toFixed(0) ; dans le script de lecture.
