### ISSUE TITLE
Disparition de sources

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#108]
J'ai des sources qui ont disparue et je ne comprends pas comment.
Je ne comprenais pas pourquoi certaine Scène ne fonctionnait plus et dans le maker je me suis rendu compte que les variables sont toujours liaisonnées mais sans source au bout.

Je vous envoi le lien de mon REDY par mail. REDY en fonctionnement et opérationnel

**Comment by WITNicolas** [comment]
Nouvelle perte de données ce jour : 

**Le symptôme:**
Disparitions de source dans SYNAPPS.
Cette fois-ci c'est une partie de la librairie d'images et la librairie couleur qui ont disparus

Il s'agit d'une disparition dans la mémoire volatile.
J'ai redémarrer le REDY est tout ce qui était sauvegardé précédemment et bien revenu.

La sauvegarde physique est donc bien réelle.
Il y a un événement qui supprime des données dans le dossier SYNAPP.

**Ce qui s’est produit à ce moment-là : (je ne saurais dire si c’est après cela que ça n’a plus fonctionner)**
Je me suis connecter sur le MAKER - OK
J'ai vu ma SYNAPP – OK
J’ai sélectionner ma SYNAPP – OK
Le cercle d’attente est apparu – OK

Puis page indiquant SERVICE INDISPONIBLE.

**Nouvelle tentative**
Même constat même punition.

**Tentative Numéro 3**
Le maker s’est ouvert correctement, mais j’ai constaté des pertes aux niveaux visuels (librairie couleur) ainsi que des erreurs de sources.

Je suis allé contrôlé dans le REDY, dans le dossier SYNAPP et j’ai constaté que des éléments avaient disparu

J’ai redémarrer mon REDY et tout est revenu comme à la sauvegarde précédente, celle de 00h00 (je sauvegarde tous les soirs).

Je vous ai envoyé mon paramétrage, je pense qu'il faudrait le mettre dans un REDY K7 pour le faire tourner et constater.

**Comment by WITNicolas** [comment]
**Nouvelle disparition.**
Toutes les sources et toutes les librairies (image, couleur, contenu).

J’étais en train de "jouer" avec un composite au niveau de l'image de l'icone en faisant des photos pour mettre une icone de représentation. (la mise en page n'est pas évidente).
J'ai donc fais ma propre icone et je l'ai glissé dans l'encart prévue à cet effet.

J'ai à nouveau eu la page "SERVICE INDISPONIBLE", et tout avait disparu.
J'essaie de reproduire.

**Comment by WITNicolas** [comment]
Il n'y a malheureusement pas de lien avec ce que je venais de faire. Cela semble aléatoire.
J'ai redémarré le K7 et tout est revenu comme avant lors de ma dernière sauvegarde.
(Ce n'est pas le K7 qui a redémarrer tout seul sans prévenir)

Depuis ma dernière intervention d'il y a 10 jours je n'avais pas travaillé sur le MAKER de manière intensive, seulement une utilisation "normale" avec le RUNTIME.

Ce qui me fait dire que c'est le MAKER qui provoque cela quand il y a une écriture pendant la phase de Déploiement.

**Comment by ericvoignier** [comment]
A réouvrir si le problème se reproduit

**Comment by ericvoignier** [comment]
@WITNicolas as tu eu de nouvelles pertes de données depuis la **1.3.6 soit environ depuis 9/10 jours ?

**Comment by WITNicolas** [comment]
Je n'ai plus constaté cela. Tant mieux.
