### ISSUE TITLE
Erreur sur Type d'Extension dans explorateur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#109]
Dans l'explorateur, des objets ne sont pas typés correctement.

Dans le REDY
![image](https://user-images.githubusercontent.com/33632664/38633455-05397adc-3dc0-11e8-914a-86e09211638d.png)

Dans Synapps
![image](https://user-images.githubusercontent.com/33632664/38633474-1425610a-3dc0-11e8-8f68-abfd691f9caa.png)

Il manque les types PLUG517 et PLUG518. Le PLUG507 était le seul qui existait à l’époque.

**Comment by ericvoignier** [comment]
Le nom du "type" de noeud est modifié pour prendre en compte le nom spécifique plutôt que celui de la classe
![image](https://user-images.githubusercontent.com/9974702/38730257-0a1e4440-3f16-11e8-882f-275a8067d1ec.png)
En attente déploiement **1.3.5**
