### ISSUE TITLE
Erreur au chargement de source

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#110]
Il y a cette erreur qui apparaît à l'affichage de la scène
![image](https://user-images.githubusercontent.com/33632664/38635069-852145be-3dc4-11e8-9592-cb8162f6360a.png)

Ensuite les données sont bien rafraîchies avec les bonnes valeurs
![image](https://user-images.githubusercontent.com/33632664/38635088-93c8ccd6-3dc4-11e8-95f8-5e0b0fa70160.png)

Sachant que les sources existent bien. Peut être un timeout trop court s'il y a beaucoup de sources.
![image](https://user-images.githubusercontent.com/33632664/38635214-f4df89f6-3dc4-11e8-94b7-cb5c0e5405fd.png)

Il s'agit de composites.

**Comment by ericvoignier** [comment]
En attente déploiement **1.3.5**

**Comment by WITNicolas** [comment]
Au temps pour moi ... désolé du doublon.
