### ISSUE TITLE
Erreur runtime SynApps sur IOs

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#111]
Erreur sysaps si la synaps est visualisé avec IOS apple.
Pas d’erreur en windows ou android
Version redy : 9.5.0
![image](https://user-images.githubusercontent.com/9974702/38726781-74f5ba56-3f0b-11e8-89b2-1bb129492c1f.png)

**Comment by ericvoignier** [comment]
@maurocolognesi  peux tu communiquer le paramétrage

**Comment by manufitoussiwit** [comment]
Il faut vérifier avant tout si safari accepte bien les cookies tiers.


![fichier 13-04-2018 11 13 13](https://user-images.githubusercontent.com/35595723/38727063-3d609c22-3f0c-11e8-98e4-9d50a02e8549.jpeg)

**Comment by ericvoignier** [comment]
@maurocolognesi peux tu vérifier si le problème subsiste en 1.3.5 ?

**Comment by WITNicolas** [comment]
Pour ma part j'utilise SYNAPPS sur Iphone 5S avec IOS11 et je n'ai jamais constaté de soucis particulier.
Je suis en : 
Empêcher le suivi intersite OFF
Bloquer les cookies OFF
Ne pas suivre mes activités ON
Alerte si site web frauduleux ON
Appareil photo et Micro ON
Rechercher Apple Pay ON

**Comment by ericvoignier** [comment]
Résolution confirmée par @maurocolognesi
