### ISSUE TITLE
Création de composite à partir d'un acteur dans une scène

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#112]
Avoir la possibilité d'envoyer une structure dans un composite.
Je m'explique.
Dans une scène, je crée un acteur et je me rends compte que finalement cet acteur est pas mal du tout et je souhaite en faire un composite.
Il faudrait pouvoir choisir l'acteur et le "transposer" dans l'interface Composite.

Une fois le "vrai" composite créé, on peut supprimer l'acteur et mettre le composite à la place.

**Comment by ericvoignier** [comment]
C'est possible !
![image](https://user-images.githubusercontent.com/9974702/38851395-e2ebf4c8-4215-11e8-8001-bfd91da85213.png)
_Remarque:_ de la même façon, lorsqu'un acteur composite est sélectionné dans une scène, l'action sur ce bouton, permet d'éditer le composite.

**Comment by ericvoignier** [comment]
Problème sur création de composite depuis un acteur d'une scene confirmé...

**Comment by ericvoignier** [comment]
Corrigé
