### ISSUE TITLE
Acteur iFrame

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#113]
Impossible de cliquer dans les sous menus.
Problème qui s'est posé à l’époque d'une utilisation des navigateurs WEB autre que IE ou bien UC qui n’était pas utilisée avec **_les paramètres de compatibilité_** d'activé.

Cela avait été gommé avec l'arrivée des V9 pour le multi-navigateurs.
Il doit y avoir des "trucs" dans l'iFrame. :op 
![image](https://user-images.githubusercontent.com/33632664/38838033-c175cb34-41d4-11e8-9448-39f3e4627b61.png)

**Comment by ericvoignier** [comment]
Le contenu des acteurs IFrame est **sandboxé**: blocage de certaines fonctionnalités pour des raisons de sécurité. Certaines propriétés de ce blocage sont dévérouillables dans l'onglet spécifique de l'acteur.
Par contre, l’accès à la structure du dom parente, en dehors du contenu de l'IFrame, est volontairement bloquée, et c'est que tente de faire le menu ci-dessus. Même si cet accès était autorisé, cela ne fonctionnerait pas mieux.
_Remarque:_ pour le même raison, certains synoptiques ne fonctionnerons pas.

**Comment by ericvoignier** [comment]
L'issue est fermée, il faut modifier le contenu qui ne doit pas accéder au dom parent de l'IFrame ...
