### ISSUE TITLE
Rendu Liste de Source de Données.

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#119]
L'affichage ne permet plus de faire un scroll pour aller chercher une source.
La frame n'a pas de butée, elle "déborde" de la modale.

![image](https://user-images.githubusercontent.com/33632664/39128645-9a2725ee-4708-11e8-9a62-b757d8a0dd9e.png)

**Comment by ericvoignier** [comment]
Scollbar ajoutée
![image](https://user-images.githubusercontent.com/9974702/39131470-c3c2b4ca-470f-11e8-8640-
a55821655f8c.png)
Déployé avec **1.36**
