### ISSUE TITLE
Nouvel Acteur Défilement de Scènes

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#121]
Suite au projet de Monaco (avec Fred et Joel) et pour la création d’écran de sensibilisation, avoir un acteur d'affichage permettant des transitions automatiques entre scènes choisies selon plusieurs effets, par exemple : Fade temporisé, Recouvrement haut/bas/gauche/droite, voire autres (sobre)

Ce type de Synapp n'aurait pas besoin de login/password vu qu'il ne s'agit "que" de Visualisation.
Un PC au démarrage devrait être "capable" de lancer le "diaporama" sans actions d'un opérateur.

**Comment by ericvoignier** [comment]
Oui, ce besoin est clairement identifié: l'usage type "écran d'accueil" sans interaction utilisateur est nécessaire. 
Concernant la session utilisateur:
- cette problématique sera adressée plus globalement en modifiant le workflow pour arriver sur une SynApps et en stockant notamment un  jeton de sécurité permettant de régénérer un _wsid_.
- d'ici la la session utilisateur est glissante et ne sera donc pas expiré avec enchaînement des écrans contenant des sources de données

**Comment by manufitoussiwit** [comment]
Une variante d'acteur écran arrive dans la version 1.1.0 de Studio.
