### ISSUE TITLE
Bug Acteur Zone à chaque ouverture de Scène

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#123]
_Vers.1.3.5 fix_
L'acteur crée visuellement des zones à chaque fois que l'on ouvre la scène contenant le-dit acteur ou bien que l'on clique sur l'acteur pour sélectionner les zones.
Dans mon exemple, je n'ai que 2 zones dans le REDY

![image](https://user-images.githubusercontent.com/33632664/39191913-3ffeb0a2-47d8-11e8-87e8-729714859191.png)

**Comment by ericvoignier** [comment]
Impossible à reproduire, peux-tu m'envoyer ton paramétrage, merci !

**Comment by ericvoignier** [comment]
Fix déployé en **1.3.6**
