### ISSUE TITLE
Acteur Liste Déroulante avec beaucoup d’éléments.

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#124]
Une liste importante l'acteur ne permet pas d'être correctement utilisable. 
Dans l'exemple : 
Les heures de 00h à 23h donc 24 lignes. Peu importe la position du texte, le défilement haut ou bas.

Une scrollbar paramétrable avec le nombre d’élément maxi affiché serait la bienvenue  ou bien tout simplement limité à la taille de la scène, si on dépasse (haut ou bas) -> Scrollbar dans la liste

![image](https://user-images.githubusercontent.com/33632664/39196633-e4f3c584-47e2-11e8-8911-3a8246948022.png)

**Comment by ericvoignier** [comment]
Ajout d'une propriété _Hauteur liste_ permettant de limiter la taille de la liste
![image](https://user-images.githubusercontent.com/9974702/39298284-0f7157fe-4946-11e8-92f1-e3dc45ef74a7.png)

**Comment by ericvoignier** [comment]
Déployé avec **1.3.6**
