### ISSUE TITLE
Rendu Zone dans les paramètres spécifiques des Acteurs

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#128]
Dans les paramètres spécifiques des acteurs, les zones sont rendus avec les labels et non pas les libellés pour les acteurs suivant (en résumé tous les acteurs qui utilisent les zones) : 

**Journal**
![image](https://user-images.githubusercontent.com/33632664/39437748-086e478c-4ca2-11e8-9227-057a505d2edd.png)

**Etat**
![image](https://user-images.githubusercontent.com/33632664/39437774-2046a8d6-4ca2-11e8-905e-35773e983fe2.png)

**Zone**
![image](https://user-images.githubusercontent.com/33632664/39437786-2d3d1598-4ca2-11e8-962c-cb2e462e1ca7.png)

**Comment by ericvoignier** [comment]
Fix en attente déploiement
