### ISSUE TITLE
Connaitre le nom des propriétés internes d'acteurs

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#129]
Nécessaire notamment dans l'utilisation dans des scriptes js

**Comment by WITNicolas** [comment]
Cette information n'est pas forcément nécessaire dans un premier niveau de création.
Tout cela pour éviter d'avoir trop d'information pour des utilisateurs de premier niveau si je puis dire.
Par contre en niveau avancé, effectivement cela devient très important.

La question est donc:
Peut on différencier une mode classique d'un mode avancé ? Peut être dans les propriétés de la SYNAPP sur le premier écran...

Un niveau Avancé n'a pas le même regard qu'un niveau Standard. Dans le premier cas, la multitude d'informations n'est pas un problème, par contre dans le second cas, cela peut rebuter ou faire "peur".

**Comment by ericvoignier** [comment]
+1

**Comment by ericvoignier** [comment]
Le **nom interne de la propriété de l'acteur** est désormais visible dans le tooltip ci-dessous
![image](https://user-images.githubusercontent.com/9974702/39533411-3fdfd5bc-4e2f-11e8-9ef8-78540c008fae.png)
