### ISSUE TITLE
Amélioration Acteurs Fonction Rotate

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#131]
Selon un angle prédéfini de 0° (par défaut) / 90° / 180° / 270°.
Permettre une rotation des images, cela permet de n'avoir qu'une seule image en bibliothèque et de la manipuler facilement. Je pense entre autre aux synoptiques de régulation ou bien de Centrale de Traitement d'Air où les directions varient souvent.
**Dans le REDY**
![image](https://user-images.githubusercontent.com/33632664/39582460-4ab43770-4eee-11e8-88d1-b6a817f25f45.png)
Il y a autant d'images que de direction possible ...

Et tant qu'à y être, une rotation du texte pour des écritures verticales, je pense entre autre à des libellés pour des jauges verticales pour des niveaux.
Les textes en horizontal peuvent prendre beaucoup de place
![image](https://user-images.githubusercontent.com/33632664/39582692-c8e860d0-4eee-11e8-8c96-fd5f0f2921f3.png) 
![image](https://user-images.githubusercontent.com/33632664/39582742-e8e00abe-4eee-11e8-81fd-4eac995c2ca5.png)

un petit **_rotate_** en somme...

**Comment by ericvoignier** [comment]
Ajout de 2 propriétés de transformation dans la catégorie _Position_ de l'inspecteur d'acteur:
- **Rotation**: effectue une rotations en degré 
- **Echelle**: effectue une mise à l'échelle de 0 à x: <1 + petit, >1 + grand
![image](https://user-images.githubusercontent.com/9974702/39630284-31d990da-4faf-11e8-8070-cacc6c1bcf8d.png)
**_Attention:_** cette fonctionnalité est taguée **BETA**, il est possible que lendu dans le Maker soit altéré dans certaines conditions. Par exemple: représentation dans une _Boite à vue_

**Comment by ericvoignier** [comment]
En attente déploiement **1.3.7**
