### ISSUE TITLE
Plantage Acteur Gauge

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#136]
Dans les propriétés spécifique de l'acteur Gauge, une couleur transparente pour la **couleur de premier plan** fait planter la synapp. (une valeur _Null_ je suppose ...)
![image](https://user-images.githubusercontent.com/33632664/39663755-4b89e424-5079-11e8-92cd-afd093c2c38f.png)

![image](https://user-images.githubusercontent.com/33632664/39663759-67fc403e-5079-11e8-8826-42fac0d2a250.png)

**Comment by ericvoignier** [comment]
La couleur vide/transparente est désormais impossible
En attende déploiement 1**.3.8**
