### ISSUE TITLE
Chargement des liaisons externes vers sources de données tardif

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#146]
Sur des connections lentes, les sources de données sont chargées après le rendu de l'acteur. Cela peut créer des prblèmes de rendus avec des valeurs nulles ou fausses tant que le chargement de la liaison par la source n'est pas terminé.

Il faut modifier le comportements des scènes pour n'être rendu que lorsque toutes les données sont prêtes.

**Comment by manufitoussiwit** [comment]
Cela arrive sur des composites dont on change la source de donnée dans le paramétrage ou plus généralement lorsqu'on change at runtime une source de donnée.

**Comment by manufitoussiwit** [comment]
La correction est faite dans la 1.4.0 mais il persiste un effet inhérent à l'absence temporaire de liaison valable (valeur `undefined`). Tant qu'il n'est pas possible d'ajouter une valeur de défaillance sur les liaisons, il est conseillé de rajouter un script de lecture du genre : 
```javascript
return Em.isNone(context.value) ? '-' : context.value;
```

**Comment by manufitoussiwit** [comment]
Résolu dans la 1.4.0
