### ISSUE TITLE
Icone de la SYNAPP qui ne change plus une fois initialisée

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#159]
Une fois le logo de la SYNAPP initialisé avec une image, il n'est plus possible de la changer.
Même en faisant un _INIT_ sur le bouton proposer, l'image change, on déploie mais si on revient et même avec un _CTRL+F5_, l'image revient.

![image](https://user-images.githubusercontent.com/33632664/40726131-609d99ae-6425-11e8-894e-e0e079830fc9.png)

**Comment by ericvoignier** [comment]
Fix déployé en **1.3.9**
