### ISSUE TITLE
Deconnexion + Acteur Métier

### ISSUE THREAD

**Issue by manufitoussiwit** [witsa/synapps#161]
Plantage lors de l'affichage d'un acteur métier comme le journal alors que la session utilisateur a expiré ou qu'on est deconnecté.

![image](https://user-images.githubusercontent.com/35595723/40768298-37a4075a-64b5-11e8-8c79-3fef286a9179.png)

v1.3.8

**Comment by ericvoignier** [comment]
Résolu en **1.3.9**
