### ISSUE TITLE
Pagination Acteur Etat

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#164]
Il faudrait supprimer la pagination quand on filtre les états par quelque chose.
Sinon il est possible de "naviguer" dans des pages vides et ne plus savoir si oui ou non il y a des etats en rapport avec le filtre.

Dans l'exemple je n'ai plus qu'1 etats, mais j'ai toutes mes pages en rapport direct avec le NOMBRE TOTAL des états et non pas le TOTAL FILTRé.
![image](https://user-images.githubusercontent.com/33632664/40862950-75efec42-65ee-11e8-811e-b3279fa09799.png)

Il faudrait donc que la pagination soit faites sur le (TOTAL - FILTRé) (à mon sens bien sur)
![image](https://user-images.githubusercontent.com/33632664/40863028-bd981b28-65ee-11e8-99b6-0b4f7878005f.png)
Donc 1 Etats 

1 Etat étant inférieur à l'affichage autorisé (21) --> Pas de Pagination.

**Comment by ericvoignier** [comment]
Précisisions sur les propriétés de l'acteur état:

- **Nombre total**: correspond au nombre total de ressources. Il a été mis en place lorsque la totalité des ressources était chargée par SynApps. Hors, le mécanisme de chargement a été modifié récemment (voir #177) et Synapps ne requête désormais que ce qui est nécessaire pour des raisons d'optimisation du temps de chargement. SynApps n'a donc plus l'information du nombre total de ressource.
La propriété _Nombre total_ va donc être **supprimée** car fausse. De mon point de vue, elle ne présentait pas vraiment d'intérêt
- **Nombre filtré**:  correspond au nombre de ressources filtrés hors _nombre affiché_. Dans le cas décrit: 466/21 = 23 pages, ce qui me semble correcte
- **Afficher**: correspond au nombre maximal d'éléments affiché dans une page

_Pour résumer:_ tout est OK excepté le Nombre total qui va être supprimé

**Comment by ericvoignier** [comment]
@WITNicolas cloture ?

**Comment by WITNicolas** [comment]
Oui on peut clôturer si la mécanique est changée, pas de soucis.
Le _**nombre total**_ n'a effectivement pas trop d’intérêt à mon sens non plus.
