### ISSUE TITLE
Evénements avec contexte étendu aux arguments

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#180]
Les événement généres sur les acteurs ont un contexte permettant d'accéder:
 à l'acteur à l'origine de l'événement 
- target_: acteur à l'origine de l'événement 
-  _session_
- _synoStage_
- etc

Par contre aucune information sur l'événement en lui-même: **attributs**, **nom** de l'événement, etc.
Par exemple sur l'événement Ev. "Mouvement souris" avec les coordonnées X et Y de la position de la souris

Proposition: ajouter dans contextes: args et eventName

**Comment by manufitoussiwit** [comment]
C'est présent dans la v2 du runtime
