### ISSUE TITLE
Evolution Objet Librairie

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#198]
Dans les Synoptiques nous utilisons un acteur signalisation où il y a la possibilité de générer un son qui provient d'un fichier Wav ou MP3 (stocké dans l'EASY/EASYPILOT/REDY) pour signaler un changement d"état ou une alarme.

Il serait intéressant d'avoir ce type de liaison pour agir sur le bip du PC ou au mieux jouer un fichier son en boucle, jusqu'à ce qu'une action utilisateur arrête le son via un click.

**Comment by manufitoussiwit** [comment]
J'avais testé la possiblité de réaliser un composite avec intégration d'un son. ça marchait très bien
