### ISSUE TITLE
Modale Grisée et Clic en dehors

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#213]
Malgré le _clic en dehors pour fermer_ décoché, la modale se ferme quand même dés l'instant où la property _Grisé_ est activé. (et qu'on clic en dehors bien sur)
Pour que le _clic en dehors pour fermer_ fonctionne, il faut que le _Grisé_ ne soit pas coché.

Pas logique.. . :op

**Comment by manufitoussiwit** [comment]
Corrigé dans la version 1.4.0 à venir
