### ISSUE TITLE
Vue Etat format Vignette Evolution

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#214]
La vue vignette pourrait être très utile pour une liste des états auto dimensionnés en format Tuile (pour faire suite au Tuto 07 Part. 2)

L’évolution consisterait à autoriser le changement de l'icone de la vignette (je ne vois pas comment d'ailleurs, vu qu'il ne s'agit pas d'un acteur métier a proprement parlé ... et que c'est lié justement au type de la ressource...qui pixellise à mort d'ailleurs :op )

Ce qui voudrait dire non pas simplement changer l'icone-type ressource, mais vraiment personnalisé par vignette.

En tout cas ça serait top au niveau rendu.

**Comment by ericvoignier** [comment]
Oui, l'acteur métier états en mode vignette utilise les logos natifs du REDY et ce mode de représentation présente un interet limité que nous allons probablement supprimer. Dans tous les cas, les possibilités de personnalisation seront toujours limitées

En fait la solution sera apportée par un autre mécansime ... dans les grandes lignes:
- Possibilité de créer un composite permettant de définir une représentation et un comportment en fonction de la classe de ressource. Dans notre cas, on pourrait par exemple définir un icone adaptée, la commande, etc. les composites sont déja capables de remplir cette fonction !
- Acteur **adaptateur**: capable de'identifier l'acteur le plus adapté à la représentation d'une donnée
- Acteur **répéteur** ou liste sachant générer dynamiquement en fonction d'une liste de ressources par exemple

Nous donnerons prochainement + d'éléments concernant cette feuille de route court terme (<3mois) mais lorsque ces fonctionnalités seront disponibles, l'évolution demandée sera réalisable !

**Comment by manufitoussiwit** [comment]
Il n'y a plus d'affichage vignette dans la v2.0
