### ISSUE TITLE
Acteur Métier Grapheur Evolution

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#217]
Il est possible de lier un Acteur Liste avec le Grapheur pour permettre la sélection d'une préparation particulière. Certains Graphiques peuvent effectivement être masqués à des utilisateurs.

Or dans le grapheur, il est toujours possible de revenir sur la page de sélection des Préparation Graphiques en cliquant sur l'icone en haut à gauche, du coup le Tri exclusif via la liste déroulante n'est plus possible.
**SYNAPP**
![image](https://user-images.githubusercontent.com/33632664/41974153-6735efa2-7a17-11e8-8ed2-c53881ad93be.png)

**REDY**
Cette possibilité de navigation est supprimée dans les Synoptiques Classiques lorsqu'un filtre est renseigné.
![image](https://user-images.githubusercontent.com/33632664/41974483-5f23fa10-7a18-11e8-93cc-b541d56dc5b9.png)

Serait-il possible de ne pas autoriser le _Retour à la Sélection des Graphiques_ dans le cas où les propriétés spécifiques _Préparation_ ou _Données du Flux_ sont liaisonnés ?
![image](https://user-images.githubusercontent.com/33632664/41974265-c9658d04-7a17-11e8-99c3-63c6672dd4c6.png)

**Comment by WITNicolas** [comment]
Précision.
Le verrouillage est bien fonctionnel quand on verrouille directement avec les Liste de Déroulante dans les propriétés Spécifiques, mais pas en liaison avec quelque chose d'externe.

**Comment by ericvoignier** [comment]
@manufitoussiwit est-il possible de masquer le chevron de retour à la liste des préparations sur le grapheur ? avec quel paramêtre dans le querystring ?

**Comment by ericvoignier** [comment]
Option non disponible dans le grapheur: évolution demandé en attente mise à disposition

**Comment by manufitoussiwit** [comment]
Effectivement, il existe une commande pour l'affichage du bouton retour: il faut ajouter `sb=true` dans l'`url`.
