### ISSUE TITLE
Symbole €

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#22]
Le symbole  € ne passe pas.
Que ce soit a travers une liaison d'une ressource pour afficher son état, ou bien en écrivant directement le symbole dans un des acteurs de la scene

![symbole](https://user-images.githubusercontent.com/33632664/32736534-ff0d1f8a-c897-11e7-97a9-58d0728e08b3.png)

**Comment by manufitoussi** [comment]
Il y a effectivement un problème d'encodage sur ce genre de caractère coté application et côté automate. Nous allons corriger ça.

**Comment by ericvoignier** [comment]
Pb lié à l'encodage en base64 des caractères Latin1 avant stockage dans le nod du Redy. 2 solutions:
* EncodeUri avant encodage base 64
[https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte](Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range)
* Envoyer encodage zippé

**Comment by manufitoussi** [comment]
@WITNicolas Je te propose en attendant la correction de marquer `&euro;` à la place du `€`, que ce soit dans les champs du REDY ou dans synapps.

![image](https://user-images.githubusercontent.com/2018558/32790301-5d6a663e-c95e-11e7-818f-d097cbe069b2.png)

![image](https://user-images.githubusercontent.com/2018558/32790422-b46b47be-c95e-11e7-99cd-f0bdbd21de81.png)

**Comment by ericvoignier** [comment]
**Fixé pou intégration dans SynApps 1.3.0**
- Gzipper les configs pour optimisation chargement
- Permettre encodage des caractères latins type '€'
_Remarque:_ runtime embarqué 1.2.1 ne sera plus compatible

**Comment by ericvoignier** [comment]
Released in 1.3.0
Les caractères spéciaux sont désormais correctement encodés et sauvegardés

**Comment by WITNicolas** [comment]
Bon apparement toujours présent de mon coté. J'ai bien vérifié le CTRL+F5, la version, j'ai bien controlé etc..etc..
J'ai remis le symbole € dans le REDY **DANS LE REDY,** et au niveau de la SYNAPP en maker ou runtime, le symbole a bien changé mais n’apparaît pas, un carré à la place. **DANS L'EXPLO**

Par contre si j'écris le Symbole € directement dans un texte de la SYNAPP, cela s'affiche bien. **ECRITURE DIRECTE**

![euros](https://user-images.githubusercontent.com/33632664/34614621-603a864e-f232-11e7-9888-7ff689af852b.png)

**Comment by ericvoignier** [comment]
@WITNicolas  le symbole euro est dans une librairie de la SynApp ou dans un nod du REDY ?

**Comment by ericvoignier** [comment]
Les caractères spéciaux définis dans l'UTL ne sont pas correctement restitués à SynApps par l'API WOS.
Le problème se situe donc soit:
- dans les mécanismes d'encodage internes du Redy ou 
- dans la sérialisation via la WOS API
La solution pour l'instant est celle de @manufitoussi le 14/11.
Une issue va être ouverte pour régler le problème côté Redy.

**Comment by ericvoignier** [comment]
Fix Redy effectué et intégré sur prochaine version. En attente confirmation résolution

**Comment by ericvoignier** [comment]
@WITNicolas peux tu valider que le problème est réglé avec la 9.4.4 du REDY ?

**Comment by WITNicolas** [comment]
La 9.4.4 n'est pas encore sortie pour l'instant pas de test possible.

**Comment by ericvoignier** [comment]
@WITNicolas peux tu confirmer correction sur 9.5.0 ?

**Comment by WITNicolas** [comment]
Problème Résolu.
