### ISSUE TITLE
Comportement inattendu sur mise à l'echelle négative des acteurs

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#227]
Avoir la possibilité de faire un Miroir sur l'axe des Y.
Actuellement quand on mets -1 sur Echelle, un miroir s’opère sur Haut Bas. Il serait intéressant de faire la même chose sur le Gauche Droite.

En résumé avoir une Inversion Haut/Bas et Gauche/Droite pour avoir toutes les possibilités d'affichage

**Comment by ericvoignier** [comment]
En effet une échelle négative provoque un effet miroir inattendu avec une **inversion verticale** de l'image.
De plus le cadre de sélection de l'acteur est **décalé**
![image](https://user-images.githubusercontent.com/9974702/42282141-d7966cfc-7fa5-11e8-8da9-621780827ed4.png)
La propriété _Echelle_ est en BETA  et cette issue ne présente pas de caractère particulierement urgent, et proposons de la mettre en attente pour l'instant et recommendons de ne l'utiliser que ponctuellement sur des valeurs d'échelles positives.

**Comment by WITNicolas** [comment]
Pas de soucis, conscient du caractère BETA je n'y porte pas d'importance.
