### ISSUE TITLE
Bug Explorateur de Variable

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#228]
Dans l'explorateur de variable la Fonction NIL du REDY est mal interprétée. Cette fonction permet de transmettre du autant du Booléen ou que de l'Analogique.

**REDY**
![image](https://user-images.githubusercontent.com/33632664/42174721-90e3632e-7e23-11e8-936b-4c901a070a30.png)

**SYNAPPS**
Apparait comme _FALSE_, alors que le _IN_ est une valeur Analogique
![image](https://user-images.githubusercontent.com/33632664/42174755-a1b4c4fe-7e23-11e8-8676-e10f9120c455.png)

**Comment by ericvoignier** [comment]
Dans l'explorateur de nod, la fonction **out** est bien de type _boolean_:
![image](https://user-images.githubusercontent.com/9974702/42283185-00e32804-7fa9-11e8-8cad-92d216c907cf.png)
Donc l'explorateur SynApps est **cohérent** avec ce qui est défini, même si je ne connais pas la signification du _boolean_.
Je n'ai pas tous les éléments côté process REDY: mais il me semble que **NIL** ne transforme pas _IN_ donc _IN_=_OUT_. Dans ce cas pourquoi ne pas se lier directement à _IN_ ?

**Comment by WITNicolas** [comment]
_Boolean_ signifie variable True / False.
Par contre je pense qu'il doit y avoir une mécanique un peu particulière quand on liaisonne un ANALOG dans le _IN_. Si on regarde mon _OUT_ dans l'automate, il y a bien la même valeur que le _IN_ et pas un True / False comme on pourrait l'imaginer.

Ce qui n'est pas cohérent avec l'information type _Booléan_ que tu retrouves.
Donc a priori SYNAPPS n’interprète pas mal, mais c'est le REDY lui-même qui modifie le comportement _OUT_ du NIL .... sans changer le type  ...

Solution de contournement effectivement est de liaisonner le _IN_

**Comment by ericvoignier** [comment]
Peux tu vérifier dans la _Configuration > Explorateur_ le type **OUT** et pas dans _Paramétrage > Ressource_

**Comment by WITNicolas** [comment]
Oui il s'agit bien d'un type _Boolean_ pour le _OUT_.

![image](https://user-images.githubusercontent.com/33632664/42284245-324a435c-7fac-11e8-9792-af658c2d8a3f.png)

**Comment by ericvoignier** [comment]
OK proposition de cloture ? la solution étant de se lier au IN (ou à la ressource qui alimente le IN)

**Comment by WITNicolas** [comment]
Adjugé.
