### ISSUE TITLE
Désolé, quelque chose ne s'est pas passée comme prévu.

### ISSUE THREAD

**Issue by maurocolognesi** [witsa/synapps#235]
EasyPilot 960
Acteur Titre dans acteur Accordeon. J'ai ajouté une Text et l'erreur est apparu
 
![image](https://user-images.githubusercontent.com/35558533/42315774-8dea5fb6-8048-11e8-959e-11ceab80f119.png)

**Comment by ericvoignier** [comment]
Corrigé et déployé
