### ISSUE TITLE
Message technique : (code: 0) Cannot read property 'get' of null

### ISSUE THREAD

**Issue by maurocolognesi** [witsa/synapps#237]
EasyPilot 960
erreur pendant la définition d'un bouton dans un stack

![image](https://user-images.githubusercontent.com/35558533/42321716-3195a600-805a-11e8-9f6c-81ab38d99345.png)

**Comment by ericvoignier** [comment]
Duplicate of #235
Ce type de problème ne doit plus se produire => forcer mise à jour de SynApps MAKER avec CTRL+F5
