### ISSUE TITLE
Oups sauvage après changement de label d'acteur

### ISSUE THREAD

**Issue by manufitoussiwit** [witsa/synapps#238]
Synapps maker plante de manière sauvage (on entend _Rrrrr!_ ) lorsqu'après avoir changé le label d'un acteur, on clic dessus.

![image](https://user-images.githubusercontent.com/35595723/42325426-8bda7d50-8066-11e8-921b-122b81a03a97.png)

**Comment by ericvoignier** [comment]
Lorsque les **labels** des _acteurs_, _scènes_ et _composites_ sont modifiés, une transition est désormais effectuée sur la route avec le nouveau label
Fix déployé
