### ISSUE TITLE
Ajout Acteur Positionnement impossible à la creation d'une scene sans faire un F5

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#243]
Il n'est pas possible de rajouter un acteur de positionnement sur une nouvelle scene fraichement créée, le + n'est pas présent.
Il est nécessaire de faire un F5 pour la fonction d'ajout soit possible.
![image](https://user-images.githubusercontent.com/33632664/42681660-938f5f48-8688-11e8-89ac-c16a5471ab8a.png)

**Comment by ericvoignier** [comment]
Je n'arrive pas à reproduire, quel est l'occurence du bug: une fois, plusieurs ou systématique ?

**Comment by WITNicolas** [comment]
Ecoute, cela ne se produit plus, je pense que c'est mon navigateur qui a du se planter. Je viens de refaire le test et c'est non reproductible.

Fausse Issue. Désolé.
