### ISSUE TITLE
Questions suite aux tutos

### ISSUE THREAD

**Issue by Thierry-ECS** [witsa/synapps#244]
Bonjour,
J'ai quelques questions:
- Dans l'acteur navigation Propriété spécifique "Scene", si on affecte une scène y a t-il moyen de revenir en arrière et remettre la combo à valeur nulle?

- Dans le tuto 4 sur le point 5 (liaison de l'acteur "screen middle") il semble qu'il faille coché "Ecriture" pour que ça fonctionne, c'est bien ça?

En tout cas c'est superbe, quel boulot!! Bravo.

**Comment by manufitoussiwit** [comment]
Bonjour Thierry,

Réponse à la 1ère question : 

Oui, en cliquant sur _Retour valeur par défaut_ dans les options de la propriété .


![image](https://user-images.githubusercontent.com/35595723/42808118-cf9fa538-89b2-11e8-8ad0-041941006a09.png)

**Comment by Thierry-ECS** [comment]
Oui, j'avance avant d'essayer de "bidouiller", mais pour le moment c'est Yoda qui a raison J
 
Beaucoup encore il te reste à apprendre.
 
 


Thierry Mallet | Emeraude Concept Systèmes
Synoptiques et supervision
 <http://ecsmalo.fr/> ECS sur le Web
Z.A. La chapelle de la Lande
BP 23118
35430 Saint Jouan des Guérêts
Tel : 02 99 19 50 94
Fax : 02 99 19 68 75
 


Pensez Environnement !

N'imprimez ce mail que si c'est vraiment nécessaire
 
 
De : Emmanuel FITOUSSI [mailto:notifications@github.com] 
Envoyé : mardi 17 juillet 2018 11:27
À : witsa/synapps <synapps@noreply.github.com>
Cc : Thierry-ECS <thierry.mallet@ecsmalo.fr>; Author <author@noreply.github.com>
Objet : Re: [witsa/synapps] Questions suite aux tutos (#244)
 
Et pour la seconde question :
Oui, bien vu! 👍
Depuis la rédaction du tuto, l'interface s'est enrichie des options lecture/écriture de la liaison. Et ici, il faut bien activer l'écriture pour que la valeur du paramètre de la scène suive les modifications.
Déja au tuto 4! Bravo!

**Comment by ericvoignier** [comment]
Merci pour le retour @Thierry-ECS !
