### ISSUE TITLE
Question Sources et Chargements

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#246]
Est ce que toutes les sources sont chargées qu'elle que soit la scène affichée ? Ou bien est ce que le chargement se fait uniquement lorsqu'une donnée qui utilise la-dite source est utilisée sur un acteur affiché ?

Question visant a comprendre le fonctionnement des requêtes SYNAPP vers REDY.

**Comment by ericvoignier** [comment]
Non seules les sources nécessaires dans la scène affichée sont chargées. De façon général, seules les ressources nécessaires sont chargées en fonction des besoins
