### ISSUE TITLE
Bug acteur Slider avec un interval

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#247]
Quand je souhaite mettre une valeur dans la property spécifique intervalle (_step_) : 

![image](https://user-images.githubusercontent.com/33632664/43009486-26817466-8c3e-11e8-8657-91790be42f76.png)

**Comment by WITNicolas** [comment]
Dans un composite pour la modification du step:
![image](https://user-images.githubusercontent.com/33632664/43089925-3dee6f54-8ea6-11e8-9569-75064d0b42fa.png)

[2018_07_23 ECOLE DE LA CONDAMINE-easy.SynApps.SYNAPP.Composites.SetCTAReprise.WK4.zip](https://github.com/witsa/synapps/files/2220187/2018_07_23.ECOLE.DE.LA.CONDAMINE-easy.SynApps.SYNAPP.Composites.SetCTAReprise.WK4.zip)

**Comment by WITNicolas** [comment]
Paramétrage complet envoyé par mail

**Comment by ericvoignier** [comment]
OK problème reproduit

**Comment by ericvoignier** [comment]
Pb identifié en cours de correction, en attendant le problème peut être corrigé ainsi:
- Cliquer sur curseur simple, 
- Réinitialise la valeur Ecart min 
- Déployer
![image](https://user-images.githubusercontent.com/9974702/43138881-8dabdfe0-8f50-11e8-96e9-e85d25a4a047.png)

Un correctif est en cours

**Comment by ericvoignier** [comment]
Fixé et déployé en **1.3.9**
