### ISSUE TITLE
Memoire Insuffisante

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#248]
Je tombe de plus en plus souvent sur mémoire insuffisante quand je suis sur le maker. Tout est relatif evidement, genre au bout de 30min à 1h de clic/param/deploiement, etc..Etc...
![image](https://user-images.githubusercontent.com/33632664/43012223-20f17eb2-8c46-11e8-97aa-a5c37de805c7.png)
là c'est le mauvais screenshot, mais sur le vrai, il y a mémoire insuffisante.

Je n'avais jamais rencontré cela quand je "m'amusais" à petite échelle, là je travaille sur du lourd (à mon sens en tout cas). La Synapp fait à cet instant 2.3mo

Je précise que je tourne sur un PC qui est de niveau Surarmement si je puis dire...

**Comment by ericvoignier** [comment]
Analyse a effectuer après prochaine version majeure et notamment séparation RUNTIME et MAKER
