### ISSUE TITLE
Dysfonctionnement Slider avec min=0

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#251]
C'est la série pour le **Slider** ...
La réaction attendue n'est pas la bonne quand la _property min = 0_ et que la _property max = x_.
Peu importe la valeur de x, le slider réagit sur la plage par défaut qui est 0/100.

Pour que le **Slider** réagisse convenablement, il faut un min<>0.
Bref le 0 n'est pas interprété comme une valeur. Avec une valeur de 0.1, tout fonctionne bien...

**Dans le Maker, butée min/max en 0/ 24** 
![image](https://user-images.githubusercontent.com/33632664/43161478-8844149a-8f88-11e8-94e4-2c59d64de1a3.png)

**Dans le Runtime, la valeur oscille entre 0/100. A l'affichage 89...**
![image](https://user-images.githubusercontent.com/33632664/43161566-b90d2dfa-8f88-11e8-880b-ddae87ca8269.png)

**Comment by ericvoignier** [comment]
Probleme introduit avec issue #250.
Correction  déployée
