### ISSUE TITLE
Evolution Acteur Métier Grapheur 

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#252]
Actuellement l'acteur grapheur utilise les ID des préparations graphiques. Ce n'est pas très pratique dans le sens où ces ID sont générés de manière complétement aléatoire. Ce qui implique de reprendre le paramétrage de la SYNAPP si jamais une préparation doit être supprimée pour être recréée.

L'utilisation du LABEL serait un peu plus a propos, encore qu'il s'agisse aussi de labels générés aléatoirement, mais que l'on peut éventuellement modifier. (contrairement aux ID).

Au mieux les libellés (comme pour le moteur de recherche du grapheur RIA pour rester dans la même logique) pour qu'il y ait le moins d'interaction négative entre SYNAPP et le REDY en cas de modification locale (simplement remettre le bon libellé de préparation)

**Comment by ericvoignier** [comment]
OK à généraliser pour toutes les ressources du REDY: flux, zone, equiment, zone, agenda etc
