### ISSUE TITLE
Erreur de typo

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#253]
Pas grand chose, mais c'est dans les détails que  ..blablabla
_Vraie ou Faux_, j'aurais plutôt mis _Vrai ou Faux_
![image](https://user-images.githubusercontent.com/33632664/43283518-68ef555e-9119-11e8-9c0e-34f9e98f6e85.png)

**Comment by ericvoignier** [comment]
Corrigé **1.4.0**
