### ISSUE TITLE
Ne pas montrer l'acteur image lorque le contenu est vide

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#258]
Dans la majeure partie des cas, nous affichons une image par dessus des fonds de plan pour faire les animations. Superposition d'un ventilateur, moteur, pompe etc.. en mouvement.

Nous ne gérons que l'image 'active', celle qui est animée.
L'image inactive n'existe pas, vu qu'il s'agit du fond de plan, qui est fixe et qui représente l'état de l'installation au repos.

Dans SYNAPPS, une image 'vide' n'est pas totalement vide, dans le sens où on voit l'encart qui positionnerait justement l'image inactive.
Pour palier à cela il faut mettre une 'vraie' image vide, du style blank.gif qui fait 1px / transparent.

Cadre vert : on ne voit pas le cadre pour l'animation soufflage
Cadre rouge : on voit le cadre prévu pour l'image inactive

![image](https://user-images.githubusercontent.com/33632664/43585081-7aed4248-9664-11e8-8bb0-c2e1b1ee79e3.png)

**Comment by ericvoignier** [comment]
Lorsque l'image de l'acteur n'est pas définie, une image blank transparent est utilisée pour éviter l'image par défaut du navigateur
![image](https://user-images.githubusercontent.com/9974702/44035420-c0f83be0-9f0f-11e8-8b37-51c9e85a6ab6.png)

**Comment by ericvoignier** [comment]
Corrigé **1.4.0**
