### ISSUE TITLE
Vulnérabilité SYNAPPS via explorateur du REDY.

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#265]
Voulant supprimer toutes les sources d'un projet, et au lieu de le faire à la main 1 par 1 (cela pourrait faire l'objet d'une évolution : Supprimer toutes les sources).
Je suis passé par l'explorateur et j'ai supprimer le **SOURCES** par la poubelle présente, pensant qu'il serait recréé automatiquement au nouveau chargement de la SYNAPP ... 
![image](https://user-images.githubusercontent.com/33632664/44671766-b52e7500-aa26-11e8-89ef-67e01b2e8d47.png)

Et là c'est le drame ...
![image](https://user-images.githubusercontent.com/33632664/44671781-beb7dd00-aa26-11e8-9833-0094a55d75b8.png)

**Comment by ericvoignier** [comment]
La structure des nods d'une SynApp est sensée être **garantie** par le REDY (classe dédiée _TNod_SynApps_). L'App SynApps MAKER ne vérifie donc pas l'existence de ce nod.
Il ne devrait **pas être possible de supprimer les nods** enfants, tel que source, depuis l'explorateur du REDY !
Une issue est ouverte pour modifier le comportement dans le REDY

**Comment by WITNicolas** [comment]
Je fais un mantis sur le REDY alors ?

**Comment by ericvoignier** [comment]
Demande de modification de la classe SynApps dans soft REDY en cours

**Comment by ericvoignier** [comment]
Fixé dans REDY **9.8.1**
