### ISSUE TITLE
Commande dans composite envoyée à l'affichage d'une scène 

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#269]
Un commande peut être envoyée lorsqu'une scène initialise un composite avec une source de donnée en écriture. Problème constaté sur l'acteur commutateur boutton mais d'autres acteurs d'intéractions potentiellement concernés.
Problème lié à l'affichage d'une scène avec que toutes les données des sources soient chargées.

**Comment by manufitoussiwit** [comment]
Il semblerait que l'acteur switch button a un comportement non attendu à son initialisation. Il est recommandé en attendant sa correction d'utiliser le switch image à la place.

**Comment by ericvoignier** [comment]
Fix déployé en **1.3.9** en attendant résolution #146
