### ISSUE TITLE
Creation de source impossible

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#283]
Je ne peux plus créer de nouvelles sources.
Plus précisément je ne peux plus descendre dans l'arborescence, je reste au niveau de :EASY.RESS.

![image](https://user-images.githubusercontent.com/33632664/47456735-93a6fb00-d7d5-11e8-95a7-f3b977be327a.png)

**Comment by ericvoignier** [comment]
Utilises tu une version 9.8.0 du REDY ?
