### ISSUE TITLE
Rangement des scènes

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#29]
Pouvoir ranger les Scenes dans un ordre différents.
Exemple: j'ai commencé à faire des Scènes, et ensuite je me suis dis que ça serait mieux de faire une Scène avec à l'intérieur un écran d'affichage.
Dans la "lecture" de la Synapp si quelqu'un passe derrière, la structure ne sautera pas aux yeux ...

![image](https://user-images.githubusercontent.com/33632664/32910484-aaabb5d6-cb09-11e7-91a7-0c5caa717e8b.png)

**Comment by ericvoignier** [comment]
Oui ce besoin a été identifié. En attendant, il est possible de ranger les scènes dans des dossiers/sous-dossiers:
![image](https://user-images.githubusercontent.com/9974702/32912372-2d244dde-cb0f-11e7-885f-8d2a30231d79.png)
Une solution pas complètement satisfaisante mais qui fonctionne est de définir l'ordre des scènes directement dans l'explorateur de nod du Redy !

**Comment by ericvoignier** [comment]
Released in 1.3.0
![image](https://user-images.githubusercontent.com/9974702/34611504-1752a8aa-f226-11e7-8f71-a9952ff79b38.png)
