### ISSUE TITLE
Liste Dossier des Scènes / Composites

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#290]
Je crois que les filtres des scènes et composites pour le rangement par dossier à subit une régression. La property **_DOSSIER_** est toujours là, mais vide.

![image](https://user-images.githubusercontent.com/33632664/50383056-cfaeed00-06ac-11e9-9074-721f4fbfed4b.png)

![image](https://user-images.githubusercontent.com/33632664/50383061-dccbdc00-06ac-11e9-8ab0-9f3b8d6b50e3.png)

![image](https://user-images.githubusercontent.com/33632664/50383050-a3936c00-06ac-11e9-8c6a-ce727346f499.png)

**Comment by manufitoussiwit** [comment]
Normalement il n'y a pas de régression, par contre j'ai relevé un problème qui cause ce genre de désagrément : essaie de changer l'index de cache de la synapp dans le paramétrage pour voir l’arborescence est de retour après rechargement.

**Comment by WITNicolas** [comment]
Bien vu, tout est rentré dans l'ordre !
