### ISSUE TITLE
Connexion IP/URL REDY à partir de SYNAPPS-MaKER

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#291]
Connexion sur SYNAPPS : 
![image](https://user-images.githubusercontent.com/33632664/51073741-d4483f00-1675-11e9-9c04-a6f9eaccbe76.png)

Si on rentre une IP sans l'entête HTTP : 
![image](https://user-images.githubusercontent.com/33632664/51073751-05287400-1676-11e9-9e64-abeeae0d9a38.png)

Il faudrait soit changer la mécanique pour autoriser une IP seule ou bien changer le texte d'indication qui précise que l'on peut saisir une IP seule. (Perso je préfère autorisé l'IP seule, sans le http....)

**Comment by manufitoussiwit** [comment]
Fait dans la version 2.0
