### ISSUE TITLE
Ecriture avec Acteur Textbox

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#295]
L'acteur Textbox est en lecture/écriture avec une source du REDY.
Quand on écrit dans le Textbox, cela écrit instantanément dans le REDY, sauf que si on écrit une donnée assez longue comme par exemple la valeur d'un compteur  102142 le fait de la relecture par la SYNAPP (refresh de la source) provoque des erreurs de saisie.

Il faudrait que "l'envoi" vers le REDY soit "désynchronisé" si je puis dire..
1.On écrit
2.on clique en dehors/ on valide
2.ça part en écriture dans le REDY.

et pas 
J'écris, ça part, ça relie, je perds un caractére, ça lit, ça écrit tout en même temps..

**Comment by manufitoussiwit** [comment]
Le comportement des acteurs textbox et textarea n'est pas celui attendu, même sans liaison. Une correction sera présente dans la prochaine version (1.5.0)
