### ISSUE TITLE
Erreur lors du choix de couleur du Fond Acteur Modal

### ISSUE THREAD

**Issue by ThibaudAZAY** [witsa/synapps#297]
lors du choix de la couleur du fond de l'acteur Modal, une erreur apparaît et me déconnecte de l'application

**Comment by ericvoignier** [comment]
Pb reproduit

**Comment by manufitoussiwit** [comment]
Correction publiée dans la version 1.4.3 [changelog](https://witsa.github.io/synapps/changelog.html)
