### ISSUE TITLE
Modification liaisons internes impossible Acteurs (Tuto07)

### ISSUE THREAD

**Issue by ThibaudAZAY** [witsa/synapps#299]
Sur le Tuto 07 (états) il est demandé la modification des liaisons internes des acteur bouton poussoir et HTML mais il est impossible de les modifier, un grand nombre d'erreurs apparaissent et ensuite lors du clic sur le bouton permettant les liaisons rien ne se passe. Après essais de modification du contenu, il est aussi impossible de le modifier. Il faut supprimer l'acteur, vider le cache et recréer l'acteur.

**Comment by manufitoussiwit** [comment]
ça ressemble à une régression sur les liaisons invalides. Je vais tenter de le reproduire.
Est-ce bloquant pour continuer le tuto ?

**Comment by manufitoussiwit** [comment]
Je viens de le reproduire. 

Pour éviter le problème, il faut : 
 - ajouter l'acteur "Etat"
 - modifier les liaisons pour pointer vers celui ci
 - et supprimer enfin l'acteur journal.

Dans la prochaine version, on empêche de se retrouver dans cette situation ou des liaisons internes pointent sur un acteur qui n'existe plus. Le tuto sera modifier en conséquence.

**Comment by manufitoussiwit** [comment]
Dans la version 1.4.4, la suppression d'un acteur ou d'un groupe d'acteur entraîne celles des liaisons cassées.
