### ISSUE TITLE
Acteur non déplaçable dans la liste 

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#30]
Je voulais réarchitecturer mes menus.
J'ai créé une stack Horizontale (Stack33), pour mettre à gauche le menu (Stack Navigation) et à droite le Screen d'affichage. (Screen30)
Sauf que dans ma liste j'ai d'abord le Screen et ensuite la Stack Verticale de mon menu (Stack Navigation)
Impossible de faire passer la Stack Verticale Menu(Stack Navigation) en premiere position et le Screen (Screen30) en 2eme.

Les actions sur les fleches montée et descente agissent mais ne font pas d'effet.

![image](https://user-images.githubusercontent.com/33632664/32918420-acfa9668-cb22-11e7-8178-9317fbe8a64a.png)

**Comment by ericvoignier** [comment]
Ce bug est identifié en attendant un fix:
1. **déployer**
2. **rafraîchir** (F5)
Les flèches seront alors opérationnelles

**Comment by ericvoignier** [comment]
Released in 1.3.0
