### ISSUE TITLE
Amélioration Liste de Ressource

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#305]
Permettre un filtrage supplémentaire avec : 
-Ressource Valide/Non Valide (permet de visualiser uniquement les ressources valides)
-Ressource Manuel/Automatique (permet de visualiser les ressources en mode automatique ou manuel. Ce qui permet de voir si une ressource à ou non était forcée)
-Ressource En Alarme/Sans Alarme

Bref les filtres qu'on retrouve dans l'interface classique du REDY.
Cela permettrait d'être super souple avec le MockupExpl.... :)

**Comment by manufitoussiwit** [comment]
Les fonctionnalités sont remplient partiellement par les états de reflets en v2.0
