### ISSUE TITLE
L'acteur synoptique ne fonctionne pas lorque les synoptiques sont dans un sous-dossier

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#308]

**Comment by ericvoignier** [comment]
La construction de l'url de l'iframe est incorrecte

**Comment by ericvoignier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#308](https://trello.com/c/JbBaKmcs/19-308)

**Comment by manufitoussiwit** [comment]
Corrigé en version 2.0
