### ISSUE TITLE
Style de Police

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#312]
Bonjour,
Sera t'il possible d'ajouter le style "Gras" et "souligné" dans les polices prochainement ? 
Même je sais que l'on peut le faire dans le contenu avec les balises <u> et <strong>

**Comment by manufitoussiwit** [comment]
Bonjour, 
Pour l’empattement des polices ça y est déjà :
![image](https://user-images.githubusercontent.com/35595723/57607604-b7604180-756b-11e9-852f-da0d6f52fcc9.png)
 
Pour ce qui est du soulignement, il manque effectivement les propriétés de décoration de texte (souligné, barré, ...)
Elles arriveront dans la prochaine version.

**Comment by manufitoussiwit** [comment]
C'est présent dans Studio
