### ISSUE TITLE
Librairie Icone

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#313]
Bonjour,
Est-ce-qu'il serait possible d'avoir le site web qui référence la librairie de base utilisée pour les icones dans les synapps ?

![1](https://user-images.githubusercontent.com/50445069/57933516-ce7d9700-78bd-11e9-8d56-e50c82ba0cc5.png)

**Comment by ericvoignier** [comment]
Hello, SynApps intègre 2 librairies:
- [WebHostingHub](https://www.webhostinghub.com/glyphs/)
- [Bootstrap 3.3.7](https://getbootstrap.com/docs/3.3/components/)
