### ISSUE TITLE
Curseur Menu acteurs

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#314]
Bonjour,

Serai't'il possible d'avoir un curseur horizontal pour le menu acteurs des scènes ? 

![1](https://user-images.githubusercontent.com/50445069/58003025-298ed400-7ae0-11e9-9114-a3ed37861cd8.png)

**Comment by manufitoussiwit** [comment]
Il manque effectivement un ascenseur horizontal dans l'arborescence des acteurs. Il sera ajouté dans la prochaine version.

**Comment by JeremieDENAEGEL** [comment]
Est-ce-que cela pourrait aussi être prévu pour les objets Synapp dans les liaisons internes entre autres ? 
Le problème apparait quand la fenêtre est réduite.

**Comment by manufitoussiwit** [comment]
Oui absolument, ce sera fait partout 👍
