### ISSUE TITLE
Acteur iframe : Problème d'envoi de caractères

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#317]
Bonjour,
J'ai créé un composite pour permettre l'envoi d'une donnée en argscript sur un synoptique et les caractères spéciaux (é,è,ô, ...) ne passe pas.

Est-ce normal ?
l'URL mis dans mon acteur est le suivant:

> {{host}}/WSID{{sid}}{{URL synoptique}}/?argscript={{argscript}}

![1](https://user-images.githubusercontent.com/50445069/58711001-de1cd580-83bd-11e9-9c92-88fe1198d90d.jpg)
![2](https://user-images.githubusercontent.com/50445069/58711006-e1b05c80-83bd-11e9-9721-aab32b288f66.jpg)

**Comment by manufitoussiwit** [comment]
Il semblerait que le synoptique a du mal avec les accents de synapps qui lui sont passés en UTF8.
Une solution possible : lui passer les accents sous la forme html par exemple pour  `é` c'est `&eacute;`
[voir ici](https://www.designvegetal.com/gadrat/cours/informatique/html/accents.html)
