### ISSUE TITLE
Acteur Modal

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#318]
Bonjour,

Je rencontre un petit soucis avec l'acteur Modal, on dirait que la position horizontale gauche est inversée avec la droite et que la position verticale haute est inversée avec la basse

Par contre pas de problème au niveau de l'attachement

![1](https://user-images.githubusercontent.com/50445069/58711419-cbef6700-83be-11e9-9d23-b4493e598c64.jpg)

**Comment by WITNicolas** [comment]
Si je ne me trompe pas, c'est le lieu d'accroche de la Modale.
