### ISSUE TITLE
Bug chargement de page Ipad 

### ISSUE THREAD

**Issue by Eltis74** [witsa/synapps#323]
Bonjour,

J'ai rencontré un petit bug quand j'ai voulu utiliser ma synapps sur ipad.
La page suivante se charge bien sur l'ordinateur ainsi que sur la simulation de l'ipad, en revanche impossible d'y accédez depuis l'ipad... 
Est-ce qu'il y a trop de données à charger ? 

Merci
![Uploading ordi.png…]()
![Uploading SimulIpad.png…]()

**Comment by ericvoignier** [comment]
Bonjour,
Les images ne sont pas accessibles, pouvez-vous ré-"uploadées" les 2 images et nous communiquer les caractéristiques de l'IPad.
Dans la mesure du possible, pouvez-vous nous envoyer le paramétrage en passant par la hotline.
Merci.
