### ISSUE TITLE
Acteur Journal

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#324]
Il serait intéressant d'avoir le filtre Acquittée / Non Acquittée.

Cela permettrait de pouvoir interpréter que l'utilisateur a effectuer une action d'acquittement dans le journal pour prise en compte et que du coup qu'une information visuelle et/ou sonore soit stoppée.

Dans ce que je souhaite faire :
Apparition d'un bandeau avec le dernier événement en cours (ça cela fonctionne)
Déclenchement du son (ça ça fonctionne, merci manu pour exemple)
Arrêter le son lorsque les événements en cours sont acquittés ...

Le plus simplement du monde, j'ai pris le nombre des événements filtrés de l'acteur Journal pour déclencher tout cela, mais du coup ça ne s'arrête jamais tant qu'au moins un défaut est présent.

**Comment by manufitoussiwit** [comment]
Dupliqué avec #412
