### ISSUE TITLE
Evolution Acteur Ensemble

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#325]
Comme pour le journal il faudrait pouvoir ne pas afficher l'Entête afin de n'avoir que la liste brute.

Il n'est pas forcément nécessaire d'avoir l'information qui nomme la colonne Identité pour le nom du point et Etat pour l’état, cela coule de source lors de l'affichage de telles informations.

**Comment by manufitoussiwit** [comment]
Fait dans la version 2.0
