### ISSUE TITLE
Acteur Navigation et propriété de scene cible

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#330]
Lorsqu'on crée un bouton de navigation et que l'on choisit une scène cible, il est demandé (si des propriétés additionnelle ont été créé précédemment dans la scène cible évidement) les variables additionnelles.
Jusque là normal.

Si il nous manque une propriété qui n'avait pas été créé précédemment, il n'est plus possible d'avoir la fenêtre de création des propriétés dans le bouton de navigation.
Même si l'on supprime la scène cible dans le bouton et que l'on déploie, qu'on remet la scène cible, les propriétés restent toujours en mémoire, aucun moyen de réinitialiser pour avoir les nouvelles propriétés.

En gros il ne faut pas se tromper ou oublier quelque chose, sinon il faut détruire le bouton et refaire.

**Comment by WITNicolas** [comment]
du coup je change le nom des propriétés, et vu que le lien n'est plus valide (en tout cas tout est nouveau) le fait de choisir à nouveau la scene, cela repropose la création des propriétés.

**Comment by manufitoussiwit** [comment]
L'astuce c'est de changer la scène cible du bouton temporairement, juste le temps de re-sélectionner la bonne scène. ça va déclencher la détection de ce qui manque. Pour les propriétés en trop, il suffit d'afficher tout en bas de l'inspecteur la partie dédiée aux propriétés additionnelles et de les supprimer.
![image](https://user-images.githubusercontent.com/35595723/66079703-dedc9880-e564-11e9-950f-5fa19d2aadcf.png)

**Comment by WITNicolas** [comment]
Ok bien vu. Je ne pensais pas que les propriétés remontées de la scene cible se créées également dans les Propriétés additionnelle de l'acteur.
Je comprends mieux plein de chose. Je n'avais pas percuté.
