### ISSUE TITLE
Positionnement des curseurs Acteur Slider

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#335]
Quand l'acteur SLIDER est sur une toile qui elle même est dans une ViewBox (pour donc faire un redimensionnement automatique), les curseurs du Slider se retrouve dans des positions bizarres.
Quand on le sélectionne il revient bien en bonne position.

En résumé lors du redimensionnement il y a une erreur de coordonnée à la reconstruction.
Si on change d'onglet dans le navigateur et que l'on revient, l'affichage se rafraîchit et tout est bon.
Donc c'est vraiment sur le coup quand on redimensionne. Pour passer d'un fullscreen (F11), à la page classique par exemple.

1 .
![image](https://user-images.githubusercontent.com/33632664/68770863-3b80a800-0627-11ea-92b6-94a2c36b87f8.png)

2.
![image](https://user-images.githubusercontent.com/33632664/68770936-5b17d080-0627-11ea-9eee-6b455b001c3b.png)

**Comment by manufitoussiwit** [comment]
Sympas le bug!
Pour éviter le pb et aussi éviter que les boutons ne soient trop petit, il vaut mieux ne pas placer cet acteur dans une boite à vue.
