### ISSUE TITLE
Acteur Synoptique bug

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#337]
L'acteur n'affiche pas les synoptiques du REDY.
Il y a un "//" dans l'URL aprés l'ip et avant le WSID : 
![image](https://user-images.githubusercontent.com/33632664/69542532-eb410880-0f8b-11ea-8988-bfd23d062b90.png)

**Comment by manufitoussiwit** [comment]
C'est un pb qui vient du renseignement de l'url du REDY : l'adresse à était rentrée avec l'ip suivit d'un `/` qui est rebalancé dans l'acteur. 
Il faut se déconnecter et se reconnecter avec la bonne adresse (sans le ``/` final).
Un future version viendra corriger l'erreur de saisie automatiquement.

**Comment by WITNicolas** [comment]
ok merci

**Comment by manufitoussiwit** [comment]
Corrigé dans la version 2.0
