### ISSUE TITLE
Acteur Journal Filtre Equipement

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#338]
Je pense qu'il y a une embrouille avec le filtre équipement. Quand je ne mets rien, il y a tout (ça je crois que c'est normal, encore que, si on ne mets rien la case TOUT devrait se selectionner automatiquement), mais quand je mets tout, il n'y a rien en fait ..

![image](https://user-images.githubusercontent.com/33632664/72098910-c5937700-331f-11ea-85e1-abf0a1cc2fa6.png)

![image](https://user-images.githubusercontent.com/33632664/72098931-d04e0c00-331f-11ea-97e1-6ea1c74410f8.png)

**Comment by manufitoussiwit** [comment]
Il semblerai qu'il y a un problème avec ce filtre. Il montre une liste multi-sélection alors qu'il attend qu'une seule sélection.

**Comment by manufitoussiwit** [comment]
C'est corrigé dans le version 2.0
