### ISSUE TITLE
Acteur Scene - Selecteur nom de variable erronée

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#342]
![image](https://user-images.githubusercontent.com/33632664/82345290-647a5f00-99f5-11ea-989b-4b4c9002e2ba.png)

Dans l'acteur, le label apparaît comme "scene" dans l'info-bulle alors que dans les faits c'est "scenekey" ... je pouvais toujours essayer de faire fonctionner cela à travers le javascript ! ... :)

**Comment by manufitoussiwit** [comment]
Bien vu!
