### ISSUE TITLE
Runtime 2.0.0-RC.1 - Acteur Bouton Poussoir inopérant

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#344]
Son action n'est pas prise en compte sur une ressource de type Consigne Logique.
L'action spécifique **enfoncé** est liaisonné à au .setpoint de la ressource. Je n'ai pas utilisé de script, uniquement la liaison directe avec la ressource en lecture / ecriture.

**Comment by manufitoussiwit** [comment]
Effectivement la liaison n'est pas migrée ici. Je vais corriger ça dès que j'ai du temps et faire une RC.2

**Comment by manufitoussiwit** [comment]
C'est corrigé dans la RC.4
