### ISSUE TITLE
Runtime 2.0.0-RC.1 - Classe label

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#345]
Cette propriété n'est pas interprétée
C'est un acteur texte avec ce contenu : `Encours <span class="label label-danger">{{nbrEncours}}</span>`

V1
![image](https://user-images.githubusercontent.com/33632664/88661340-a6501180-d0d8-11ea-8c55-bae787266ae4.png)
V2
![image](https://user-images.githubusercontent.com/33632664/88661368-b0721000-d0d8-11ea-827b-f5055976ac22.png)

**Comment by manufitoussiwit** [comment]
Il faut remplacer `label label-danger` par `badge badge-danger`.

ça vient du fait que la v2 utilise[ bootstrap v4](https://getbootstrap.com/docs/4.5/components/badge/) qui à changer le nom de la classe.

**Comment by WITNicolas** [comment]
OK merci
