### ISSUE TITLE
Acteur ecran par défaut RC4

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#346]
![image](https://user-images.githubusercontent.com/33632664/92325316-d250a200-f049-11ea-8d14-db0b4c179601.png)
 A priori la scene par défaut de l'acteur Ecran ne s'affiche pas.
Quand je navigue via les menus, tout fonctionne bien, mais si je reviens sur mon bouton Généralités, la scène n'est pas affichée.

En haut, le menu
En dessous, l'acteur Ecran

**Comment by manufitoussiwit** [comment]
Bien vu! une RC5 arrive pour corriger ça.
