### ISSUE TITLE
Runtime 2.0.0-RC.5 - Acteur Navigation ou Acteur Ecran

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#347]
4 boutons qui affichent dans le même écran.
Les 3 premiers boutons appellent la même scène en passant un argument de source, la scène ne change pas, ou tout du moins les données ne sont pas en rapport avec la source appelé. Comme si la Scène globale disait "vu que la scene qui doit être affiché dans l'écran est déjà affichée dans l'écran, ça ne sert à rien que je la change et que je rafraichisse".

ps : je viens de faire le test sur un autre site et c'est exactement la même chose qu'il se passe ... la scene est déjà affichée donc pas de refresh....

Par contre si je clique sur le 4eme bouton qui appelle une scène de type "en cours de constuction", la scène change bien.
Et si je clique sur le 2eme bouton, j'ai bien la scène avec la source du 2eme bouton qui s'affiche.

Puis cette scène reste affichée si je clique sur le bouton 1 ou 3 ... bref quand j'appelle la même scéne.
![image](https://user-images.githubusercontent.com/33632664/92412271-94d43d80-f14b-11ea-8fe2-f7d325359ab8.png)

**Comment by manufitoussiwit** [comment]
Cela vient de l'absence de propriété additionnelle sur l'acteur écran qui permet de controller le paramètre de la scène.
Je viens de l'ajouter (`prop_source` labelChaudiere) et ça marche.

Ca fait parti des différences de comportement entre la v1 et la v2. 
Dans la v1, il n'était pas nécessaire de faire ça. Ca marchait quand même (en fait, c'était pas normal que ça marche :-) )

**Comment by WITNicolas** [comment]
Ok ... donc il faut un label au niveau de l’écran ... avant le bouton appelait l'argument direct de la scène qui était embarquée et l’écran se débrouillait c'est bien ça ?
Maintenant il faut que l'acteur scène ait connaissance de l'argument qui doit être affiché ?
