### ISSUE TITLE
Runtime 2.0.0-RC.5 - Acteur Commutateur Etat

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#348]
V1: 
![image](https://user-images.githubusercontent.com/33632664/92412589-b4b83100-f14c-11ea-8498-35d48f9c0f4f.png)

RC5
![image](https://user-images.githubusercontent.com/33632664/92412608-c26db680-f14c-11ea-8d26-751540f2403f.png)

J'ai l'impression que l'acteur n'aime pas les images vides et qu'il faut absolument mettre un gif vide de 1px*1px
Quand le défaut, il y a une icone, quand normal il n'y a rien.

**Comment by manufitoussiwit** [comment]
Effectivement, la valeur n'est pas la bonne lorsqu'il n'y a pas d'image pour `faux`.

**Comment by manufitoussiwit** [comment]
Corrigé dans la 2.0.0-RC.6
