### ISSUE TITLE
Runtime 2.0.0-RC.5 Acteur Liste Déroulante

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#349]
![image](https://user-images.githubusercontent.com/33632664/92412759-6192ae00-f14d-11ea-86c9-c18ea5747ee7.png)

L'icone est déroutante, j'ai l'impression que c'est une zone de saisie analogique en mode saisie de valeur analogique avec la flèche haut pour (+) et bas pour (-).
Il faudrait uniquement la flèche bas un peu grosse pour dire que c'est une liste qui déroule et qui va donc ouvrir un panel de choix.

**Comment by manufitoussiwit** [comment]
C'est vrai que ça peut porter à confusion, mais en réalité, le déroulement vers le bas n'est pas une règle : sur PC le déroulement peut se faire automatiquement vers le haut si l'espace est insuffisant en bas. Aussi, sur iOS, il apparait le fameux rouleau et sur Android, le menu s'affiche par le centre en modale.

**Comment by WITNicolas** [comment]
Ok merci. faux problème donc.
