### ISSUE TITLE
Runtime 2.0.0-RC.5 Acteur Modale

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#350]
L'option Cliquer en dehors pour fermer est opérationnelle alors qu'elle est décochée dans le Maker.

![image](https://user-images.githubusercontent.com/33632664/92413145-006bda00-f14f-11ea-9279-15181ca3b330.png)

**Comment by manufitoussiwit** [comment]
Bien vu!
Corrigé en RC.6
