### ISSUE TITLE
[STUDIO][1.0.0-beta.1] Création d'un projet sur chemin réseau + Message d'erreur non visible

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#351]
Sur un chemin réseau du style \\\DISKSTATION\homes\WIT\CloudStation\SYNAPPS PROJET il y a un message d'erreur et le projet ne se créé pas.
Sur un chemin local cela passe pas non plus
Le message d'erreur n'est malheureusement pas visible

![image](https://user-images.githubusercontent.com/33632664/106311701-d9c94f80-6265-11eb-902d-faa2bfccf90f.png)

**Comment by manufitoussiwit** [comment]
Les messages d'erreur sont visible dans la version 1.0.0-rc.2
