### ISSUE TITLE
[STUDIO] beta1 Scène d'ouverture

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#352]
Si on supprime la scène d'ouverture, rien ne nous indique qu'il n'y a pas de scène d'ouverture de paramétrée.
Petit manque d'info.
Du coup j'ai essayé plusieurs fois d'exécuter le runtime sans succès forcément.
En résumé, il faudrait interdire une publication ou une exécution s'il n'y a pas de scène d'ouverture (le play vert)

**Comment by manufitoussiwit** [comment]
Bien vu

**Comment by manufitoussiwit** [comment]
La suppression d'une scène de démarrage sera interdite. Pour la supprimer, il faut en désigner une autre avant.
