### ISSUE TITLE
[STUDIO][1.0.0-beta.1] Bouton dupliquer un acteur absent

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#353]
A priori il n'y a pas de bouton pour dupliquer les acteurs paramétrés.

**Comment by WITNicolas** [comment]
J'ai contourné le problème en éditant directement le JSON de la scène mais ce n'est pas user-friendly (ceci dit c'est très pratique de faire comme cela aussi ...)

**Comment by manufitoussiwit** [comment]
Dans la version beta.2 on peut copier un acteur et le coller dans un acteur de disposition (même dans un autre projet!)
