### ISSUE TITLE
[STUDIO][1.0.0-beta.1] Preview de la SYNAPP sur la scene d'ouverture

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#354]
L'exécution de la scene d'ouverture pourtant sélectionnée ne fonctionne pas.
Même aprés fermeture, refresh, relance, publication, etc..

![image](https://user-images.githubusercontent.com/33632664/106331747-c201c380-6285-11eb-8443-2cdbf243f4da.png)

**Comment by WITNicolas** [comment]
Sur un chemin local 'c:/xxx' la preview est fonctionnelle.
Donc clairement les chemins réseau du type \\DISKSTATION\xxxx n'est effectivement pas bien géré dans le PROXY.

**Comment by manufitoussiwit** [comment]
Lié au pb de dossiers distant. Résolu en rc.2
