### ISSUE TITLE
[STUDIO][1.0.0-beta.1] Barre de redimensionnement menu Acteur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#355]
Si on prends la barre de redimensionnement, on peut la monter au top.
Il faudrait la limiter au max jusqu'au titre "SCENES"

![image](https://user-images.githubusercontent.com/33632664/106782998-1d97cc80-664b-11eb-9c14-f9e96911a7c9.png)

**Comment by manufitoussiwit** [comment]
Corrigé dans la beta.4
