### ISSUE TITLE
[STUDIO][1.0.0-beta.1] Création par la console Json et doublon de clé

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#356]
Lors de la création par la console nous pouvons créer les objets et surtout mettre les mêmes clés pour les acteurs. Dans l'absolu ça se comprend, il ne s'agit que de texte.
Par contre dans le Designer, rien n'indique un doublon de clé .. la notification de doublon se fait que lorsque l'on crée un acteur via les boutons classiques Ajouter.
Cela peut donc engendrer des erreurs .. et surement d'ailleurs.

Si cela ne peut être fait en automatique, est-ce qu'un bouton de type "vérification de code, d'erreurs" serait une bonne idée ?

![image](https://user-images.githubusercontent.com/33632664/106784147-4ec4cc80-664c-11eb-9d41-ecb98bc6e5de.png)

**Comment by manufitoussiwit** [comment]
Il va falloir un outil qui permet de récupérer toute les erreurs

**Comment by WITNicolas** [comment]
Ok. Dans tous les cas, par le JSON, c'est le mode Avancé si je peux dire.
Donc même un outil externe (si ça existe), dans un premier temps, je pense que ça irait.

**Comment by manufitoussiwit** [comment]
Corrigé dans la rc.5
