### ISSUE TITLE
[STUDIO][1.0.0-beta.2] Ajout d'un LEAD ACTOR

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#358]
L'action du bouton n'a pas l'effet escompter. (Je suppose le choix d'ajout de stack, canvas, ...)

![image](https://user-images.githubusercontent.com/33632664/106936499-f01b5380-671c-11eb-80b8-1cb166aae3fc.png)

**Comment by manufitoussiwit** [comment]
corrigé en beta.3
