### ISSUE TITLE
[STUDIO][1.0.0-beta.2] Bouton Dupliquer une scène

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#359]
Le bouton "Dupliquer" crée une erreur Scen8 is not empty. Dans le dossier du projet, cela crée bien le dossier Scene8 (d'ailleurs c'est étonnant je pensais que les dossiers s'appelleraient par leur clé) et ce dossier est vide.

![image](https://user-images.githubusercontent.com/33632664/107067167-2faa7400-67df-11eb-960f-5634dc5caee7.png)

**Comment by manufitoussiwit** [comment]
Les scènes et les composites ont un identifiant interne pour pouvoir les stocker sur le disque dans un dossier qui ne change pas alors que leur clé peut changer. Le bug c'est parce que bien sur je me suis pas servi de cette identifiant lors du clonage :)  

corrigé dans beta.3
