### ISSUE TITLE
Retour Maker depuis Runtime en mode desktop

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#36]
Quand sur le maker en rubtime desktop et que l on fait un deploiement puis une execution pour controle, tout se passe bien ... sauf quand on veut faire une modif et du coup revenir en mode edition, on ne peut revenir en arriere.

**Comment by ericvoignier** [comment]
En mode desktop:

- Prévoir menu de retour au _Maker_ depuis _Runtime_ ou 
- Forcer l'ouverture d'un deuxième écran pour _Runtime_

**Comment by manufitoussiwit** [comment]
Un bouton de retour a été ajouté dans la version 1.4.0 à venir
