### ISSUE TITLE
[STUDIO][1.0.0-beta.2] Longueur des clés

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#361]
Une clé trop longue est accepté mais n'est pas fonctionnelle quand on l'utilise.
Une clé courte fonctionne trés bien.
Il faudrait indiquer qu'une clé est trop longue

![image](https://user-images.githubusercontent.com/33632664/107129519-25af7080-68c6-11eb-81b9-7149226229f8.png)

**Comment by manufitoussiwit** [comment]
Corrigé dans la beta.3
