### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Ajout d'une scène

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#364]
L'ajout d'une scène ne fonctionne a priori pas 
![image](https://user-images.githubusercontent.com/33632664/109476266-fa5c1380-7a76-11eb-8cff-e83d8b41c54c.png)

**Comment by manufitoussiwit** [comment]
On a des pb avec les disques réseau.

**Comment by WITNicolas** [comment]
A priori sur un chemin local même sans Espace, ça ne passe pas non plus.
![image](https://user-images.githubusercontent.com/33632664/110044445-6ecdd580-7d49-11eb-8298-a658ba619a38.png)

**Comment by WITNicolas** [comment]
OK. En fait c'est le Dossier scene4 qui était déjà créé mais non supprimé dans l'orborescence je ne sais pas pourquoi.
J'ai supprimé le dossier et j'ai pu le créer comme il faut.
Je pense que le JSON de configuration ne connaissait pas ce dossier, et vu qu'il voulait le créer, il ne pouvait pas .... vu qu'il existait ... mais il ne le savait pas ....

Du coup je ne pense pas que ça soit un "vrai" bug ... je pense que tu peux clôturer.

**Comment by WITNicolas** [comment]
Je viens de comprendre l'origine du problème. Et je pense que c'est un bug.

Manip : 
Je construis un projet avec des scenes.
Je désactive la publication de certaines scènes avec l'option "EXCLU" (on va dire la scene8 par exemple)
J'exporte le template.
Je démarre un autre projet à partir du template...et le dossier de la Scene8 à suivi mais vide ....

Donc si je souhaite créer une nouvelle scene j'ai le message d'erreur.

A gauche les scenes à partir du template, a droite le JSON du nouveau projet ave cle template.
A gauche on voit le dossier scene8, à droite il n'apparait pas dans le JSON (logique la scene est exclue ..)
![image](https://user-images.githubusercontent.com/33632664/115022017-139d1000-9ebd-11eb-9bdf-42c5d978d40a.png)

**Comment by WITNicolas** [comment]
Je vais creuser encore il y a autre chose. Si je créé une scene vide ça passe ... mais un scene peuplé ça bug

**Comment by manufitoussiwit** [comment]
C'est bien un pb avec la gestion des dossiers distants. C'est résolu dans la rc.2
