### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Acteur switch image, mauvais intitulé d'une property

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#366]
Je suppose que les 2 propriétés après les libellés titres sont pour mettre des images.
![image](https://user-images.githubusercontent.com/33632664/109526446-d7e7eb80-7ab2-11eb-9dbd-0b844acd2972.png)

**Comment by manufitoussiwit** [comment]
Corrigé dans la beta.5
