### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Visuel des property qui sont liaisonnées / modifiées

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#367]
Il serait intéressant d'avoir un rappel dans les accordéons pour indiquer qu'une propriétés à été modifiée / liaisonnée. ça éviterait d'avoir de chercher pourquoi une représentation / réaction n'est pas adapté à ce que l'on souhaite au niveau rendu si on sait que certaine chose ont été modifié. (vu que les modif peuvent venir de beaaaaauuuucoup d'endroit différent)

![image](https://user-images.githubusercontent.com/33632664/110206396-a2aa1780-7e7d-11eb-8352-a64c00ffd3b7.png)

**Comment by manufitoussiwit** [comment]
C'est la beta.4
