### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by WITALD** [witsa/synapps#37]
Évitez d'être Case Sensitive dans les chemins relatif

![liaisoncasesensitive](https://user-images.githubusercontent.com/35064776/34520846-f80af8e0-f08a-11e7-9797-f0d5e8c5bc32.PNG)

**Comment by ericvoignier** [comment]
Le chemin relatif n'est plus case sensitive et est corrigé automatiquement.
Ex: ci-dessous **_range1_** => devient **_RANGE1_**
![image](https://user-images.githubusercontent.com/9974702/37413286-fe522d06-27a6-11e8-83da-712e61da015f.png)

![image](https://user-images.githubusercontent.com/9974702/37413310-0a463c24-27a7-11e8-963b-c94b3986de71.png)

**Comment by ericvoignier** [comment]
Sera déployé avec la **1.3.5**
