### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Lien vers librairie image non pris en compte

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#370]
J'ai créé une image en bibliotheque qui est fonctionnelle en via l'encodage
![image](https://user-images.githubusercontent.com/33632664/110206955-392c0800-7e81-11eb-97be-0f034040abc7.png)
Mais quand je la BIND, elle n'apparait pas (j'ai fais la même chose sur la librairie TEXT qui fonctionne trés bien)
![image](https://user-images.githubusercontent.com/33632664/110206989-5fea3e80-7e81-11eb-9720-2c8d679de1ea.png)

EDIT :
Ha oui en fait non, ça ne lui plait pas du tout ......
J'attendrais le DESIGNER pour cette partie :)
![image](https://user-images.githubusercontent.com/33632664/110207052-9aec7200-7e81-11eb-9a4b-d1213e564240.png)

**Comment by manufitoussiwit** [comment]
Tu peux faire ça mais avec les constantes. 
Les images en librairie sans designer c'est pas tout a fait comme ça : 

- tu glisses le fichier image dans le répertoire `pictures` du projet. 
- puis tu vas dans le fichier `JSON` et tu crées un champ correspondant  : 

```js
{
  "monImage": "nom du fichier"
}
```

**Comment by WITNicolas** [comment]
t as raison, merci, j'avais oublié que tout est en dossier sur le PC !
