### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Acteur detail reflet Consigne Logique

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#371]
Pour le reflet consigne analogique, il y a une confirmation a donner (ce qui est trés bien d'ailleurs), mais du coup sur le reflet consigne logique, cette validation n'apparait pas et pour le coup c'est dommage ne pas avoir la même réaction. (je pense idem pour le reflet Tableau de Consigne... bref toujours avoir des confirmations.

![image](https://user-images.githubusercontent.com/33632664/110220013-2e926280-7ec3-11eb-8078-d6b73809f8d7.png)

**Comment by WITNicolas** [comment]
Je confirme qu'il faudrait la confirmation de l'action.
1 . pour être cohérent avec les autres reflets
2 . c'est dangereux de mettre une action directe, sachant que ça peut être utiliser sur du tactile .. et un miss click arrive très vite.

**Comment by manufitoussiwit** [comment]
C'est la version 1.1.0 de Studio et dans la version 2.3.0 du runtime qui arrive
