### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Acteur Journal de variables 

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#372]
Dans le studio il manquerait l'information du nombre d'évènements filtrés en fonction des choix spécifiques de l'acteur.
Dans le maker c'était présent et ça permettait de savoir par exemple le nombre d'évènement encours et d'afficher cette valeur ...

Le soucis c'est que si on importe (dans le futur bientôt ...) une Synapp réalisée avec le MAKER, cette info va sauter.

**Comment by manufitoussiwit** [comment]
L'info existe toujours, elle n'est pas affichée dans l'inspecteur mais elle est disponible pour les liaisons et script dans le champ "count".

**Comment by WITNicolas** [comment]
ok merci
