### ISSUE TITLE
[STUDIO][1.0.0-beta.3] Acteur Liste d'Etat

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#374]
Dans le Specific de l'acteur, il manque des Filtres.
Actuellement il y a : Ensemble / Ressource
Il faudrait rajouter : Groupe / Zone / Equipement pour être cohérent avec les Acteurs FILTER (collection/ zone/ device/ Group)

**Comment by manufitoussiwit** [comment]
Et bien, il n'y sont pas parce que malheureusement l'API ne permet de filtrer par ces critères.

**Comment by WITNicolas** [comment]
Es-tu sûr de ton coup pour l'API ?
Dans le maker c'était présent .. xD ... ou alors ça y était mais ça ne fonctionnait pas .. pitêtre ... xD
![image](https://user-images.githubusercontent.com/33632664/112843119-8b3c0400-90a2-11eb-884c-506cb4550599.png)

**Comment by manufitoussiwit** [comment]
> Es-tu sûr de ton coup pour l'API ?
> Dans le maker c'était présent .. xD ... ou alors ça y était mais ça ne fonctionnait pas .. pitêtre ... xD
> ![image](https://user-images.githubusercontent.com/33632664/112843119-8b3c0400-90a2-11eb-884c-506cb4550599.png)
> 
> Pour le journal c'est pareil, ça utilise les mêmes filtres.

et bien c'est exactement ça! :-) ça ne marchait pas. 
Pour le journal ça marchait.
