### ISSUE TITLE
[STUDIO][1.0.0-beta.4] Derouler les acteurs Stack et Grid

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#377]
Les fermetures des acteurs ne fonctionnent plus
![image](https://user-images.githubusercontent.com/33632664/112727358-76386700-8f22-11eb-9c2f-ff2affb8d3bc.png)

**Comment by manufitoussiwit** [comment]
Bien vu! C'est corrigé pour la beta.5
