### ISSUE TITLE
[STUDIO][1.0.0-beta.4] Gestion des DATA avec plusieurs HOST

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#379]
Le fait d'être connecté sur un REDY, cela ne met pas en phase les ressources.
C'est à dire que si le HOST n'est pas choisi en SET DEFAULT, il y a toujours les data du site qui est en SET DEFAULT.

Par exemple
Je suis sur la chaufferie qui est en SET DEFAULT.
Je me connecte sur une sous station pour déployer/contrôler le fonctionnement de ma SYNAPP.
Si je ne la mets pas en SET DEFAULT, je vois toujours les données de la chaufferie.

Si je me connecte sur une UC, c'est pour gérer justement l'UC avec ses propres DATA, donc pour moi cela n'a pas d'intérêt d'avoir ce bouton SET DEFAULT qui devrait être justement lié au HOST .

**Comment by WITNicolas** [comment]
Evidement, une fois que la SYNAPP est publiée sur l'UC, il y a bien les données du site en question.
C'est uniquement quand tu es dans le STUDIO. Mais je viens de comprendre que tu peux par ce biais controler que la SYNAPP est bien fonctionnelle dans plusieurs environnement.
En fait le fait de mettre en  surbrillance le HOST ne le sélectionne pas vraiment, c'est que je viens de comprendre .....

**Comment by manufitoussiwit** [comment]
J'ai changé la qualification de défaut à actif. ça améliore peut être la clarté de la nuance entre connexion et actif.

**Comment by WITNicolas** [comment]
Oui c'est mieux de faire comme ça. Actif signifie clairement que l'on travaille dans cet environnement.
