### ISSUE TITLE
[STUDIO][1.0.0-beta.4]  Sortir d'un publishing qui n'aboutit pas

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#380]
A priori il n'y a pas possibilité d'ABORT un PUBLISHING qui n'aboutit pas.
Dans mon cas, je suis sur un VPN avec une connexion qui est faiblarde et je ne sais plus si je suis connecté, toujours en cours, ou si ça a planté.
Il faudrait prévoir un bouton sur l'info d'avancement PUBLISHING, ou bien tout simplement sortir automatiquement en indiquant que la PUBLICATION a été ABORT.

**Comment by WITNicolas** [comment]
Bon j'ai laissé tourné et c'est arrivé au bout, du coup le fait de mettre uniqumement PUBLISHING n'est peut être pas assez complet.

**Comment by manufitoussiwit** [comment]
Présent dans la v1.1.4 et amélioré dans dans la v1.1.5
