### ISSUE TITLE
[STUDIO][1.0.0-rc1.0] Zone de texte

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#385]
Le mode auto ne permet d'utiliser la poignée en H et V, mais uniquement en V
Horizontal ok
Vertical ok
None ok

![image](https://user-images.githubusercontent.com/33632664/114068571-5a2bb280-989e-11eb-9403-3c95b9304139.png)

**Comment by manufitoussiwit** [comment]
Bien vu, c'est une erreur : c'est pas `auto` mais `both` pour les deux.

**Comment by manufitoussiwit** [comment]
Par défaut c'est `vertical`

**Comment by manufitoussiwit** [comment]
C'est corrigé dans la rc.2
