### ISSUE TITLE
[STUDIO][1.0.0-rc1.0] Acteur Switch Image Texte vrai/faux ne s'affiche pas.

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#386]
Les textes ne sont affichés sur le OnHover de l'image
Logiquement il devrait y avoir le Texte quand image pour vrai et l'autre texte quand image pour faux

![image](https://user-images.githubusercontent.com/33632664/114167532-598f2c80-992f-11eb-8416-8def248f6a2e.png)

**Comment by manufitoussiwit** [comment]
C'est corrigé dans la version 2.1.2 du runtime et inclus dans la version [v1.0.0-rc.2](https://github.com/witsa/synapps/releases/tag/1.0.0-rc.2) de Studio
