### ISSUE TITLE
[STUDIO][1.0.0-rc1.0] Charts Evolution

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#388]
Pouvoir masquer l'aiguille pour faire ce genre de design.
ça rejoins peut être un éventuel prise en charge du canvas gauge js directement

![image](https://user-images.githubusercontent.com/33632664/114177715-058b4480-993d-11eb-836e-bda994b464d2.png)

**Comment by manufitoussiwit** [comment]
On peut masquer l'aiguille en choisissant une couleur transparente pour elle.
