### ISSUE TITLE
Accentuation aprés upgrade V1.3.0

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#39]
Apres avoir fait un upgrade en V1.3.0, les accentuations ont disparus en laissant à la place un caractère non reconnu. (Exemple **_Météo_**)
Si on les ré-écris dans les objets cela reste comme il faut après déploiement

![accent](https://user-images.githubusercontent.com/33632664/34613625-b01102d2-f22e-11e7-96d3-d5a70f6a6062.png)

**Comment by ericvoignier** [comment]
L'encodage a été modifié mais en effet les SynApps 1.2.1 ouvertes en 1.3.0 présentent un pb d'encodage résolu après modification. Je propose devant le faible impacte de cloturer ?

**Comment by WITNicolas** [comment]
Oui bien sur, c’était pour avoir une traçabilité. Mais effectivement impact très mineur

**Comment by ericvoignier** [comment]
OK !
