### ISSUE TITLE
[STUDIO][1.0.0-rc1.0] Acteur Période Incohérence du format avec Acteur Journal et Journal de Reflet

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#390]
Acteur   Période |  
-- | --
Rends les valeurs : | all today last24 week weekprevious month monthprevious year yearprevious
  |  
Acteur Journal |  
Attends les valeurs : | date de début et une date de fin en format ISO
  |  
Acteur Journal des Reflets |  
Attends les valeurs : | date de début et une date de fin en format ISO
  |  
  | Conclusion, il manque 2 infos dans l'acteur Periode pour pouvoir faire   une liaison correcte

**Comment by manufitoussiwit** [comment]
Il manque les champs bornes `dateFrom` et `dateTo` dans les propositions de liaison sur l'acteur période. Il seront présent en rc.2

**Comment by manufitoussiwit** [comment]
Corrigé dans la version [v1.0.0-rc.2](https://github.com/witsa/synapps/releases/tag/1.0.0-rc.2)
