### ISSUE TITLE
[STUDIO][1.0.0-rc.1] Ajout d'un bouton Dupliquer

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#393]
Pour faciliter la manipulation suivante sur les acteurs : 
Sélection puis Copier
Sélection puis Coller

Sélection puis Dupliquer

![image](https://user-images.githubusercontent.com/33632664/114191974-43906480-994d-11eb-96b9-7451834aa551.png)
![image](https://user-images.githubusercontent.com/33632664/114192017-4f7c2680-994d-11eb-98a0-1c148e5193f8.png)

**Comment by manufitoussiwit** [comment]
Avec la version 1.1.0, on peut "coller" en ouvrant le menu sur n'importe quel acteur. ça a pour effet de coller dans le même parent. C'est presque un "dupliquer" :-)

**Comment by WITNicolas** [comment]
Mouais .... admettons .... réponse de développeur quoi :) .... ça va me va :)
