### ISSUE TITLE
[STUDIO][1.0.0-rc.2] Dysfonctionnement Contenu Acteur Bouton

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#397]
On ne peut plus éditer le contenu de l'acteur bouton.
![image](https://user-images.githubusercontent.com/33632664/115125454-716a4e80-9fc8-11eb-8af8-6a6efda07170.png)

![image](https://user-images.githubusercontent.com/33632664/115125427-47b12780-9fc8-11eb-96e1-8ebfc8803b05.png)

**Comment by manufitoussiwit** [comment]
Bien vu! Régression!!!

**Comment by manufitoussiwit** [comment]
corrigé en rc.3
