### ISSUE TITLE
[STUDIO][1.0.0-rc.2] Erreur d'exécution dans le Runtime d'une Synapp Publiée

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#398]
La publication se passe bien entre STUDIO et REDY, par contre l'exécution ne fonctionne pas sur le REDY.
Mon REDY est en version 13.2.0

![image](https://user-images.githubusercontent.com/33632664/115214007-64ea1100-a102-11eb-962d-d767c024d8a2.png)

**Comment by WITNicolas** [comment]
Tu as pu identifier ou tout du moins reproduire ?
C'est juste pour être sûr que ça ne provienne pas (encore) d'un particularité de mon réseau ou que sais-je... xD

**Comment by manufitoussiwit** [comment]
> Tu as pu identifier ou tout du moins reproduire ?
> C'est juste pour être sûr que ça ne provienne pas (encore) d'un particularité de mon réseau ou que sais-je... 

Je n'arrive pas à reproduire, il faudrait que je vois l'erreur sur ton REDY.

**Comment by WITNicolas** [comment]
Erreur dans une intégration JS
Le nom du fichier JS ne doit pas contenir de caractères non autorisés.
Il s'agit d'un label (pas d'espace, pas d'accent, pas de - (tiret du 6))
Merci manu
