### ISSUE TITLE
[STUDIO][1.0.0-rc.3] Rendu dans le designer qui ne fonctionne pas

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#402]
**RC3**
Mise à jour RC3.
Installation directe sur une RC2 déjà présente sur le PC: Erreur de preview sans message d'erreur
Après redémarrage du PC, l'erreur est toujours présente.
Suppression de la RC3 et réinstallation propre de la RC3, cela ne fonctionne toujours pas.

**RC2**
Suppression et réinstallation propre de la RC2.
La preview du designer est à nouveau fonctionnelle.

En résumé, il y a un truc qui bloque dans la RC3

**Comment by manufitoussiwit** [comment]
C'est corrigé en rc.4
