### ISSUE TITLE
[STUDIO][1.0.0-rc.3] Ergonomie Selection Acteur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#403]
Si tous les acteurs Stack / Canvas sont fermés dans la partie sélection, il est impossible de retrouver un acteur sur lequel on aurait cliqué sur le Designer.
Il faudrait que la Stack/Canvas parent s'ouvre et mette en surbrillance l'acteur.
Dans l'absolu ce n'est pas "trop" gênant vu que l'on accède quand même au paramétrage de l'acteur.

C'est simplement une question de clarté.

![image](https://user-images.githubusercontent.com/33632664/117773760-fc8ddb80-b238-11eb-8f30-a77893b787c1.png)

**Comment by manufitoussiwit** [comment]
Ce sera corrigé dans la version 1.0.2
