### ISSUE TITLE
[STUDIO][1.0.0-rc.3] 1er Déplacement d'un acteur sur une grille

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#406]
A la créations d'un acteur que l'on positionne sur une grille, l'acteur se positionne en haut à gauche de la scène.
Cependant, il n'a pas de coordonnées dans les propriétés de disposition (vide).

Ce qui fait qu'au premier déplacement de l'acteur avec la souris, l'acteur ne sait pas se positionner et revient en haut à gauche avec cette fois les coordonnées de position remplies ( 0,0 )
 
Et donc maintenant l'acteur peut être déplacé à la souris convenablement.

Bref, il faudrait qu'à la création de l'acteur, il y ait des coordonnées ( 0,0 ) (haut,gauche) qui soit renseignées par défaut.

**Comment by manufitoussiwit** [comment]
Bien vu, c'est corrigé dans la rc.5
