### ISSUE TITLE
[STUDIO][1.0.0-rc.5] JSON de l'acteur DROPDOWN

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#408]
Il faudrait que dans les options de la liste déroulante, ce soit formater comme suit : 
[
  {"value":"value1","text":"Option 1"},
  {"value":"value2","text":"Option 2"},
  {"value":"value3","text":"Option 3"}
]

Et non pas en ligne comme ça par défaut : 
[{"value":"value1","text":"Option 1"},{"value":"value2","text":"Option 2"},{"value":"value3","text":"Option 3"}]

ça serait plus lisible pour l'utilisateur.
là il n'y a pas beaucoup d'option, mais la liste peut être trééééés longue aussi

**Comment by manufitoussiwit** [comment]
Bien vu! J'ajoute ça dans la rc.6
