### ISSUE TITLE
[STUDIO][1.0.0-rc.5] Liste Projets Récents

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#409]
Juste un léger soucis de mise en page quand la liste est longue.
![image](https://user-images.githubusercontent.com/33632664/121916152-2d7b9780-cd34-11eb-8f2e-842cf6ea2030.png)

**Comment by manufitoussiwit** [comment]
Heu c'est pas censé en montrer autant, seulement les 10 ou 15 plus récents :-) !!! Je vais corrigé ça pour la rc.6

**Comment by manufitoussiwit** [comment]
Finalement, j'ai corrigé en ajoutant une barre de défilement. Ce sera dans la rc.6

**Comment by WITNicolas** [comment]
Bien vu c'est une bonne solution aussi
