### ISSUE TITLE
[STUDIO][1.0.0-rc.5] Bulle d'aide sur Composite

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#410]
A priori l'effet Bulle d'aide ne fonctionne pas sur un acteur de type Composite.

**Comment by manufitoussiwit** [comment]
ça se passe plus généralement sur les acteurs de disposition avec des acteurs enfants. C'est corrigé dans la version de Studio et prochainement dans la version 2.1.3 du runtime

**Comment by manufitoussiwit** [comment]
Heu c'est pas censé en montrer autant, seulement les 10 ou 15 plus récents :-) !!! Je vais corrigé ça pour la rc.6
