### ISSUE TITLE
[STUDIO][1.0.0-rc1.0.1] Taille par défaut des acteurs

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#414]
Il faudrait peut être supprimer la taille par défaut de 200/200 et mettre auto/auto
En fait dans 100% cette taille doit être enlevée. Ce qui n'est pas gênant en soit vu que l'on peut toujours attraper l'acteur pour le déplacer.

Le fait de laisser cette taille par défaut est perturbant car on impose quelque chose qui n'est pas voulu.

**Comment by manufitoussiwit** [comment]
Dans la version 1.0.2, j'ai enlevé cette définition par défaut sauf sur la modale et la jauge.
