### ISSUE TITLE
[STUDIO][1.0.1] Nouvelle Variante Acteur Bouton

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#415]
Pour afficher les Modales on fait appel à un script OnClick : 

var modalTooltip = context.stage.findByKey('modal1');
modalTooltip.properties.isShown = true;

Pourquoi ne pas avoir une Variante xD .... Tu as ouvert la boite de Pandore ... désolé. xD
Variante + Sélection de la modale que l'on souhaite (comme pour les Glyph)

**Comment by manufitoussiwit** [comment]
Une variante de modale sera présente dans la v1.1.0 qui permettra de sélectionner l'acteur déclencheur de son affichage.
Il y aura peut-être plus d'option, comme pouvoir définir l'acteur qui déclenche sa fermeture ou bien le type d'évènement qui déclenche l'affichage (pas forcément le click, ça peut être le survol, ...)

**Comment by WITNicolas** [comment]
Oui c'est plus logique dans l'autre sens .... :) Variante de Modale ça me plait bien.
Je suis d'accord avec toi, il faudra choisir l'option qui ouvre et l'option qui ferme

**Comment by manufitoussiwit** [comment]
La variante Modale au clic remplit le rôle.
