### ISSUE TITLE
[STUDIO][1.0.0-rc1.0.1] Liste des agendas dans acteur Agenda

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#416]
La liste n'est pas extensible, ou n'a pas d'ascenseur. (Il me semble c'est pareil pour l'acteur Synoptique)
![image](https://user-images.githubusercontent.com/33632664/126352298-a57cb9a8-cc6c-4b01-a8e4-b6e92693b577.png)

**Comment by manufitoussiwit** [comment]
Normalement, il y a un ascenseur.

**Comment by WITNicolas** [comment]
Je confirme qu'il n'y a pas d'ascenseur de disponible. :)

**Comment by manufitoussiwit** [comment]
J'ai fini par regarder avec beaucoup d'agenda : y a bien l'ascenseur.... mais une fois que j'ai corrigé la requête qui alimente la liste :-)
Elle n'allait chercher que les 10 premiers seulement :-) donc rien à scroller. 
J'ai corrigé pour les synos et les préparation aussi. Ce sera dans la 1.0.2

**Comment by WITNicolas** [comment]
Mouais j ‘ prefere ! 😂 :)
