### ISSUE TITLE
Ré-utilisation des composites Maker 

### ISSUE THREAD

**Issue by jyknecht** [witsa/synapps#417]
Bonjour,
peut on réutiliser les composites créer dans le Maker dans le Studio ? si oui comment.
Cordialement

**Comment by WITNicolas** [comment]
Bonjour JeanYves
Non ce n'est malheureusement pas possible dans le sens où des instructions sont différentes.
Les composites doivent être repensé.
As-tu un composite en particulier en tête ?
Cordialement

**Comment by jyknecht** [comment]
Bonjour Nicolas,
j'espère que as passer de bonne vacances
je n'avais pas trop d'espoir , mais j'essayais.
C'est pour les jauges que tu m'avais envoyées, elle ne marche plus dans la
version Maker et je les utilise pour suivre la qualité d'air dans les
écoles.
Comme c'est bientôt la rentrée, je dois faire la migration vers le studio.
En abusant, as tu un modèle de synapps, j'ai du mal avec la syntaxe dans
les événements.
Cordialement
JYK

Le jeu. 19 août 2021 à 14:13, WITNicolas ***@***.***> a
écrit :

**Comment by WITNicolas** [comment]
Merci, trés bien :)
Je t'ai fais parvenir un mail avec un template pour t'en inspirer, il y a pas mal de petites choses dedans
