### ISSUE TITLE
[STUDIO] Déplacement Acteur 

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#421]
Un petite amélioration pour le déplacement des objets.
Par défaut il serait intéressant que les flèches de direction puisse être utilisées pour le déplacement.

Genre MAJ+Fleche

ça permettrait d'aller plus vite dans la disposition précise, plutot que d'ouvrir la DISPOSITION.

**Comment by manufitoussiwit** [comment]
Présent dans la version 1.3.0
