### ISSUE TITLE
[STUDIO][1.0.3] Rappel d'une modification dans la property (barre bleue)

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#423]
Dans la property Bordure, il n'y a pas le rappel qu'une propriété a été modifiée. (la petite barre bleue)
![image](https://user-images.githubusercontent.com/33632664/135417491-c1687ba7-6234-4c78-8e5e-1f506ef36ac7.png)

**Comment by manufitoussiwit** [comment]
Bien vue! Elle a été déplacé dans cette section mais c'est encore l'ancienne "Effets" qui réagit.

**Comment by manufitoussiwit** [comment]
C'est corrigé dans la révision 2021-09-30T12:45:00
