### ISSUE TITLE
[STUDIO][1.0.3] Bulle Info ne s'affiche plus

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#424]
J'ai 2 réactions contradictoires entre l'execution via le STUDIO ou dans le REDY
Via STUDIO j'ai la bonne info bulle qui s'affiche, et en direct sur le REDY, l'info bulle ne s'affiche pas. (ne s'affiche plus j'ai envie de dire, parce que je suis persuadé que cela fonctionnait sur des versions antérieures)

**Comment by manufitoussiwit** [comment]
Les bulles sont placées sur des composites, sur des acteurs ?

**Comment by WITNicolas** [comment]
Ne pas tenir compte, je pense que c'est parce que j'etais sur un acteur Empilement.
J'ai déplacé dans un acteur à l'intérieur et tout est rentré dans l'ordre.

J'ai essayé les 2 et c'etait bizarre.
