### ISSUE TITLE
[STUDIO] Message d'erreur à la connexion

### ISSUE THREAD

**Issue by jyknecht** [witsa/synapps#426]
Suite au changement de MdP sur Redy 14, la modification du MdP sur studio renvoi :
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

JYK

**Comment by manufitoussiwit** [comment]
Salut, y a t il  des caractères très spéciaux dans le mot de passe ?

**Comment by jyknecht** [comment]
Bonjour,
non pas du tout.


Le ven. 5 nov. 2021 à 15:20, Emmanuel FITOUSSI ***@***.***> a
écrit :

**Comment by manufitoussiwit** [comment]
Un caractère comme le signe € peut-être?

**Comment by jyknecht** [comment]
oui, mais je ne le considérait pas comme exceptionnel

Le lun. 8 nov. 2021 à 09:53, Emmanuel FITOUSSI ***@***.***> a
écrit :

**Comment by WITNicolas** [comment]
Je prends part à la discussion.
Attention à la V14 qui impose maintenant des mots de passe fort avec Maj Min Chiffre Caractères spéciaux etc...

**Comment by manufitoussiwit** [comment]
Oui, il vaut mieux éviter les caractères @ : € ou tout autre caractère non UTF 8 dans les noms d'utilisateur et le mot de passe
