### ISSUE TITLE
[STUDIO] [REDY] Graphique ne s'affiche plus

### ISSUE THREAD

**Issue by jyknecht** [witsa/synapps#429]
Bonjour,
Les graph ne s'affiche pas dans le REDY (apiRoot is required.), mais fonctionne parfaitement en exécution dans le studio.
Le lien dans la console de développement affiche bien le graph dans une nouvelle fenêtre .
Redy V14.1.0
Cordialement

**Comment by manufitoussiwit** [comment]
Bonjour, c'est peut-être un pb de cache navigateur. Le REDY à l'air de proposer l'ancienne version du grapheur dans le runtime. Essayez de vider cache pour voir si ça résout le pb.

**Comment by jyknecht** [comment]
Bonjour,
C'est bien ça.
Merci
