### ISSUE TITLE
[SYNAPP] Synapp Veepee

### ISSUE THREAD

**Issue by JYK-WIT** [witsa/synapps#437]
Bonjour, 
on trouve une image en paramètre de scène et la même dans l'image de fond de l'aspect de l'empilement ROOT de cette scène.
J'ai supprimer celle du paramètre scène, quelle est sont utilité ?
JYK

**Comment by manufitoussiwit** [comment]
Salut! 
Elle sert à renseigner la scène principale pour qu'elle affiche cette image dans la partie droite inférieur.
