### ISSUE TITLE
[STUDIO][1.1.0-beta] Affichage de l'explorateur de NOD

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#438]
Quand une Source est sélectionnée, l'affichage de la liste de NOD se calle sur la Source elle-même (donc le parent)
![image](https://user-images.githubusercontent.com/33632664/156751554-1f839cbd-b6fe-4893-9827-d539332b3152.png)

Il serait préférable que la liste s'ouvre sur les Enfants de la Source, ce qui me parait plus logique vu que la racine est logiquement choisie par la Source
![image](https://user-images.githubusercontent.com/33632664/156751670-6e4f204f-226e-4244-8ddc-154fff3d17a3.png)

**Comment by manufitoussiwit** [comment]
Bien vu! ce sera corrigé dans la version 1.1.0
