### ISSUE TITLE
Inversion min/max acteur curseur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#44]
Il serait intéressant de pouvoir inverser le haut et le bas. En effet quand on met le slider en mode vertical la direction + se fait vers le bas et la direction - se fait vers le haut quand on le liaisonne par exemple à une ressource Consigne Analogique pour réaliser un réglage de température.

Peut être dans les propriétés mettre un angle de rotation 0° 90° 180° 270° pour pouvoir afficher convenablement l'action au lieu de la case Vertical/Horizontal.

**Comment by ericvoignier** [comment]
En effet le min du slider est à gauche ou en haut selon horizontal ou vertical.
Proposition d'ajout d'une propriété spécifique: _inverser_ permettant de basculer:
- gauche/droite <=> droite/gauche,
- haut/bas <=> bas/haut

Remarque: le slider présente une instabilité lorque la valeur min est supérieure à max. A corriger

**Comment by ericvoignier** [comment]
Solution ci-dessus implémenté
![image](https://user-images.githubusercontent.com/9974702/35352826-76fa70ca-0145-11e8-8ae3-76c5f3a5c590.png)
Déploiement avec 1.3.3

**Comment by ericvoignier** [comment]
Déployé 1.3.3
