### ISSUE TITLE
[STUDIO][1.1.0-beta] Bordure Modale

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#445]
La courbure de bordure n'est pas prise en compte sur l'acteur Modale.
Le contenu "subit" bien la courbure, mais l'acteur Modale en lui-même non.

![image](https://user-images.githubusercontent.com/33632664/159926020-2aa11f9f-320b-4ce3-9244-9ef81ee95850.png)

**Comment by manufitoussiwit** [comment]
Il y a un moyen d'avoir la courbure : 
Il faut d'abord ajouter cet acteur html : 
```text
SYNAPPS-STUDIO-ACTOR|{"type":"display/html","key":"modal-style","properties":{"content":"<style>\n  .ember-modal-dialog {\n    box-shadow: none;\n    background-color: transparent;\n  }\n</style>"}}
```
Il a pour effet d'enlever l'ombre et le fond de ce qui supporte la modale.

Ensuite, il faut rajouter ce qu'on vient d'enlever à l'acteur modale : 
- ombre ; `0 0 10px #222`
- couleur de fond : `white`

![image](https://user-images.githubusercontent.com/35595723/159935596-5dc9a7b4-5baa-4e17-a6f6-1e52264bc555.png)

**Comment by manufitoussiwit** [comment]
Dans les futures version, ça pourrait être de base comme ça.

**Comment by manufitoussiwit** [comment]
Dans la version du Runtime 2.4.0
