### ISSUE TITLE
[STUDIO][1.1.0-beta] Preview Reflet Courbe de Chauffe

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#449]
La preview dans Studio ne donne pas la réalité du rendu
Nota, le reflet est posé dans une scene qui elle-même est dans une boite à vue .... 

![image](https://user-images.githubusercontent.com/33632664/160702661-84c362a5-0483-4a59-88ba-86968aa2bd8e.png)

**Comment by manufitoussiwit** [comment]
On dirait que la taille de la modale n'est pas la même. Peut-etre une définition en `em`. Il faudrait que je jette un coup d'oeil.

**Comment by WITNicolas** [comment]
Je vais quand meme creuser un peu pour être sûr de ce "problème".
