### ISSUE TITLE
[SYNAPP] Superposition d'acteurs

### ISSUE THREAD

**Issue by WIToliv** [witsa/synapps#455]
Bonjour, 
Je souhaiterais superposer des images suivant le mode en cours.
ex : Une image de pompe en marche / arrêt avec l'acteur "Images Interrupteur" et le même acteur superposé pour le mode défaut.
J'ai essayé de les positionner l'un après l'autre, de jouer avec le z-index mais je coince.
Merci

![Capture d’écran 2022-04-04 154204](https://user-images.githubusercontent.com/101122670/161556768-3fd13c59-00fe-4f13-8486-cf37b205a6d0.png)

**Comment by manufitoussiwit** [comment]
Salut! as-tu utilisé un acteur toile pour les superposer ?

**Comment by WIToliv** [comment]
Salut, non je les ai mis dans uns stack.

**Comment by WITNicolas** [comment]
Donc ce n'est pas possible de superposer avec stack, sachant que son rôle est d'empiler horizontalement/verticalement les acteurs.
Seul le Canvas permet de positionner comme on le souhaite, donc de superposer vraiment.
