### ISSUE TITLE
[REDY][14.2.1] Etat d'un site non conforme

### ISSUE THREAD

**Issue by WIToliv** [witsa/synapps#457]
Hello, 
Est il possible qu'un reflet d'un site modbus affiche l'état : Connecté / Déconnecté et non True /False
![image](https://user-images.githubusercontent.com/101122670/161965292-e362cce1-7096-4e26-89f3-e1c43c338db3.png)
![image](https://user-images.githubusercontent.com/101122670/161965465-2db8f97d-dbcd-406f-8847-121549a0935c.png)

**Comment by manufitoussiwit** [comment]
Effectivement, l'état du reflet état devrait plutôt être `Connecté` ou `Déconnecté`. C'est une correction qui devrait être faite du coté du REDY. Je transmet pour faire un mantis

**Comment by manufitoussiwit** [comment]
On a essayé de reproduire en `14.2.1` sans succès. Peut-être utilises tu une version antérieure ?

**Comment by WIToliv** [comment]
je viens de le refaire et la ca passe en détails de reflet, bizarre.
J'avais le même truc sur la liste de reflet, il me mettait false et la aujourd'hui il me met bien déconnecté. est ce le fait d'avoir redémarrer Studio ce matin?!

**Comment by WIToliv** [comment]
effectivement aujourd'hui après une nouvelle ouverture de studio cela s'affiche correctement, bizarre.

Sinon j'ai fait une liste de reflet hier avec un site Mbus et la ca me met false
![image](https://user-images.githubusercontent.com/101122670/162160754-5fa51f70-9da6-4236-b9dc-0db2e1bc63bc.png)

**Comment by manufitoussiwit** [comment]
C'était le reflet qui était de type Site qui n'est pas supporté pour l'instant par Synapps.
