### ISSUE TITLE
[STUDIO][1.1.0-beta] Liste d'états - filtre par ensemble

### ISSUE THREAD

**Issue by WIToliv** [witsa/synapps#458]
Hello, 
Problème de rafraichissement. Lorsque l'on crée un ensemble dans le REDY, il n'apparait pas dans la liste des ensembles dans l'acteur "liste d'état". Y a t'il un temps de rafraichissement ?
Même en supprimant et recréant un acteur on le voit pas.
Idem en fermant la scène et en l'ouvrant à nouveau.

![image](https://user-images.githubusercontent.com/101122670/161981921-b464361c-035d-4f51-ba67-82f5b1221171.png)
![image](https://user-images.githubusercontent.com/101122670/161981965-a46c91e6-0fbc-4658-aa23-9a4d13c8ed59.png)

**Comment by manufitoussiwit** [comment]
Bien vu! En attendant mieux, il faut changer d'hôte si on en a plusieurs, ou alors carrément relancer l'application : Menu *Aide>Recharger l'application* (Raccourci clavier `Ctrl+Alt+R`). Attention a bien sauvegarder avant.
