### ISSUE TITLE
[RUNTIME][2.3.0] Bug Edge

### ISSUE THREAD

**Issue by WIToliv** [witsa/synapps#460]
Hello, 
j'ai fait une boite de saisie et je saisie un nombre (une consigne).
Sur edge n'apparaît pas les flèches pour la modifications de la valeur alors que sur chrome si.
Un problème de compatibilité sans doute.

**Comment by manufitoussiwit** [comment]
Je n'arrive pas à reproduire. 
Du moment que l'option "Nombre" est choisie pour l'acteur *boite de saisie*, les flèches s'affichent dans les deux navigateurs.

**Comment by manufitoussiwit** [comment]
Si ce n'est pas reproduit, je ferme ;-)
