### ISSUE TITLE
[STUDIO][1.1.0] Instabilité générale

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#461]
Comparé à la Beta, la V1.1.0 me parait moins stable.
Le modele 3 colonnes ne fonctionne à priori pas, erreur de rendu de la scene comme si je n'etais pas connecté alors que je suis bien authentifié et connecté dans les hotes.

Message erreur sur mon projet LSSM
![image](https://user-images.githubusercontent.com/33632664/162389460-390e1ada-0b2b-4f85-a3a1-ece1b4f6f8ce.png)

Parfois je ne peux plus déplacer les acteurs à la souris.

Je downgrade en beta3 pour le moment.

**Comment by WITNicolas** [comment]
Je fais des vrais tests pour te confirmer tout cela !

**Comment by manufitoussiwit** [comment]
Le message d'erreur apparait effectivement lorqu'on recharge l'application studio avec un projet ouvert. Heureusement, c'est une erreur interne sans conséquence qui ne devrait pas apparaitre comme ça. Je prépare une révision pour cette aprem.

**Comment by manufitoussiwit** [comment]
Pour le reste, je n'arrive pas à reproduire.

**Comment by manufitoussiwit** [comment]
Une révision de la version 1.1.0 arrive dans quelques minutes.

**Comment by manufitoussiwit** [comment]
La révision de 14:00 corrige tout ça.
