### ISSUE TITLE
[STUDIO] Commentaires

### ISSUE THREAD

**Issue by JYK-WIT** [witsa/synapps#465]
Bonjour,
serait il possible dans les prochaines versions de commenter un peu les lignes de programmations dans les évènements, pour les modèles qui sont fournis? Par exemple pour un OnClick d'un bouton de sous-menu

const toggle = actor => {
  actor.additionals.isOpen = !actor.additionals.isOpen;

  const subMenu = context.getActor(actor.additionals.subMenuKey);
  if (!subMenu) return;
  subMenu.properties.maxHeight = actor.additionals.isOpen ? `${subMenu.childUis.size * 4}em` : '0em';
   actor.actor.querySelector('.indicator').style.transform = `rotate(${actor.additionals.isOpen ? 45 : 0}deg)`;
}

if (!this.additionals.isOpen) {
  (this.stage.allActors || this.stage.actorsRegister.records)
    .filter(actor => actor.additionals.isMenuPanel && actor.additionals.isOpen && actor !== this)
    .forEach(toggle);
}

toggle(this);

Merci

**Comment by Raphwit** [comment]
On prend note pour les fonctionnalités un peu avancées comme celles-ci !
