### ISSUE TITLE
Affichage en fenêtre indépendante impossible avec Edge

### ISSUE THREAD

**Issue by manufitoussi** [witsa/synapps#47]
On ne peut pas afficher ni le runtime ni le maker en onglet/fenêtre indépendante de `Edge`.
On reste sur la page de login avec l'erreur suivante :
![image](https://user-images.githubusercontent.com/2018558/34931745-8f3062ca-f9d0-11e7-97df-5f27da8055d9.png)

On a accès en revanche au runtime dans l'UI du REDY.

**Comment by manufitoussiwit** [comment]
Apres enquête il apparaît que c'est un [bug de Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8438041/)

**Comment by ericvoignier** [comment]
Déployé 1.3.3
