### ISSUE TITLE
Ergonomie des sources de données

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#48]
La création et la modification des sources de données ne permet pas d'être suffisamment productif: pas de copier/coller, pas de recherche, etc. Revoir l'UX

De même la liaison des acteurs aux sources est également peu intuitive et ne permet pas de saisir directement le chemin de liaison vers le WOS. Revoir également la sélection de source de donnée, chemin relatif, contexte, etc trop complexe

**Comment by ericvoignier** [comment]
Review a organiser avec ops MB, @WITNicolas, JFG

**Comment by manufitoussiwit** [comment]
Dans la version 1.1.0 de Studio
