### ISSUE TITLE
Problème de connexion et de visualisation

### ISSUE THREAD

**Issue by JYK-WIT** [witsa/synapps#494]
Bonjour,
je n'arrive pas à visualiser ma synapps en tant qu'utilisateur autre que celui qui à réalisé cette synapps.
Sur studio, j'ai maintenant une erreur "UnknownError" avec le même identifiant et aussi avec les id par défaut.
Je suis oblige de créer un nouvel utilisateur dans studio et le redy pour pouvoir continuer.
Merci
JYK

**Comment by manufitoussiwit** [comment]
Salut! Bizarre comme expérience. 
Difficile d'interpréter ce qui s'est passé.
Est ce qu'en ajoutant un nouvel hôte avec les identifiants d'origine ça remarche ?

**Comment by manufitoussiwit** [comment]
Lié à l'issue #499
