### ISSUE TITLE
Propriétés additionnelles : Problèmes de rendu

### ISSUE THREAD

**Issue by manufitoussi** [witsa/synapps#50]
Les boutons dans la fenêtre de gestion des propriétés additionnelles/paramètres de scène ne sont pas bien disposés au 1er affichage.

![image](https://user-images.githubusercontent.com/2018558/34951464-b815af56-fa16-11e7-8011-555ff0ef29c9.png)

**Comment by manufitoussiwit** [comment]
Le pb n'est présent que sur chrome canary
