### ISSUE TITLE
[DOC] Composite

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#514]
> Lien de la page : `concepts/composite.md`.
La composite planning hebdomadaire à une réaction curieuse malgré le lien avec la ressource planning
J'ai l'impression qu'il y a un soucis avec les sources de données qui ne sont pas correctement prises en compte

![image](https://user-images.githubusercontent.com/33632664/177158422-58110a9c-7867-4a6c-8954-051b5a5cef96.png)

**Comment by manufitoussiwit** [comment]
oula c'est tout cassé sur ta capture :-) Comment en es tu arrivé là ?

**Comment by WITNicolas** [comment]
Copier-coller direct du composite de la DOC vers STUDIO :-)

**Comment by WITNicolas** [comment]
Le composite de la discussion fonctionne par contre
https://github.com/witsa/synapps/discussions/471

**Comment by manufitoussiwit** [comment]
Corrigé
