### ISSUE TITLE
[STUDIO] Probléme Affichage Explorateur WOS 

### ISSUE THREAD

**Issue by DavMar05** [witsa/synapps#515]
![image](https://user-images.githubusercontent.com/108288565/177558257-fd3ef541-be9d-4757-ad95-a6346e523c1f.png)

Bonjour,

En utilisant Studio, je rencontre des problèmes  d 'accès de variable. Version d'automate V14.2.2 . Version Studio V1.1.2.

J'ai juste supprimé une extension dans l'extenbus et réglé type de conversion de sonde sur des extensions 4 SVA.
Du coup, je n'ai plus accès au variable avant je n'avais aucun problème.

cordialement

**Comment by WITNicolas** [comment]
Dans l'explorateur, il y avait des variables WOS qui avaient des valeurs énormes.
170000000000000000000000000000.
En enlevant ces valeurs, l'explorateur est de nouveau apparu, il y a donc a priori un dépassement de quelquechose qui plante l'explorateur
