### ISSUE TITLE
[DOC] Composite

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#528]
> Lien de la page : `concepts/composite.md`.

Pour le composite Icone Defaut qui clignote il y a quelquechose qui ne fonctionne pas quand on intégre le composite dans les acteurs remarquables.
Dans le contenu de l'acteur Html Icone, il y a normalement : 
`<i class="icon-{{icon}}"></i>`

Alors que dans les composites remarquables, il y a : 
`<i class="icon-"></i>`
Le joker a disparu

**Comment by manufitoussiwit** [comment]
Normalement c'est corrigé
