### ISSUE TITLE
Publier dans un Redy PC

### ISSUE THREAD

**Issue by edejean** [witsa/synapps#538]
Bonjour,
Tout est dans le titre.
Peux-t-on publier un Synapps dans un Redy PC ?
Quand je tente l'opération, j'ai le message d'ereur suivant : 

![2022-10-04 09_12_13-Window](https://user-images.githubusercontent.com/105919791/193757606-d198de9c-4580-4758-a839-e32431600abd.png)

On a du sans doute en parler pendant la formation, mais j'ai zappé...
Cdt
Eric

**Comment by WITNicolas** [comment]
Bonjour,
Est ce que vous avez bien l'option INTRAVISION qui est activée sur votre REDY PC ?

**Comment by edejean** [comment]
Voici le Redy PC que je lance

![image](https://user-images.githubusercontent.com/105919791/193796609-22cea592-99f2-4784-aa79-3a7bdabb4460.png)

**Comment by WITNicolas** [comment]
Ok, l'intravision est bien activée

Eventuellement le niveau d'accés ?
ou bien essayer de recharger STUDIO --> AIDE / RECHARGER APPLICATION

Je laisserais le soin au dév' de vous répondre plus précisement si ça bloque encore.
Il saura exactement ce que signifie le message d'erreur.

**Comment by manufitoussiwit** [comment]
Normalement, lorsque l'intravision ou que le niveau utilisateur est insuffisant, Studio prévient avec un beau message qu'il n'est pas possible de publier un synapp. 
Là, le REDY PC semble répondre de manière inattendue que l'utilisateur n'a pas le droit de créer la synapp.

Est-ce que dans l'exporateur, dans le dossier :easy, le dossier SynApps ressemble à ça ?

![image](https://user-images.githubusercontent.com/35595723/193828830-9f81d029-75c8-4197-a284-4cbe8ca67910.png)

**Comment by edejean** [comment]
Exactement à cela excepté pour le nombre d'enfants...
![image](https://user-images.githubusercontent.com/105919791/193841981-3ecf490e-3748-421e-8410-6f2b347a1236.png)
Le message d'erreur apparait pratiquement à la fin de la publication.

**Comment by manufitoussiwit** [comment]
Ok, alors je soupçonnerais peut être la présence d'une scène avec une clé dupliquée ou un caractère bizarre non accepté par le REDY. Normalement, Studio empêche ça.

**Comment by edejean** [comment]
Bonjour,
Je viens de tester avec un nouveau projet créé depuis un template d'une base identique sur une redyPC et cela fonctionne et c'est justement ce projet en question sur lequel j'avais besoin de publier SynApps sur un redyPC.
Donc, on va pouvoir clore le sujet et quand j'aurai un moment, je jetterai un coup d'oeil sur l'autre projet qui a pu être publié sur l'automate sans problème d'ailleurs.

**Comment by manufitoussiwit** [comment]
Même pb que #549
