### ISSUE TITLE
Personnalisation couleur de fond bar acteur curseur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#54]
![image](https://user-images.githubusercontent.com/33632664/35065290-1bf2c1e6-fbcd-11e7-832b-97451e14afa9.png)

Pouvoir personnaliser la couleur de la barre des 2 cotés. Pour une consigne de température, ça peut être sympa d'avoir du rouge d'un coté et du bleu de l'autre.
Je n'ai pas d'exemple pour d'autres applications à cet instant....

**Comment by ericvoignier** [comment]
OK, en attente déploiement 1.3.3

**Comment by ericvoignier** [comment]
Déployé 1.3.3
