### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MauroColo** [witsa/synapps#540]
Pandans la modif de l?URL d'un IFrame:

![image](https://user-images.githubusercontent.com/109213637/195558441-a5b98d4a-9fc8-41ab-89b8-b61201bdec8a.png)

**Comment by manufitoussiwit** [comment]
Vu en directe, c'est le  PC qui est à l'origine du crash.

**Note :** Ce message, qui arrive dans des situations limites, mériterait d'être un peu plus digeste :-)
