### ISSUE TITLE
[STUDIO] Bug liaison sur Acteur Source de Ressource

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#541]
Acteur Source de Ressource dont le chemin est liaisonné à une additionnelle de scene.
![image](https://user-images.githubusercontent.com/33632664/195813041-befa1735-48f4-4856-a337-bdae27163db5.png)

Un acteur (peu importe) qui prend sa source vers l'acteur Source de Ressource.
![image](https://user-images.githubusercontent.com/33632664/195813211-333c6a4f-d385-46e2-8f49-0518fe0964a1.png)

La source se liaisonne sur la valeur initiale et pas celle du Chemin.
Mon chemin venant de l'aditionnelle est 
![image](https://user-images.githubusercontent.com/33632664/195813470-0e00a3af-c89f-4576-8c9f-d8a78e232bce.png)
Du coup les chemins relatifs ne sont pas bons
![image](https://user-images.githubusercontent.com/33632664/195813870-ae69df10-698e-4368-b114-e3ca21c8e6dd.png)

**Comment by manufitoussiwit** [comment]
Effectivement, les propositions sont faites en utilisant les valeurs initiales et sans résoudre les liaisons. Ils font d'ailleurs les utiliser dans ce sens-là c'est à dire comme des valeurs de travail ou de construction.

**Comment by WITNicolas** [comment]
Ok donc ça veut dire que dans les bonnes pratiques, la Valeur Initiale est trés importante pour avoir des liens cohérents, qui seront par la suite alimentés par les additionelles de scene, etc..etc...
