### ISSUE TITLE
Supprimer le cadre blanc sur bouton nav

### ISSUE THREAD

**Issue by edejean** [witsa/synapps#546]
Bonjour,
Comment supprimer le cadre blanc sur les boutons nav ?

![image](https://user-images.githubusercontent.com/105919791/197778138-b06043d8-751b-42ba-a0c1-880e41ad5733.png)

**Comment by Raphwit** [comment]
Bonjour, 
Pour supprimer un cadre d'un élément c'est dans la section "Bordures" -> "Épaisseur de la bordure" -> "0px"

**Comment by edejean** [comment]
Bien vu !!!
Vu que je n'avais pas touché au style de bordure et qu'il n'y a pas de style par defaut, je ne pensais pas que cette valeur de 1 px influençait l'acteur "Bouton de navigation"
Merci en tout cas ;)
