### ISSUE TITLE
Problème de navigation avec l'acteur écran

### ISSUE THREAD

**Issue by Arnaudvitale** [witsa/synapps#548]
### Explication du problème

> On est sur une scène **principale** contenant un acteur écran qui redirige vers quelques autres scènes (pour contextualiser)

Dans mon cas, après utilisation des scènes provenant de l'acteur écran, elles redirigent vers le **stack-root** de la scène **principale**
![image](https://user-images.githubusercontent.com/91725889/201682989-0a4fca08-e4e1-4fa4-b7b0-a2ea895148e0.png)
(afin de rediriger sur la bonne scène car il y a des conditions de navigation sur le **stack-root** de la scène **principale**. A noter que l'acteur écran contient une condition *getActor* qui redirige ver le **stack-root**).
![image](https://user-images.githubusercontent.com/91725889/201682291-d3512ac9-2b6e-42d5-a4c8-2f5065de93da.png)
Lorsque l'on est amené à changer le nom de la scène **principale** pour X ou Y raison (souvent pour avoir des noms plus explicites) et que l'on change aussi dans le code et les autres acteurs liés à celui-ci le nom ou la clé pour que ça corresponde, une erreur persiste : "*scène non trouvée*" dans l'acteur écran. 
![image](https://user-images.githubusercontent.com/91725889/201682071-63986220-caef-44fb-8a40-1df5ab7e7c2e.png)
Pourquoi "*scène non trouvée*", c'est tout simplement car sur la *clé de la scène à afficher* le nom ne change pas et continue de chercher la scène avec son ancien nom (j'espère que c'est clair parce que c'était assez compliqué à expliquer). Le problème s'est réglé en supprimant manuellement cette clé.
![scre](https://user-images.githubusercontent.com/91725889/201681686-8553bc16-bcae-4347-a918-8862b0197f92.PNG)

**Comment by manufitoussiwit** [comment]
Si on change la clé d'une scène, on doit répercuter ce changement à la main partout où elle a été utilisée (dans les scripts, dans les propriétés, ...). En effet, c'est l'identifiant unique de la scène.
En revanche, le nom de la scène peut être changer librement, sans aucune conséquence.
