### ISSUE TITLE
Erreur de transfert

### ISSUE THREAD

**Issue by JYK-WIT** [witsa/synapps#549]
Bonjour, 
j'ai cette erreur lors d'un transfert vers un REDY
![image](https://user-images.githubusercontent.com/100723121/202001442-a465e6b1-2481-48d4-b373-cd6eab0ec81d.png)
 et j'ai déjà la synapps sur le REDY

**Comment by manufitoussiwit** [comment]
Salut! J'ai plusieurs questions : 
- passes tu par un proxy ?
- l'utilisateur est-il au moins installateur ?
- dans l'explorateur, à l'adresse :easy/synapps/ peux tu envoyer une capture de qu'il y a ?

**Comment by JYK-WIT** [comment]
- Non
- Administrateur
En plus cela supprime le synapps présent sur le REDY.
Je corrige en supprimant la dernière scène créé
Je t'envoi tout sur teams

**Comment by manufitoussiwit** [comment]
La clé de scène est **c**taConf. Une autre scène s'appelle **C**taConf. 
Dans studio, ces deux clés sont différentes. Mais lorsqu'on publie, ces clés sont ensuite traduites en label dans le REDY et lui, il n'est pas sensible à la casse. 
> Ce qui produit l'erreur lors de l'étape de publication de la seconde scène avec presque la même clé.

Pour résoudre le pb, remettre la scène dans le projet et changer sa clé.

## Remarque
Dans la version `1.1.4` de Studio, la comparaison des clés de scène et composite ne distinguera plus la casse.

**Comment by manufitoussiwit** [comment]
Il peut y avoir le même problème avec les clés des Images. C'est réglé dans version `1.1.5`
