### ISSUE TITLE
Manque de details dans l'acteur Journal 

### ISSUE THREAD

**Issue by maurocolognesi** [witsa/synapps#55]
Les infos disponible dans l'acteur Journal sont beaucoup moins riches des infos présents dans le journal du easy/redy/easyPilot.

![list champs journal](https://user-images.githubusercontent.com/35558533/35087750-9c2b69f8-fc31-11e7-8505-802b21e5dbd3.JPG)

**Comment by ericvoignier** [comment]
OK, quelles sont les infos manquantes qui sont pertinentes à ajouter ?

**Comment by maurocolognesi** [comment]
Pour ne pas se tromper je dirais tous les champs que tu vois dans l'images

**Comment by ericvoignier** [comment]
Certains champs ne présentent pas d’intérêt dans SynApps. 
Par exemple: liens vers synoptique.
@WITNicolas vois tu des champs complémentaires qui seraient pertinents dans le journal SynApps du Redy ?

**Comment by WITNicolas** [comment]
Quelque chose qui n'existe pas dans le journal du REDY comme les occurrences d'une alarme.

**Comment by ericvoignier** [comment]
Le nombre d’occurrence est-il disponible dans la "ressource" journal du REDY. Cette info est nécessaire pour être rendue correctement dans SynApps. Il ne me semble pas mais nous validons cela.

**Comment by WITNicolas** [comment]
Non effectivement ce n'est pas une info disponible.

**Comment by WITNicolas** [comment]
Concernant les éléments du journal (ce n'est que ma vision)

**Tout le temps et Vital**
Date d'Origine
Libellé
Etat

**Assez souvent**
Site
Supprimer

**De temps en temps**
Diffusion
Consigne
Acquitté part

**Rarement**
Pièce Jointe (pas d’intérêt dans Synapps)
Informations
Lien vers Synoptique (pas d’intérêt dans Synapps)

**Jamais**
ID
Date d'enregistrement
URL
Type
Equipement
Zone 
Classe
Lien vers site (pas d’intérêt dans Synapps)
Numéro de la ressource

**Comment by MaxiWit** [comment]
Assez d'accord avec Nico pour la liste, pour moi il y a 3 gros manques dans le journal actuel:
1) Avoir un vrai acquit, voir rapidement qui a acquitté et si possible pourquoi. En bonus: avoir un impact sur l'astreinte, mais ça touche le soft hors synapps
2) Les notes, pourrait être vu dans des bulles-infos pour ne pas encombrer
3) Les occurrences ont une vrais utilité, peut-être que ça serait l'occasion de l'intégrer dans le soft de nos produits...

**Comment by ericvoignier** [comment]
OK vous l'avez souligné, nous ne pouvons restituer dans _Synapps_ que des éléments du journal disponible dans le REDY, concernant les _occurrences_ et _impacte sur astreinte_, nous sommes hors périmètre et vous propose d'ouvrir ce sujet sur Gladys.
Concernant le reste, nous pouvons enrichir le journal avec un certain nombre d'éléments, qui vont être précisés. A noter que pour les acquittements des _en-cours_, nous avons déja l'info de qui a acquitté. Nous allons vérifier que la note (le pourquoi?) est également disponible via l'API journal du REDY

**Comment by WITNicolas** [comment]
Pour la note effectivement ça peut être intéressant dans le sens où on peut l'utiliser cela pour afficher une conduite à tenir sur une alarme en affichant la note dans une modale par exemple.
En tout cas ça ouvre des perspective. Les synoptiques actuels ne permettent pas de déclencher l'ouverture d'un popup .. ce que peut faire SYNAPPS... donc intéressant.

**Comment by ericvoignier** [comment]
_Note_ et _Description_ sont définies au niveau de la ressource. Ces 2 infos seront donc affichées au survol de la ressource
