### ISSUE TITLE
Copie d'acteur texte avec lien vers source de donnée

### ISSUE THREAD

**Issue by maurocolognesi** [witsa/synapps#56]
Acteur Texte - Specifique - Contenu >>> Erreur Oups! Désolé, quelque chose ne s'est pas passée comme prévu.
L'acteur créé par duplication d'un autre Texte avec lien vers source de données

**Comment by ericvoignier** [comment]
Impossible à reproduire. Peux tu exporter le projet dans

> \\wit-file\Echange\SynApps\Issues\56

**Comment by ericvoignier** [comment]
Problème fixé dans versions précédente
