### ISSUE TITLE
Edge n'affiche pas les SynApps

### ISSUE THREAD

**Issue by maurocolognesi** [witsa/synapps#57]
La page SynApps affichè par Edge est vide alors que une synapp est bien presente et affichè par Chrome.

![image](https://user-images.githubusercontent.com/35558533/35141778-75756522-fcfc-11e7-9544-aaf23825adb5.png)

**Comment by manufitoussi** [comment]
Merci Mauro.
Je l'avais remarqué également.

**Comment by manufitoussiwit** [comment]
Apres enquête, il apparaît qu'une option dans Edge doit être activée pour qu'il fonctionne correctement avec les redy pc en local.

Dans la barre d'adresse, il faut taper : `about:flags`
ensuite autoriser le bouclage localhost 

![image](https://user-images.githubusercontent.com/35595723/35520980-dbfaee74-0518-11e8-82fd-5d56b582fc19.png)
