### ISSUE TITLE
Les données de certains blocs fonction ne s'affichent pas dans une scène

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#579]
Bonjour,

Les données .Out des blocs fonction NIL et MOINS ne s'affiche pas alors que celle provenant des .Shot des fonctions DELTA s'affiche. 

Version Synapps Studio v1.1.5
Automate REDY (où les données sont) v14.4.0 avec distribution K7Linux v2.5.2

![Synapps1](https://user-images.githubusercontent.com/50445069/228808213-5f2e88b8-ad3e-405a-acd5-bb782aefb6cd.png)
![Synapps2](https://user-images.githubusercontent.com/50445069/228808197-d3dfdcda-1faf-49b9-9754-977aff4db513.png)
![Synapps3](https://user-images.githubusercontent.com/50445069/228808200-c2fda847-8399-42c3-bb87-3d4a4b6341de.png)
![Synapps4](https://user-images.githubusercontent.com/50445069/228808206-2bbb997e-dae4-40ac-b57c-09cb748999a9.png)
![Synapps5](https://user-images.githubusercontent.com/50445069/228808208-63d9e45c-4d9c-4442-bc06-0e225513b413.png)
![Synapps6](https://user-images.githubusercontent.com/50445069/228808210-0e6ecbef-b583-44c5-95a0-8cde42fc2bc6.png)

**Comment by manufitoussiwit** [comment]
Salut! J'ai essayé de reproduire et je ne vois pas de pb : 

![image](https://user-images.githubusercontent.com/35595723/228849378-f9f6dd30-5804-4a1b-ad06-18a236911544.png)


J'ai lié comme toi au `In` d'une fonction Nil et au `Out` d'une fonction Moins et je ne vois pas de pb.

![image](https://user-images.githubusercontent.com/35595723/228850470-989dc2e2-52fb-4bd4-9024-02c7c49f358f.png)


![image](https://user-images.githubusercontent.com/35595723/228850671-deb64c66-291d-4095-8415-cac436688dd1.png)


_______________
>
> Au passage, on peut aussi se lier directement à la donnée de l'acteur relatif  : 
> 
> ![image](https://user-images.githubusercontent.com/35595723/228850889-31c4268f-de34-4875-b980-ce24aa0a3b37.png)
> 
> ça marche pareil et ça fait moins d'objets donc on a une petite optimisation ;-)

**Comment by JeremieDENAEGEL** [comment]
Problème résolu avec manufitoussiwit (Merci ;) )
Le problème venait apparemment de l'autorefresh du composite.
