### ISSUE TITLE
Problème publication Synapp

### ISSUE THREAD

**Issue by Eltis74** [witsa/synapps#589]
Bonjour,

J'ai un petit souci de publication de ma synapps sur mon Redy.
J'ai synapps studio en 1.1.5 et mon Redy en 14.4.0 : 
- Je crée un nouveau projet en mode tablette et bureau.
- Je me connecte à mon Redy et publie ma synapps (jusque-là tout fonctionne, ma synapps est bien dans mon Redy).
- Je fais des modifications basiques de fond (couleur) de la scène "accueil" et rajoute du texte.
- Puis je republie ma synapps.
- Là ça ne fonctionne plus, le chargement de la publication reste bloqué à 41%, je ne peux plus me connecter à mon Redy, le Redy redémarre et je n'ai plus de synapps présente dans l'automate.

Pouvez-vous m'éclairer sur ce problème ?

Cordialement,

CONTAT Arthur - ELTIS Génie Electrique

**Comment by manufitoussiwit** [comment]
> 

Bonjour, est ce que le problème se répète si vous republier votre projet dans le REDY ?

**Comment by Eltis74** [comment]
C'est le projet de base lors de la création d'un nouveau projet.
J'ai juste fait des petite modification, mais rien d'extraordinaire.
Je l'ai deposé.

**Comment by manufitoussiwit** [comment]
> 

Merci, a première vue, les images sont beaucoup trop grosses pour le REDY ce qui le fait redémarrer je pense.

Aussi, le projet ne se charge pas correctement : il manque une partie de la scène 9. C'est la même chose pour vous ou c'est juste le transfère qui a été interrompu ?

**Comment by Eltis74** [comment]
Pourtant j'ai bien mis l'image dans la bibliothèque comme demandé.
Qu'entendez vous par la scène 9 ?
je n'ai que ca dans mon projet :
![image](https://github.com/witsa/synapps/assets/53903952/79e0fa2d-14ea-408d-82cb-6716e71c8eb9)

**Comment by Eltis74** [comment]
Très bien je vais tester de la réduire et voir si le problème viens de là.

**Comment by manufitoussiwit** [comment]
Content que le pb soit résolu. Il reste à jongler entre la taille et la qualité 🙂

**Comment by manufitoussiwit** [comment]
En général, j'utilise https://www.img2go.com/compress-image

![image](https://github.com/witsa/synapps/assets/35595723/e99a806a-b5d6-4143-ac7d-3904daf75fcf)

Par exemple pour l'image d'eltis, on peut passer de 12Mo à 2Mo sans perte de qualité, et encore moins en changeant un peu la taille ou la qualité.

**Comment by manufitoussiwit** [comment]
Ceci est dû à un pb dans l'API du REDY qui retourne un message mal formaté. L'erreur produit l'arrêt de la publication à l'étape de l'image concernée. C'est assez aléatoire comme problème. Il est plus fréquent avec les grosses images.
Heureusement 👍, depuis la version du REDY `14.5.0` en combinaison avec Studio `1.2.0`, cela ne peut plus arriver ! 
C'est grâce à l'accélération mise en œuvre dans ces deux versions [voir la note de version](https://witsa.github.io/synapps/synapps-studio-releases/notes/1.2.0#acc%C3%A9l%C3%A9ration-de-la-publication-de-synapp).
