### ISSUE TITLE
[ACTEUR] Liste de choix - Problème lecture pour rendu valeur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#603]
![image](https://github.com/witsa/synapps/assets/33632664/eb303b62-019f-4d25-8f80-78d3a160abe9)

Quand on est en lecture / écriture avec la liste de choix, la lecture ne suit pas la valeur du NOD relié.
En écriture, pas de soucis, l'action sur les puces agissent bien sur la liaison

**Comment by manufitoussiwit** [comment]
Je dirais que c'est un pb de type. La valeur du REDY doit surement être un numérique alors que la clé de l'option est une chaine.

Il faut du coup faire des transformations :

### pour `onReadTransform` : 

```js
return `${context.value}`;
```

Si y a écriture aussi : 

### pour `onWriteTransform` : 

```js
return parseFloat(context.value);
```

**Comment by WITNicolas** [comment]
Ok compris .... en fait ça revient souvent ce "soucis" de typage. C'est comme pour les Fonctions NIL, en entrée c'est une chaine, en sortie c'est typé comme un booleen true/false .... alors qu'il y a une valeur.
