### ISSUE TITLE
problème fermeture de modale

### ISSUE THREAD

**Issue by simhelio** [witsa/synapps#608]
Bonjour

J'ai un petit problème, quand je clique ailleurs ça me ferme la modale même avec l'option à l'arret.

bonne journée

 
![Capture d’écran 2023-07-05 143315](https://github.com/witsa/synapps/assets/128216403/b795818c-9e54-4efc-bdc7-6d674cbeb4eb)

**Comment by Raphwit** [comment]
Bonjour, est-ce possible de nous fournir la scène ou le composite ou ce comportement est observé ? merci

**Comment by simhelio** [comment]
pas de problème, mais je fais comment?

**Comment by Raphwit** [comment]
Vous pouvez copier la scène ou le composite depuis le menu contextuel : 
![image](https://github.com/witsa/synapps/assets/93767525/ba892cf7-f863-4c05-88e7-5171f94051eb)

Et coller directement ici

**Comment by simhelio** [comment]
SYNAPPS-STUDIO-SCENE|{"config":{"key":"deshydratation","name":"deshydratation"},"leadActor":{"type":"layout/stack","key":"stack1","children":[{"type":"layout/view-box","key":"view-box1","children":[{"type":"layout/canvas","key":"canvas1","properties":{"verticalAlignment":"expand","height":"980px","width":"1740px"},"children":[{"type":"display/image","key":"fondsyno","properties":{"borderWidth":"","width":"74%","top":"0px","left":"230px"},"bindings":{"properties.content":"picture@S_dshydratation","properties.backgroundColor":"color@vertwit"}},{"type":"input/button","key":"BP_centri1","properties":{"height":"40px","width":"40px","top":"182px","left":"1308px","backgroundRepeat":"round","borderColor":"rgba(2, 2, 2, 1)","borderWidth":"2px","borderRadius":"20%","boxShadow":"10px 5px 5px grey"},"bindings":{"properties.backgroundImage":"picture@Engrenage","properties.backgroundColor":"color@dark"}},{"type":"input/button","key":"BP_centri2","properties":{"height":"40px","width":"40px","top":"182px","left":"1261px","backgroundRepeat":"round","borderColor":"rgba(2, 2, 2, 1)","borderWidth":"2px","borderRadius":"20%","boxShadow":"10px 5px 5px grey"},"bindings":{"properties.backgroundImage":"picture@Engrenage","properties.backgroundColor":"color@dark"}},{"type":"input/button","key":"BP_para3","properties":{"height":"40px","width":"40px","top":"590px","left":"1460px","backgroundRepeat":"round","borderColor":"rgba(2, 2, 2, 1)","borderWidth":"2px","borderRadius":"20%","boxShadow":"10px 5px 5px grey"},"bindings":{"properties.backgroundImage":"picture@Engrenage","properties.backgroundColor":"color@dark"}},{"type":"display/text","key":"text1","properties":{"content":"Boues soutirées FE101","width":"100px","textAlign":"center","top":"158px","left":"646px"}},{"type":"display/text","key":"text2","properties":{"width":"100px","textAlign":"center","top":"196px","left":"646px","borderColor":"rgba(221, 0, 255, 1)","borderWidth":"2px","borderStyle":"solid","borderRadius":"10px","color":"rgba(45, 90, 255, 1)"},"bindings":{"properties.content":{"relativeTo":"global/resources","relativePath":"R00013.R00265.WORD000","fieldName":"state","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"display/image","key":"image2","properties":{"height":"50px","width":"50px","top":"584px","left":"1397px"},"bindings":{"properties.content":"picture@fan_arret_128"}},{"type":"display/text","key":"text5","properties":{"content":"Eaux potable","color":"rgba(5, 101, 0, 1)","borderColor":"rgba(200, 200, 200, 1)","borderWidth":"4px","borderStyle":"solid","borderRadius":"5px 15px","top":"500px","left":"750px","fontWeight":"bold","paddingRight":"6px","paddingLeft":"5px","fontStyle":"italic"},"bindings":{"properties.backgroundColor":"color@gray"}},{"type":"display/text","key":"text3","properties":{"content":"Vers la serre de séchage","color":"rgba(5, 101, 0, 1)","borderColor":"rgba(200, 200, 200, 1)","borderWidth":"4px","borderStyle":"solid","borderRadius":"5px 15px","top":"486px","left":"1213px","fontWeight":"bold","paddingRight":"6px","paddingLeft":"5px","fontStyle":"italic","width":"100px","textAlign":"center"},"bindings":{"properties.backgroundColor":"color@gray"}},{"type":"display/text","key":"text4","properties":{"content":"Venant du skid eaux industrielles","color":"rgba(5, 101, 0, 1)","borderColor":"rgba(200, 200, 200, 1)","borderWidth":"4px","borderStyle":"solid","borderRadius":"5px 15px","top":"425px","left":"1030px","fontWeight":"bold","paddingRight":"6px","paddingLeft":"5px","fontStyle":"italic","width":"130px","textAlign":"center"},"bindings":{"properties.backgroundColor":"color@gray"}},{"type":"display/text","key":"text6","properties":{"content":"Venant du skid eaux industrielles","color":"rgba(5, 101, 0, 1)","borderColor":"rgba(200, 200, 200, 1)","borderWidth":"4px","borderStyle":"solid","borderRadius":"5px 15px","top":"202px","left":"278px","fontWeight":"bold","paddingRight":"6px","paddingLeft":"5px","fontStyle":"italic","width":"130px","textAlign":"center"},"bindings":{"properties.backgroundColor":"color@gray"}},{"type":"display/text","key":"text7","properties":{"content":"Venant de la recirculation","color":"rgba(5, 101, 0, 1)","borderColor":"rgba(200, 200, 200, 1)","borderWidth":"4px","borderStyle":"solid","borderRadius":"5px 15px","top":"248px","left":"278px","fontWeight":"bold","paddingRight":"6px","paddingLeft":"5px","fontStyle":"italic","width":"130px","textAlign":"center"},"bindings":{"properties.backgroundColor":"color@gray"}},{"type":"display/text","key":"text10","properties":{"content":"Centrifugeuse","fontWeight":"bold","top":"390px","left":"860px","fontSize":"20px"},"bindings":{"properties.color":"color@info2"}},{"type":"display/text","key":"text8","properties":{"content":"Soutirage boues","fontWeight":"bold","top":"350px","left":"372px","fontSize":"20px"},"bindings":{"properties.color":"color@info2"}},{"type":"display/text","key":"text9","properties":{"content":"Préparation  polymères","fontWeight":"bold","top":"770px","left":"495px","fontSize":"20px"},"bindings":{"properties.color":"color@info2"}},{"type":"composite/marche_image","key":"marche_ventil","properties":{"height":"50px","width":"50px","top":"584px","left":"1397px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@fan_3752_128","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD013.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_vert","key":"marche_Pboue2","properties":{"height":"16px","width":"16px","top":"307px","left":"380px"},"bindings":{"properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD001.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_vert","key":"marche_Ppolymere","properties":{"height":"15px","width":"15px","top":"735px","left":"857px"},"bindings":{"properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD000.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_demarrage","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2bol","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out1","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_miseenvitesse","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2vitesse","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_stablisation","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2boletvis","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out3","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_polymere","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2polymres","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out4","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_departboue","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2boues","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out5","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_production","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2production","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out6","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_production2","properties":{"height":"115px","width":"16px","top":"364px","left":"1253px"},"bindings":{"properties.backgroundImage":"picture@boue1","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out6","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_vidange","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2lavage","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out7","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_lavage","properties":{"height":"146px","width":"576px","top":"241px","left":"772px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@centri2lavage","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.FNCT.F0001.Out8","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_vert","key":"marche_bol","properties":{"height":"25px","width":"25px","top":"302px","left":"1393px"},"bindings":{"properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD005.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_vert","key":"marche_vis","properties":{"height":"20px","width":"20px","top":"306px","left":"1289px"},"bindings":{"properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD006.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_Ppolymer","properties":{"height":"12px","width":"44px","top":"736px","left":"891px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@seepex_anim_polymer","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD000.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/marche_image","key":"marche_PBoues","properties":{"height":"11px","width":"90px","top":"311px","left":"445px","backgroundRepeat":"round"},"bindings":{"properties.backgroundImage":"picture@ecoule_boue_horizD","properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00307.WORD001.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"input/radio-list","key":"cde_centri","properties":{"value":"0","options":"[\n  {\n    \"value\": \"0\",\n    \"text\": \"arret\"\n  },\n  {\n    \"value\": \"1\",\n    \"text\": \"production\"\n  },\n  {\n    \"value\": \"2\",\n    \"text\": \"horloge\"\n  },\n  {\n    \"value\": \"3\",\n    \"text\": \"essai\"\n  }\n]","top":"213px","left":"816px","isInline":true,"borderWidth":"3px","borderStyle":"solid","borderRadius":"10px","height":"25px","width":"338px","textAlign":"center"},"bindings":{"properties.value":{"canWrite":true,"relativeTo":"global/resources","relativePath":"R00013.R00222.WORD000.InLink","fieldName":"value","dataReadMode":"always","writeOnChange":true,"source":"redy/wos-relative-variable"},"properties.borderColor":"color@cyan"},"events":{"properties/value/binding/onReadTransform":["return `${context.value}`;"],"properties/value/binding/onWriteTransform":["return parseFloat(context.value);"]}},{"type":"display/text","key":"info_centri","properties":{"content":"Text","width":"338px","top":"190px","left":"816px","textAlign":"center","borderStyle":"solid","borderRadius":"10px","borderWidth":"3px","fontWeight":"bold","height":"25px"},"bindings":{"properties.content":{"relativeTo":"global/resources","relativePath":"R00013.R00214.WORD000.Output","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"},"properties.borderColor":"color@cyan","properties.color":"color@vitesserelative"},"events":{"properties/content/binding/onReadTransform":[" var level = context.value;","  switch(level) {","      case 8:","          return \"Lavage\";","          break ;","      case 7:","          return \"Vidange\";","          break ;","      case 6:","          return \"Production\";","          break ;","      case 5:","          return \"Départ boues\";","          break ;","      case 4:","          return \"Départ polymère\";","          break ;","      case 3:","          return \"Stabilisation vitesse\";","          break ;","      case 2:","          return \"Mise en vitesse\";","          break;","      case 1:","          return \"Démarrage\";","          break;","      case 0:","          return \"Arret\";","          break;","      default:","          return \"?\";","          break;","  }"]}},{"type":"display/text","key":"couple","properties":{"width":"100px","textAlign":"center","top":"213px","left":"1154px","borderColor":"rgba(221, 0, 255, 1)","borderWidth":"2px","borderStyle":"solid","borderRadius":"10px","color":"rgba(45, 90, 255, 1)","height":"25px","lineHeight":"25px"},"bindings":{"properties.content":{"relativeTo":"global/resources","relativePath":"R00013.R00265.WORD003","fieldName":"state","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"display/text","key":"Vitesse_vis","properties":{"width":"100px","textAlign":"center","top":"189px","left":"1154px","borderColor":"rgba(221, 0, 255, 1)","borderWidth":"2px","borderStyle":"solid","borderRadius":"10px","color":"rgba(45, 90, 255, 1)","height":"25px","lineHeight":"25px"},"bindings":{"properties.content":{"relativeTo":"global/resources","relativePath":"R00013.R00265.WORD002","fieldName":"state","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"display/text","key":"Vitesse_bole","properties":{"width":"100px","textAlign":"center","top":"165px","left":"1154px","borderColor":"rgba(221, 0, 255, 1)","borderWidth":"2px","borderStyle":"solid","borderRadius":"10px","color":"rgba(45, 90, 255, 1)","height":"25px","lineHeight":"25px"},"bindings":{"properties.content":{"relativeTo":"global/resources","relativePath":"R00013.R00265.WORD001","fieldName":"state","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/defClignotant","key":"bas_polymere","properties":{"height":"20px","width":"20px","textAlign":"center","top":"542px","left":"677px","fontSize":"20px","lineHeight":"20px","iconOK":"bowling","etatDefaut":false},"bindings":{"properties.etatDefaut":{"relativeTo":"global/resources","relativePath":"R00013.R00220.WORD000.Output","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/composite12","key":"composite121","properties":{"height":"17px","width":"17px","top":"518px","left":"551px"},"bindings":{"properties.visible":{"relativeTo":"global/resources","relativePath":"R00013.R00215.WORD000.Output","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat2pos-texte2","properties":{"height":"17px","width":"40px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"816px","prop1":"Lundi"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B6","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat1","properties":{"height":"17px","width":"40px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"857px","prop1":"Mardi"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B5","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat2","properties":{"height":"17px","width":"52px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"898px","prop1":"Mercredi"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B4","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat3","properties":{"height":"17px","width":"41px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"951px","prop1":"Jeudi"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B3","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat4","properties":{"height":"17px","width":"51px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"993px","prop1":"Vendredi"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B2","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat5","properties":{"height":"17px","width":"49px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"1045px","prop1":"Samedi"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B1","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}},{"type":"composite/Etat2pos-texte","key":"Etat6","properties":{"height":"17px","width":"57px","color":"rgba(1, 1, 1, 1)","borderRadius":"10px","top":"169px","left":"1095px","prop1":"Dimanche"},"bindings":{"properties.propOn":{"relativeTo":"global/resources","relativePath":"R00013.R00224.WORD004.FNCT.F0001.B0","fieldName":"value","dataReadMode":"always","source":"redy/wos-relative-variable"}}}]}],"properties":{"verticalAlignment":"expand","horizontalAlignment":"expand"}},{"type":"layout/modal","key":"modal-on-click1","properties":{"height":"50vh","width":"39vw","clickOutsideToClose":false},"additionalDefs":{"showTrigger":{"type":"actor","label":"Affichage","helperTxt":"Acteur qui déclenche l'affichage."},"hideTrigger":{"type":"actor","label":"Fermeture","helperTxt":"Acteur qui déclenche la fermeture."}},"additionals":{"showTrigger":"BP_centri1","hideTrigger":"nav-synoddeshydra"},"children":[{"type":"layout/canvas","key":"canvas3","properties":{"verticalAlignment":"expand"},"children":[{"type":"display/screen","key":"screen1","properties":{"verticalAlignment":"expand","sceneKey":"tab_centri2","top":"0px","bottom":"0px","right":"0px","left":"0px"}},{"type":"input/nav-button","key":"nav-synoddeshydra","properties":{"content":"\n","height":"37px","width":"37px","paddingTop":"1px","paddingBottom":"1px","paddingRight":"1px","paddingLeft":"1px","horizontalAlignment":"middle","backgroundRepeat":"no-repeat","borderWidth":"","backgroundPosition":"center","displaySceneKey":"deshydratation","top":"0px","right":"0px"},"additionalDefs":{"prop1":{"type":"scene"}},"bindings":{"properties.backgroundImage":"picture@Exit"}}]}],"events":{"onPostInit":["const showTrigger = context.getActor(this.additionals.showTrigger);","","","if (showTrigger) {","  const originalOnClickFx = showTrigger.events.onClick ? showTrigger.events.onClick.fx : null;","  if (originalOnClickFx) {","    showTrigger.removeEvent('onClick');","  }","","  showTrigger.createEvent('onClick', (ctx) => {","    this.properties.isShown = true;","    if (originalOnClickFx) {","      originalOnClickFx(ctx);","    }","  });","}","","const hideTrigger = context.getActor(this.additionals.hideTrigger);","","if (hideTrigger) {","  const originalOnClickFx = hideTrigger.events.onClick ? hideTrigger.events.onClick.fx : null;","  if (originalOnClickFx) {","    hideTrigger.removeEvent('onClick');","  }","","  hideTrigger.createEvent('onClick', (ctx) => {","    this.properties.isShown = false;","    if (originalOnClickFx) {","      originalOnClickFx(ctx);","    }","  });","}"]}},{"type":"layout/modal","key":"modal-on-click2","properties":{"height":"45vh","width":"39vw","clickOutsideToClose":false},"additionalDefs":{"showTrigger":{"type":"actor","label":"Affichage","helperTxt":"Acteur qui déclenche l'affichage."},"hideTrigger":{"type":"actor","label":"Fermeture","helperTxt":"Acteur qui déclenche la fermeture."}},"additionals":{"showTrigger":"BP_centri2","hideTrigger":"nav-synoddeshydra1"},"children":[{"type":"layout/canvas","key":"canvas2","properties":{"verticalAlignment":"expand"},"children":[{"type":"display/screen","key":"screen2","properties":{"top":"0px","bottom":"0px","right":"0px","left":"0px","sceneKey":"tab_centri1"}},{"type":"input/nav-button","key":"nav-synoddeshydra1","properties":{"content":"\n","height":"37px","width":"37px","paddingTop":"1px","paddingBottom":"1px","paddingRight":"1px","paddingLeft":"1px","horizontalAlignment":"middle","backgroundRepeat":"no-repeat","borderWidth":"","backgroundPosition":"center","displaySceneKey":"deshydratation","top":"0px","right":"0px"},"additionalDefs":{"prop1":{"type":"scene"}},"bindings":{"properties.backgroundImage":"picture@Exit"}}]}],"events":{"onPostInit":["const showTrigger = context.getActor(this.additionals.showTrigger);","","","if (showTrigger) {","  const originalOnClickFx = showTrigger.events.onClick ? showTrigger.events.onClick.fx : null;","  if (originalOnClickFx) {","    showTrigger.removeEvent('onClick');","  }","","  showTrigger.createEvent('onClick', (ctx) => {","    this.properties.isShown = true;","    if (originalOnClickFx) {","      originalOnClickFx(ctx);","    }","  });","}","","const hideTrigger = context.getActor(this.additionals.hideTrigger);","","if (hideTrigger) {","  const originalOnClickFx = hideTrigger.events.onClick ? hideTrigger.events.onClick.fx : null;","  if (originalOnClickFx) {","    hideTrigger.removeEvent('onClick');","  }","","  hideTrigger.createEvent('onClick', (ctx) => {","    this.properties.isShown = false;","    if (originalOnClickFx) {","      originalOnClickFx(ctx);","    }","  });","}"]}}],"bindings":{"properties.backgroundColor":"color@vertwit"}}}

**Comment by simhelio** [comment]
Bon, j'ai trouvé le problème.
Dans mon cas, j'ai deux modales l'une sur l'autre et la première avait le sélecteur " ferme si clic ailleurs " d'activé.

**Comment by Raphwit** [comment]
Effectivement, il faut faire attention aux modales dans les modales cela peut engendrer des soucis comme ceux-ci, ces interactions sont quelques peu imprévisibles
