### ISSUE TITLE
Ouverture d'un PDF

### ISSUE THREAD

**Issue by edejean** [witsa/synapps#609]
Bonjour,
Je n'arrive simplement pas à ouvrir un PDF dans une frame.
J'ai essayé avec l'acteur html et le pdf en utilisant "<embed src="url" width="1800" height="1134" type="application/pdf"/>" mais je ne comprends pas comment lui indiquer la source /web/pdf... j'ai créé le fournisseur de variable ":WEB.pdf" mais sans trop savoir quoi en faire...
J'ai tenté l'acteur iframe en créant un html appelant mon pdf, mais à priori, je n'arrive pas à l'afficher, il me demande de télécharger le pdf...
Auriez-vous un moyen simple d'afficher un pdf se situant dns un dossier "pdf" créer dans le dossier "WEB" existant ?
Merci d'avance
Cdt
Eric

**Comment by Raphwit** [comment]
Bonjour, si le téléchargement fonctionne, c'est que cela fonctionne et une fois la Synapp poussée dans le REDY, cela fonctionnera.

Malheureusement il y a pour l'instant un bug dans Studio qui empêche la visualisation de fichier PDF et qui donc propose uniquement le téléchargement du PDF, nous notons cela et nous le corrigerons au plus vite !

**Comment by manufitoussiwit** [comment]
C'est corrigé dans la version 1.3.0

**Comment by AdrienAzay** [comment]
Bonjour,
Pourriez-vous indiquer la manière dont vous avez procédé dans ce cas 👍 ?
Merci d'avance

**Comment by Raphwit** [comment]
> Bonjour, Pourriez-vous indiquer la manière dont vous avez procédé dans ce cas 👍 ? Merci d'avance

Hello, voilà un tuto sur le sujet : https://witsa.github.io/synapps/tutorials/open-pdf/iframe-pdf.html

**Comment by AdrienAzay** [comment]
> > Bonjour, Pourriez-vous indiquer la manière dont vous avez procédé dans ce cas 👍 ? Merci d'avance
> 
> Hello, voilà un tuto sur le sujet : https://witsa.github.io/synapps/tutorials/open-pdf/iframe-pdf.html

Merci beaucoup, cela m'a été très utile !!
