### ISSUE TITLE
Filtre des Etats inopérant

### ISSUE THREAD

**Issue by PatinAroulettes** [witsa/synapps#61]
Dans un acteur liste d'états les filtres ne fonctionnent pas (ex : filtre des zones) :
![image](https://user-images.githubusercontent.com/33750858/35152196-a14ca53c-fd21-11e7-809f-bc22c62c5a09.png)

**Comment by ericvoignier** [comment]
Peux tu copier le projet dans \\wit-file\Echange\SynApps\Issues\61

**Comment by PatinAroulettes** [comment]
OK, c’est fait
(Code : Admin et .)

De : ericvoignier [mailto:notifications@github.com]
Envoyé : lundi 29 janvier 2018 18:29
À : witsa/synapps
Cc : Jean Francois GINI; Author
Objet : Re: [witsa/synapps] Filtre des Etats inopérant (#61)


Peux tu copier le projet dans \wit-file\Echange\SynApps\Issues\61

**Comment by ericvoignier** [comment]
Déployé 1.3.3
