### ISSUE TITLE
Prise en compte police/Taille de texte

### ISSUE THREAD

**Issue by ArmandGC** [witsa/synapps#612]
Bonjour,
Je viens de me rendre compte après avoir charger ma synapps sur mon redy que la police d'écriture de l'onglet Généralités ne sont pas prises en compte. j'ai eu à les ajouté dans ma vue Gabarit.
Quelqu'un d'autre a eu le même problème ?
au final ça fonctionne quand même mais pas avec les info de la vue généralité

**Comment by Raphwit** [comment]
Bonjour, je n'ai pas noté ce comportement chez moi, êtes vous sûr qu'une police n'est pas définie au sein de la Synapp et donc prends le dessus sur la police dans "généralités"

**Comment by ArmandGC** [comment]
J'en suis certain,
lorsque je teste via synapps via le bouton "exécuter dans le navigateur", la police de "généralités" est prise en compte mais dès que je charge dans un automate ce n'est plus le cas.
par contre lorsque je met la police au niveau de la viewbox du gabarit c'est pris en compte dans les deux cas.

**Comment by Raphwit** [comment]
Effectivement, je constate le même comportement, c'est bel et bien un bug, merci de nous l'avoir remonté, je l'ajoute à la liste des corrections pour la prochaine version !

**Comment by manufitoussiwit** [comment]
La correction sera dans la prochaine version de Studio 👍

**Comment by manufitoussiwit** [comment]
Corrigé dans la version `1.2.0`
