### ISSUE TITLE
Images dans librairies non résolues dans HGW

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#614]
_StepToReproduce:_

1. Ajouter une image dans librairie
2. Lier l'image à un acteur image
3. Déployer la SynApp sur HGW

L'image ne s'affiche pas car la source est de type: _data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA..._
Hors le lien devrait être de type: _https://synapp.../picture/cf6442d0-6745-4bb3-a7c4-067ccd1e0f3c/0_

A noter que lors de la désérialisation de la SynApp le lien vers l'image de la librairie est correcte (voir loadPictures dans setup-highway) mais il  semble que quelquechose vienne encoder le lien http en dataUrl ...

**Comment by ericvoignier** [comment]
- Setup Studio: [test-image.zip](https://github.com/witsa/synapps/files/12213666/test-image.zip)
- Runtime: https://synapp.wit-datacenter.com/runtime/testimage/debug#/testimage/scene1

**Comment by manufitoussiwit** [comment]
Corrigé dans la version `1.2.0`
