### ISSUE TITLE
Modification option d'une liste

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#626]
Quand on édite le contenu, c'est à dire les options, la fenetre se décale vers le haut... ce n'est pas grand chose, mais on retrouve perdu quand le menu "saute".
Peu importe la position de l'ascenseur, il se recale tout seul sur l'option éditer et j'avoue que ça me perturbe un peu à chaque fois que je clique :)
![image](https://github.com/witsa/synapps/assets/33632664/d1c5eb7e-6a5c-46b6-9144-141a19bc376c)

**Comment by Raphwit** [comment]
Cela partais d'une bonne intention pour mettre en avant l'option que le souhaite éditer et ainsi être certain de visualiser l'option que l'on a ouverte sans avoir à scroll mais cela peut tout à faire être changé si tu trouves que cela est déroutant, merci du retour ! 👍

**Comment by WITNicolas** [comment]
En fait c'est comme la souris, tu peux activer le magnetisme auto dans windows pour qu'elle vienne se caler sur les boites de confirmation oui/non valider/annuler .... ben c'est pas bien :)
En résumé, une action qui n'est pas maitrisée et qui est du coup est automatique, est perturbante :) parce que tu n'en ai pas l'origine.

**Comment by Raphwit** [comment]
Corrigé pour la prochaine version ! :)

**Comment by manufitoussiwit** [comment]
Corrigé dans la version `1.2.0`
