### ISSUE TITLE
Acteur slider génère une instabilité totale si min>=max

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#63]
[Synapp et Composite.zip](https://github.com/witsa/synapps/files/1648902/Synapp.et.Composite.zip)

Après avoir gérer des seuils mini / maxi d'un acteur slider en les liaisonnant au Min Max d'une ressource consigne analogique (j'avais laissé les valeurs à 0 / 0 dans la ressource REDY).
Le composite a explosé, impossible de le récupérer....

Est ce qu'il y a moyen de faire quelque chose pour récupérer ça, j'avais presque fini évidement ...

Avant ... ce n'est pas le dernier visuel mais ça ressemblait à ça avec des acteurs en plus.
![img_7549](https://user-images.githubusercontent.com/33632664/35184718-7b272250-fdf9-11e7-97bb-ce2995ffd03a.PNG)

Aprés ...
![image](https://user-images.githubusercontent.com/33632664/35184706-5ba7fac6-fdf9-11e7-8842-3f7cb7740aee.png)

La scene qui utilise le composite ne fonctionne plus non plus, bref hécatombe ...

**Comment by ericvoignier** [comment]
Attention au pb du seuil mini. Je regarde le param.

**Comment by ericvoignier** [comment]
OK récupérable, je te le corrige. En tout cas beau travail !

**Comment by ericvoignier** [comment]
[2018_01_20 GTB WHOME-easy.SynApps.Test.Composites.Atlantic.WK4.zip](https://github.com/witsa/synapps/files/1648931/2018_01_20.GTB.WHOME-easy.SynApps.Test.Composites.Atlantic.WK4.zip)
Composite corrigé, la liaison min/max sur le _slider48_ est supprimée. La scène devrait également fonctionner

**Comment by ericvoignier** [comment]
A faire **rapidement**: correction pb du min >= max sur l'acteur _slider_ qui entraîne un bug non récupérable

**Comment by ericvoignier** [comment]
@WITNicolas avais tu essayé de définir min et max sur la ressource ?

**Comment by WITNicolas** [comment]
merci, je me fais la main :)
oui j'ai essayé de mettre les min max mais pas mieux...

**Comment by WITNicolas** [comment]
Bon je crois que c'est plus compliqué que cela. J'ai remplacé le composite et même résultat (j'aurais dû percuter sur le bug du min / max...)

J'ai ce message dans l'URL, je ne sais pas si ça peut aider..
http://appria.wit.fr/synApps-maker/index.html#/app-error/%3Cb%3E(code:%200)%3C%2Fb%3E%20Cannot%20read%20property%20'off'%20of%20undefined

En tout cas ce n'est pas pressé je vais faire autre chose pour m'amuser ;).. profite de ton weekend !

**Comment by ericvoignier** [comment]
Oui pb de rendu du slider. Envoie nous le PK4 (par mail) car avec le WK4 la SynApp n'arrive pas à charger  les ressources liées +

**Comment by ericvoignier** [comment]
Modifier le numéro de _build_ de la SynApp dans le **Redy** pour forcer le rafraîchissement du composite dans le navigateur

**Comment by WITNicolas** [comment]
Ok effectivement ça passe mieux ...

**Comment by ericvoignier** [comment]
Fixé dans:

- Maker: message d'avertissement sur les propriétés min et max
- Runtime: rendu de l'acteur avec valeurs par défaut 0, 100 si min>max

En attente déploiement 1.3

**Comment by ericvoignier** [comment]
Déployé 1.3.3
