### ISSUE TITLE
Je n'arrive plus à charger la Synapps dans mon automate ou un RedyPC

### ISSUE THREAD

**Issue by edejean** [witsa/synapps#634]
Bonsoir,
Je viens de terminer les modification de mon projet Synapps et là, grosse erreur en fin de téléchargement de mon synapps sur l'automate avec un "PreconditionFailedError...

![image](https://github.com/witsa/synapps/assets/105919791/af6b3848-8b77-4034-b606-528efa2b5caa)

Je tente de réaliser la même chose sur un RedyPC, même erreur...

Je tente un export du projet, recrée un nouveau projet à partir de l'export, toujours le même souci, c'est la cata... le projet est supposé être livré demain et impossible de le charger...

Voici un lien weTransfert avec l'export de la synapps : https://we.tl/t-qW4hqqkP1i

J'ai besoin de charger absolument cette synapps demain matin...

Bien cdt

Eric

**Comment by manufitoussiwit** [comment]
Salut,
La scène `ROOFTOP 7B.1 - Cellule 7B` est en doublon. La clé de cette scène apparait une seconde fois pendant la publication d'ou l'erreur. 
Ca arrive très rarement qu'on se retrouve avec un doublon et on va corriger ça dans la version qui arrive.
Quand ça arrive, il suffit :
- soit de changer la clé de scène en doublon
- soit de la supprimer.


Sinon, je me permet un conseil, Il y a beaucoup d'image dans la librairie. J'ai l'impression qu'elles ne sont pas toutes utilisées. Du coup ça ralenti la publication et occupe de l'espace inutilement dans le REDY. 
Le mieux serait de laisser uniquement les images utilisées déclarées dans la librairies. Les autres images peuvent tout a fait rester dans le dossier sans les enregistrer en librairie, ça gênera plus. 👍

**Comment by manufitoussiwit** [comment]
J'en profite encore : 

ça donne encore mieux avec un arrière plan noir pour éviter que les navigations se fassent avec un fondu blanc à chaque fois. Pour ça : 
Dans généralités, il faut changer la couleur d'arrière plan pour du noir. Et dans la scène `Home page`, il faudrait enlever la couleur blanche d'arrière plan.

Mais de toute manière : 
# Très belle synapp !! Bravo ! 👏

**Comment by edejean** [comment]
[signature_401425535]

Bonjour Emmanuel et merci beaucoup,

Je trimbale ce doublon depuis un moment à priori, et la Synapps avait déjà été publié mais il est vrai qu’hier, j’en fait une copie pour faire une v3, le problème est apparu avec cette nouvelle copie, bref, j’ai renommée mon doublon, et ai téléchargé sur mon RedyPC, et c’est passé !!!!!

Pour les images, je t’avoue, j’aurais du le faire au fil de l’eau, vous n’auriez pas un petit outil qui permettrait de vérifier quelle image est utilisée ou non ? pour les mauvais élèves comme moi par exemple…

En tout cas, merci encore pour ton aide.

Cordialement,

- - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Eric DEJEAN / DOMOCORE

(+33) 6 60 43 24 51
***@***.******@***.***>

Adresse des bureaux :
184, avenue Saint Exupéry
31400 Toulouse

[signature_1000732461]



De : Emmanuel FITOUSSI ***@***.***>
Date : jeudi, 12 octobre 2023 à 01:36
À : witsa/synapps ***@***.***>
Cc : Eric Dejean ***@***.***>, Author ***@***.***>
Objet : Re: [witsa/synapps] Je n'arrive plus à charger la Synapps dans mon automate ou un RedyPC (Issue #634)

J'en profite encore :

ça donne encore mieux avec un arrière plan noir pour éviter que les navigations se fassent avec un fondu blanc à chaque fois. Pour ça :
Dans généralités, il faut changer la couleur d'arrière plan pour du noir. Et dans la scène Home page, il faudrait enlever la couleur blanche d'arrière plan.

Mais de toute manière :

Très belle synapp !! Bravo ! 👏

**Comment by manufitoussiwit** [comment]
Pour les librairies, on réfléchit à un truc justement pour détecter celles qui sont utilisées et celles qui ne le sont pas.
