### ISSUE TITLE
Lien Additionnel fantome dans un acteur

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#636]
Bonjour,

En regardant les erreurs d'affichage d'un de nos synapps, il semble que j'ai un additionnelle fantome sur certains de mes acteurs pointant un acteur "subMenu_ReglageCVC" qui n'existe pas dans ma scène.

Capture de l'erreur en question depuis mon navigateur
![01](https://github.com/witsa/synapps/assets/50445069/25151833-4d16-4b3e-a952-23caded3ac3e)
Capture de l'acteur sur SynappsStudio
![02](https://github.com/witsa/synapps/assets/50445069/405c2bdf-41a9-46c5-bfa5-50661b06509a)

Acteur en question :
`SYNAPPS-STUDIO-ACTOR|{"type":"display/text","key":"text4","properties":{"content":"Mode Portrait : {{Value}}"},"additionalDefs":{"Value":{"type":"text"}},"bindings":{"properties.fontSize":{"sourceType":"actor","sourceKey":"TAILLE","path":"additionals.MenuTailleTexteNiv2"},"properties.color":{"sourceType":"color","path":"SceneMenuTexte"},"properties.lineHeight":{"sourceType":"actor","sourceKey":"TAILLE","path":"additionals.MenuHauteurTexteNiv2"},"additionals.Hauteur":{"sourceType":"actor","sourceKey":"subMenu_ReglageCVC","path":"key"},"additionals.Value":{"sourceType":"user-agent","path":"isPortrait"}}}`

A noter que j'avais copié les acteurs problématiques depuis un autre projet qui disposait d'un acteur "subMenu_ReglageCVC"

**Comment by Raphwit** [comment]
Bonjour, il existe des liaisons fantômes dans l'acteur suspecté, je n'ai pas d'idée sur le "comment" de l'apparition de ces liaisons fantômes mais si l'on regarde dans l'onglet "JSON Acteurs" vers les "bindings" il existe une liaison vers "additionals.Hauteur" qui pointe vers la clé d'un acteur.
Cette liaison ne devrait pas se trouver ici, d'ou l'erreur.
