### ISSUE TITLE
Profils de résolutions prédéfinis

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#65]
Prévoir un sélecteur avec des résolutions prédéfinies en fonction d'un équipement en plus de la saisie manuelle, a la manière du mode F12 des navigateurs.
Cette liste pourrait évoluer en fonction des sorties matérielles.

**Exemples**
Eview
Full HD
4K
Apple Iphone X
Apple Iphone 6S
Samsung Galaxy Tab 10
Samsung Galaxy Note 8
...

**Comment by WITNicolas** [comment]
[Synapps Maker - Google Chrome 07_03_2018 22_17_35.zip](https://github.com/witsa/synapps/files/1790969/Synapps.Maker.-.Google.Chrome.07_03_2018.22_17_35.zip)

Léger petit bug lors de la rotation d'une résolution prédéfinie.
-Il y a un sursaut d'image
-Le texte de la résolution choisie disparaît.

**Comment by ericvoignier** [comment]
Le libellé de la taille qui disparait lors de la rotation est le comportement attendu: le libellé défini la hauteur et la largeur, par exemple: largeur:1920xhauteur:1080, la rotation fait naturellement que le libellé ne correspond plus. Tu peux créer un libellé _Full HD 2_ avec largeur:1080xhauteur:1920.
**L'objectif était d'avoir un raccouci rapide pour un prévisu.** 
Après reflexion .... il est vrai que l'on pourrait considérer qu'il s'agit du même label en portrait ou paysage le bouton de rotation permettant la bascule d'un mode à l'autre.

**Comment by ericvoignier** [comment]
Nous allons ajouter d'autres dimensions standards pour l'_Eview_, _4K_, n’hésitez pas à compléter si besoin
