### ISSUE TITLE
Erreur sur acteur bouton navigation lors du changement de la scène

### ISSUE THREAD

**Issue by PatinAroulettes** [witsa/synapps#66]
Je duplique un bouton existant, je modifie son label, lorsque je change le plan de destination du bouton, l'application plante :+1: 
![image](https://user-images.githubusercontent.com/33750858/35225052-875fc902-ff87-11e7-8528-2ffb84461fd1.png)

**Comment by ericvoignier** [comment]
Pb fixé en attente déploiement 1.3.4
