### ISSUE TITLE
[REFLET] Reflet loi d'eau

### ISSUE THREAD

**Issue by manufitoussiwit** [witsa/synapps#669]
### Discussed in https://github.com/witsa/synapps/discussions/667

<div type='discussions-op-text'>

<sup>Originally posted by **ABIAdrienG** November 23, 2023</sup>
Bonjour,
Depuis le passage en 1.2.0 nous n'arrivons plus à afficher correctement le reflet loi d'eau.
![image](https://github.com/witsa/synapps/assets/127521459/03ca10d7-15cb-4c38-8b9f-24ec78c99f46)
La représentation de la courbe semble ne plus être liée à la taille de police. 
Quel est le nouveau facteur influençant la taille du graphique ?

Je vous remercie par avance !

A.G.</div>

**Comment by manufitoussiwit** [comment]
Oula! c'est petit !

L'affichage normal : 

![image](https://github.com/witsa/synapps/assets/35595723/a79e6cc2-e99a-4310-9850-04574d3489b8)


**Hypothèse :** Le détails est dans une boite à vue et la taille est réglée en `em`. La taille en `em` doit être très grosse, du coup le détails est très gros aussi, mais la boite à vue compense. 
Le graphique, lui, ne suit pas la taille en `em` (comportement normal). Résultat, il apparait très petit par rapport au reste.

Pour en être sûr, le mieux est de copier/coller la scène ici.

**Comment by SeddikRebbaj** [comment]
Bonjour, @manufitoussiwit 

C'est normal que je ne vois pas scène à copier ?

**Comment by Raphwit** [comment]
Bonjour, je pense que ce que @manufitoussiwit voulais dire c’est que le plus simple est que de nous fournir la scène en la collant dans cette discussion !

**Comment by WITNicolas** [comment]
Bonjour,
Il faudrait que vous copiiez votre scene dans le Github pour que l'on puisse voir ce qui ne va pas.

**Comment by SeddikRebbaj** [comment]
Autant pour moi vous retrouverais la scène ci dessous :


SYNAPPS-STUDIO-SCENE|{"config":{"key":"Reglages","name":"Reglages"},"leadActor":{"type":"layout/view-box","key":"view-box1","properties":{"height":"100vh","width":"100vw"},"children":[{"type":"layout/canvas","key":"canvas1","properties":{"height":"100vh","width":"100vw","horizontalAlignment":"left","verticalAlignment":"top"},"children":[{"type":"display/text","key":"Titre","properties":{"content":"Text","textAlign":"center","fontWeight":"bold","textDecoration":"none","fontStyle":"normal","fontVariant":"normal"},"bindings":{"properties.width":"constant@LargeurPage","properties.height":"constant@hauteurMenu_D","properties.color":"color@fond","properties.backgroundColor":"color@themeColor","properties.fontSize":"constant@taillePoliceTitle","properties.content":"stage@name","properties.fontFamily":"constant@TypePolice"}},{"type":"display/text","key":"textDepartChaudiere","properties":{"content":"Départ Chaudière Gaz","backgroundColor":"rgba(255, 255, 255, 1)","color":"rgba(0, 102, 255, 1)","top":"70px","left":"40px","fontWeight":"bold","fontSize":"30px"}},{"type":"display/text","key":"textDepartChauffage","properties":{"content":"Départ Radiateur Restaurant ","backgroundColor":"rgba(255, 255, 255, 1)","color":"rgba(0, 102, 255, 1)","top":"70px","left":"390px","fontWeight":"bold","fontSize":"30px"}},{"type":"display/text","key":"textDepartPlancherChauffant","properties":{"content":"Départ Radiateur Bureaux","backgroundColor":"rgba(255, 255, 255, 1)","color":"rgba(0, 102, 255, 1)","top":"70px","left":"930px","fontWeight":"bold","fontSize":"30px"}},{"type":"display/text","key":"textDepartCTA","properties":{"content":"Départ Vestiaires","backgroundColor":"rgba(255, 255, 255, 1)","color":"rgba(0, 102, 255, 1)","top":"70px","left":"1450px","fontWeight":"bold","fontSize":"30px"}},{"type":"layout/stack","key":"stackChaudiere","children":[{"type":"redy/reflect-details","key":"etatChaudiere","properties":{"borderStyle":"solid","top":"140px","left":"50px","fontSize":"15px","withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00005"}},{"type":"redy/reflect-details","key":"TNCchaudiere","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00038.R00014","submitMode":"auto"}},{"type":"redy/reflect-details","key":"TNCchaudiere1","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00038.R00053","submitMode":"auto"}},{"type":"redy/reflect-details","key":"TNCchaudiere2","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00038.R00098","submitMode":"auto"}},{"type":"redy/reflect-details","key":"TNCchaudiere3","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00038.R00100","submitMode":"auto"}}],"properties":{"top":"130px","left":"40px","fontWeight":"bold","width":"320px","borderColor":"rgba(0, 0, 0, 1)","borderWidth":"2px","borderStyle":"solid","textAlign":"center"}},{"type":"layout/stack","key":"stackChauffageRestaurant","children":[{"type":"redy/reflect-details","key":"etatPompeChauffage","properties":{"borderStyle":"solid","top":"140px","left":"50px","fontSize":"15px","withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00013.R00057.R00016","width":"450px"}},{"type":"redy/reflect-details","key":"CMDchauffage","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00013.R00057.R00101","submitMode":"auto","width":"450px"}},{"type":"redy/reflect-details","key":"V3Vchauffae","properties":{"withIcon":false,"submitMode":"auto","reflectPath":"VarImg.AO.R00007","borderStyle":"solid","width":"450px"}},{"type":"redy/reflect-details","key":"LoiOchauffage","properties":{"withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00013.R00057.R00018","borderStyle":"solid","top":"290px","left":"540px","width":"450px"}}],"properties":{"top":"130px","left":"390px","fontWeight":"bold","borderColor":"rgba(0, 0, 0, 1)","borderWidth":"2px","borderStyle":"solid","textAlign":"center","width":"450px"}},{"type":"layout/stack","key":"stackChauffageBureaux","children":[{"type":"redy/reflect-details","key":"etatPompeChauffage1","properties":{"borderStyle":"solid","top":"140px","left":"50px","fontSize":"15px","withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00013.R00268.R00016","width":"450px"}},{"type":"redy/reflect-details","key":"CMDchauffage1","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00013.R00268.R00101","submitMode":"auto","width":"450px"}},{"type":"redy/reflect-details","key":"V1","properties":{"withIcon":false,"submitMode":"auto","reflectPath":"VarImg.AO.R00121","borderStyle":"solid"}},{"type":"redy/reflect-details","key":"LoiOchauffage1","properties":{"withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00013.R00268.R00018","borderStyle":"solid","width":"450px"}}],"properties":{"top":"130px","left":"930px","fontWeight":"bold","borderColor":"rgba(0, 0, 0, 1)","borderWidth":"2px","borderStyle":"solid","textAlign":"center","width":"450px"}},{"type":"layout/stack","key":"stackChauffageVestiaires","children":[{"type":"redy/reflect-details","key":"etatPompeChauffage2","properties":{"borderStyle":"solid","top":"140px","left":"50px","fontSize":"15px","withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00013.R00269.R00016","width":"450px"}},{"type":"redy/reflect-details","key":"CMDchauffage2","properties":{"borderStyle":"solid","fontSize":"15px","withIcon":false,"reflectPath":"Chaufferie.Prod.R00013.R00269.R00101","submitMode":"auto","width":"450px"}},{"type":"redy/reflect-details","key":"V2","properties":{"withIcon":false,"submitMode":"auto","reflectPath":"VarImg.AO.R00242","borderStyle":"solid","width":"450px"}},{"type":"redy/reflect-details","key":"LoiOchauffage2","properties":{"withIcon":false,"submitMode":"auto","reflectPath":"Chaufferie.Prod.R00013.R00269.R00018","borderStyle":"solid","width":"450px"}}],"properties":{"top":"130px","left":"1450px","fontWeight":"bold","borderColor":"rgba(0, 0, 0, 1)","borderWidth":"2px","borderStyle":"solid","textAlign":"center","width":"450px"}}],"bindings":{"properties.width":"constant@LargeurPage","properties.height":"constant@HauteurEcran"}}]}}

**Comment by manufitoussiwit** [comment]
Merci, 
pouvez vous me donner les valeurs des constantes LargeurPage et HauteurEcran s'il vous plait ?

**Comment by SeddikRebbaj** [comment]
Ma constante largeurPage est de 1920px et ma constante hauteurEcran est de 1080px

**Comment by ABIAdrienG** [comment]
Bonjour, Je prends la suite. 
J'ai encapsulé le reflet dans un canevas de 700px par 700px. Mais je n'arrive toujours pas à agrandir le graphique. La taille des textes est bien liée à la variable "Texte:Taille" mais plus le graphique depuis la MAJ 1.2.0. 
Quel est le nouveau paramètre pour la taille du graphique ?

Je vous remercie !
Adrien

SYNAPPS-STUDIO-ACTOR|{"type":"layout/canvas","key":"canvas2","properties":{"height":"800px","width":"800px","top":"220px","left":"910px"},"children":[{"type":"redy/reflect-details","key":"reflect-details3","properties":{"withIcon":false,"withName":false,"reflectPath":"R00053.R00173.R00045.R00056","height":"100%","width":"100%","isVertical":false}}]}

**Comment by manufitoussiwit** [comment]
Bonjour, ce que je peux vous proposer c'est d'utiliser l'acteur suivant pour modifier un peu le comportement du graphique :

```text
SYNAPPS-STUDIO-ACTOR|{"type":"display/html","key":"reflect-style","properties":{"content":"<style>\n  .redy-reflect-details .content .reflect-details-heating-curve canvas {\n    width: 100% !important;\n  }\n</style>"}}
```

Si vous le placer dans la même scène qu'un acteur détails qui montre un reflet courbe de chauffe, il va faire en sorte que le graphique suive la largeur de l'acteur.

**Comment by ABIAdrienG** [comment]
D'accord, merci ça semble fonctionner.
Est-ce que c'est considéré comme un bug ? 
Est-ce que un champ sera disponible dans les prochaines versions pour gérer la taille du graphique simplement ?

Je vous remercie par avance.

Adrien

**Comment by ABIAdrienG** [comment]
Je rencontre trop de difficultés pour afficher la loi correctement. Lorsque je zoom sur la page sur un automate la loi d'eau devient flou/disparait puis apparait... De plus elle semble ne pas prend en compte le style. Je vais redescendre la version de synapps. Je reste à l'écoute des prochains patch-notes.

Adrien

**Comment by manufitoussiwit** [comment]
Il n'y a pas de grosse différence avec l'ancienne version normalement. 
Pour que je comprennes ce qui vous arrive : 
- quand vous parler de zoomer, quel est l'opération que vous réalisez?
- quel est l'environnement de l'acteur détails ?


Aussi, le graphique est générée pour une taille donnée. Si on zoom avec le navigateur, il va apparaitre flou si on zoom beaucoup. Mais faut beaucoup zoomer :-) . Dans votre cas, j'ai l'impression que le graphique est généré très petit, ce qui produirait un graph très vite pixelisé et flou si on zoom.
