### ISSUE TITLE
Refresh Acteur Journal

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#67]
J'ai l'impression que l'acteur journal ne se rafraîchit pas automatiquement. Si un événement apparaît dans le REDY, celui ci n’apparaît pas dans la SYNAPP tant qu'on fait pas un F5.

Vu qu'il n'y a pas la notion de SOURCE pour l'acteur journal, il n'y a pas de tempo réglable de refresh.

**Comment by ericvoignier** [comment]
Oui aucun rafraîchissement n'est implémenté.

_Proposition:_ ajouter une propriété **Période de rafraichissement** en secondes. _Null_ par défaut, signifiant pas de mise à jour auto.

_Remarque:_ pas de source à définir, le journal est un acteur métier intégrant directement le pulling vers Redy.

**Comment by ericvoignier** [comment]
Pour mémo, prévoir même comportement pour l'acteur _Liste des états_

**Comment by WITNicolas** [comment]
Je ne mettrais pas la periode de refresh en Null. 
Je pense qu il faudrait mettre une valeur qui soit cohérente comme 10 sec. 
Cela pourrait etre piegeux. 
Les listes etats meme principe.

**Comment by ericvoignier** [comment]
Mise en place du mécanisme d'auto-refresh sur journal et états. La valeur par défaut est de 30 secondes.
La période de rafraîchissement est configurée par la propriété _Période_
![image](https://user-images.githubusercontent.com/9974702/35574123-3dae3bc4-05d9-11e8-8c03-f4d49d342396.png)
_Remarque:_ une nouvelle propriété _Date fraicheur_, en lecture seule, permet de connaitre la date de requetage du journal ou des états. Utile pour informer l'utilisateur en liant cette information sur un acteur texte par exemple.
En attente déploienent 1.3.3

**Comment by ericvoignier** [comment]
Déployé 1.3.3
