### ISSUE TITLE
Problème d'affichage des courbes de chauffes

### ISSUE THREAD

**Issue by AmauryPit1** [witsa/synapps#672]
Lorsque je me connecte au REDY, je m'authentifie, puis je suis automatiquement redirigé vers le Synapps. 
Ensuite, j'ouvre l'onglet dédié à la chaufferie et clique sur un bouton qui me permet d'afficher la courbe de chauffe de mon circuit. Cependant, dès que j'appuie sur ce bouton, la fenêtre pop-up affiche une interface incomplète.
![image](https://github.com/witsa/synapps/assets/152264626/ff5bb082-3dd9-4d77-ae70-b012d2538657)

En revanche, si je lance REDY, patiente une dizaine de secondes dans l'onglet de connexion, puis me connecte et effectue la même manipulation, l'onglet pop-up s'affiche parfaitement.
![image](https://github.com/witsa/synapps/assets/152264626/632f02f2-71bf-4725-a05f-26680ddcfeae)

Je ne suis pas certain de savoir si le problème provient du logiciel Synapps ou du programme Wit sur REDY. 
Si une résolution est possible, cela m'arrangerait. 
Merci.

**Comment by manufitoussiwit** [comment]
Salut,
Si vous relancer à chaque fois le REDY, oui cela vient bien du REDY. 
En effet, les reflets mettent une dizaine de secondes avant d'être correctement valorisés. Dans les prochaines versions du REDY, ce temps sera réduit.

**Comment by AmauryPit1** [comment]
> Salut, Si vous relancer à chaque fois le REDY, oui cela vient bien du REDY. En effet, les reflets mettent une dizaine de secondes avant d'être correctement valorisés. Dans les prochaines versions du REDY, ce temps sera réduit.

Merci pour votre réponse, ça signifie que pour l'instant je ne peux rien y faire ?

**Comment by AmauryPit1** [comment]
[Vidéo bug courbe de chauffe.zip](https://github.com/witsa/synapps/files/13487552/Video.bug.courbe.de.chauffe.zip)

Dans le fichier ZIP ci-joint un exemple de fonctionnement où ça bug et un autre nickel

**Comment by AmauryPit1** [comment]
J'ai effectué plusieurs tests avec le code de la "modale au clic" sur Synapps, et nous pouvons d'ores et déjà la faute au code d'affichage de la fenêtre. 
Après avoir examiné le code source du site web et de l'application, il semble rencontrer des difficultés pour récupérer les reflets et les valeurs _easyress_. 
En ce qui concerne les courbes de chauffe, une erreur critique se produit pour les deux courbes de chauffe.

![image](https://github.com/witsa/synapps/assets/152264626/5d633254-3736-441c-850c-e15ccb8c367d)

**Comment by manufitoussiwit** [comment]
Je confirme, c'est bien analysé. 

Le REDY au démarrage n'a pas ses reflets dans le bonne état. Si Synapps interroge les reflets pendant ce lapse de temps, le REDY lui donne des informations erronées. Notamment pour la courbe de chauffe : c'est carrément n'importe quoi :-), y a pas de point, ça génère une erreur.

Environ 10 secondes après son démarrage, le REDY passe sur tous les reflets pour les mettre dans le bon état. 
A partir de là, tout va mieux côté Synapps qui obtient des informations cohérentes. Bémol pour la courbe de chauffe qui s'est pris une erreur et, qui si elle reste affichée, aura du mal a afficher le bon état. Par contre, si on recharge l'acteur, c'est ok.

Tout ça est dû au délai d'initialisation des reflets côté REDY. Ce sera corrigé dans la prochaine version (délai plus court : 1s au lieu de 10s).

Si je comprend bien, ça pose surtout un pb pour REDY PC qui lorsqu'il démarre, invite à se connecter de suite. Pour les REDY c'est moins un pb non ?

**Comment by AmauryPit1** [comment]
C'est exactement cela. 
Le problème provient du REDY-PC, ce qui a sûrement des répercussions sur le test de prévisualisation du Synapps.

D'un autre côté, j'ai transféré le programme sur le REDY, et tout se déroule parfaitement. Aucun délai n'est observé lors de la récupération des reflets, voire des points des courbes. 
C'est un aspect positif, mais il serait préférable de ne pas se limiter à vérifier le fonctionnement du Synapps uniquement avec le REDY afin de gagner du temps ^^.

Maintenant que le problème a été identifié, je vous remercie pour vos réponses et votre réactivité.

En attendant votre réponse pour clôturer le billet de demande,
Bonne journée.

**Comment by belkasse** [comment]
Bonjour, je n'arrive pas à créer une représentation graphique de la loi d'eau, lorsque je lie le reflet à la variable , j'ai la loi d'eau en valeur et pas en  courbe.
pourriez vous svp m'indiquer la procédure pour avoir le reflet en courbe?
