### ISSUE TITLE
Présentation des sources de données trop grande

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#68]
Revoir présentation des sources de données avec tailles trop importantes, tooltip et chemins peu lisibles
![image](https://user-images.githubusercontent.com/9974702/35383390-76c004da-01c2-11e8-9886-fcadd91d9299.png)

**Comment by WITALD** [comment]
En général dans les listes des "propriétés", des "Evènements" il serait bien d'avoir le texte sur une seul ligne quand c'est possible.

![image](https://user-images.githubusercontent.com/35064776/35384342-3d5c6d34-01c5-11e8-847c-1934823e44b1.png)

![image](https://user-images.githubusercontent.com/35064776/35384458-a4b4893a-01c5-11e8-90b1-21c7a2b1d406.png)

**Comment by ericvoignier** [comment]
Ok, on test en diminuant la taille !
