### ISSUE TITLE
Erreur sur le chemin relatif

### ISSUE THREAD

**Issue by maurocolognesi** [witsa/synapps#69]
Pas possibile de sortire de cette erreur

![image](https://user-images.githubusercontent.com/35558533/35384451-a0f69b58-01c5-11e8-8fd8-5c131513d689.png)

**Comment by ericvoignier** [comment]
OK, pb rencontrer plusieurs fois mais difficile à reproduire =>  peux tu copier le PCK du projet sur
> \\wit-file\Echange\SynApps\Issues\69\

**Comment by maurocolognesi** [comment]
param 2018_01_25 Centro Scolastico.PK4 disponible ici \\WIT-FILE\Echange\SynApps\Issues\69

**Comment by ericvoignier** [comment]
Pb reproduit lorsque le chemin relatif est lui même relié à la valeur d'une source de donnée ... 
Le chemin relatif peut être défini:
- manuellement ou 
- via l'explorateur un chemin relatif
- voir, très rarement, par liaison interne vers un chemin relatif d'un autre acteur ou vers une librairie.

Mais ce chemin relatif ne viendra jamais d'une source de donnée, trop complexe à mettre en oeuvre et je ne vois pas de cas d'usage.

Le pb rencontré ici est donc lié à cette liaison vers une source de donnée alors qu'a priori tu voulais juste définir un chemin relatif => IHM ambiguë de ce point de vu.

La **liaison** du chemin relatif vers les **sources de donnée** est donc désormais **désactivé**
![image](https://user-images.githubusercontent.com/9974702/35400155-5c61a286-01f6-11e8-96e7-459fd670c7d0.png)

**Comment by ericvoignier** [comment]
En attente déploiement 1.3.3

**Comment by ericvoignier** [comment]
Déployé 1.3.3
