### ISSUE TITLE
Erreur à la publication

### ISSUE THREAD

**Issue by edejean** [witsa/synapps#698]
Bonjour,

Je pensais à un problème d'image, je les ai donc repassée 1 par 1, mais dès que je n'ai plus le message d'erreur liée à l'image manquante, l'erreur suivante apparait...

Error invoking remote method 'studio:call': READ_ERROR: code: 500 name:READ_ERROR origin:[FileIO][readBase64File] G:\Mon Drive\SynappsProjets\Urgo_Longvic\pictures Error: EINVAL: invalid argument, read

![2024-02-27 17_24_47-Synapps Studio-000195](https://github.com/witsa/synapps/assets/105919791/34002c56-d035-4895-9daa-1621b23a3af2)

**Comment by Raphwit** [comment]
Bonjour, assurez vous que le projet n'est pas situé dans un disque réseau, il semble que Synapps ne parvienne pas à lire un des fichier.

**Comment by edejean** [comment]
Effectivement, il était sur un emplacement onedrive mais je l'ai rapatrié en local depuis, et essayer les images une à une dans la mesure où il butte sur le dossier "pictures", mais dès que la dernière image est redéplacer dans le dossier, l'erreur apparait, dès que j'enlève une image, n'importe laquelle, ça passe...

**Comment by manufitoussiwit** [comment]
> Effectivement, il était sur un emplacement onedrive mais je l'ai rapatrié en local depuis, et essayer les images une à une dans la mesure où il butte sur le dossier "pictures", mais dès que la dernière image est redéplacer dans le dossier, l'erreur apparait, dès que j'enlève une image, n'importe laquelle, ça passe...

Bonjour, si c'est un emplacement onedrive alors ce n'est pas un problème de lecteur réseau. 

Pouvez-vous s'il vous plait faire une capture de la liste des images dans le dossier pictures qui ferait apparaitre les noms des fichiers et leur extension?

**Comment by edejean** [comment]
Je pensais à un problème de synchro de fichiers au départ, mais bon j'ai trouvé d'où venait l'erreur, j'avais 2 références d'images qui ne pointaient sur rien dans le config.json : 
  "picture1": "",
  "picture2": "",
On peut clôturer le sujet, merci et bonne soirée !

**Comment by manufitoussiwit** [comment]
Dans la version 1.2.1, l'étape à laquelle la publication s'est arrêtée est inscrite dans le message d'erreur. Cela va faciliter la détection de ce genre de problème en attendant de l'empêcher en amont.
