### ISSUE TITLE
Représentation Booléen Gestion Propriété Spécifique

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#70]
Suite à tes conseils pour les Composites, j'essaie de créer des propriétés de configuration ce qui ouvre effectivement beaucoup de perspectives.
Mon interrogation et demande d’évolution concerne la _propriété spécifique Booléen_.
![image](https://user-images.githubusercontent.com/33632664/35481089-f122ff32-041c-11e8-9dd0-cb3752431e6c.png)

Je souhaite que l'**Utilisateur Configurateur** puisse choisir une option type Oui / Non. Par exemple : Gestion de Porte Oui / Non.
Apparemment avec la propriété Booléen cela fonctionne bien (et tant mieux) mais c'est moins agréable a utiliser ou pas assez explicite à mon sens en comparaison d'une liste déroulante avec les états OUI / NON.

En utilisant la liste déroulante il n'est pas possible de venir piloter un état booléen d'un acteur dans le Composite (en tout cas je n'ai pas trouvé). Dans mon exemple, c'est la _propriété "Visible"_ de l'acteur Bouton que je souhaite ou pas afficher en fonction justement de la sélection faite par **l'Utilisateur Configurateur**.

En fait, à mon sens, il faudrait que la _Propriété Spécifique Booléen_ soit sous une représentation par liste à 2 choix unique équivalent à un True / False avec libellé paramétrable (ouvert / fermé - oui/ non - on/off - etc....
![image](https://user-images.githubusercontent.com/33632664/35481150-40d0e534-041e-11e8-8054-cf42940af566.png)

Tout simplement, une liste est plus "sexy" qu'une case à cocher...
![image](https://user-images.githubusercontent.com/33632664/35481185-fa0e6e54-041e-11e8-91bb-f385efb2ad15.png)

**Comment by ericvoignier** [comment]
OK **le plus simple** est de présenter un booléen. Par exemple: "Gestion Ouverture Porte", 
Mais tu souhaites plutôt proposer une **liste déroulante bi-état** de configuration de ton composite. C'est possible mais cela demande **un usage plus avancé** et il faut mettre un peu les mains dans le javascript.
La problématique est la suivante: les clés des listes déroulantes sont des **chaines de caractères** et ne peuvent donc pas en l'état être liées directement à une propriété **booléen** d'un acteur.
Ex: la propriété _visible_ d'un bouton.

Il est par contre possible de **transformer la valeur liée** simplement:
- se positionner sur la propriété de l'acteur lié à la liste déroulante. Dans notre exemple; visible sur l'acteur bouton
- sélectionner _script de lecture_
![image](https://user-images.githubusercontent.com/9974702/35521530-49a63fc2-051a-11e8-83d5-0d0a46c047fc.png)
- saisir le javascript en remplaçant helloVisible par le label de la liste déroulante
```js
var helloVisible = context.synoStage.get('helloVisible');
return helloVisible==="0";
```

1. _context.synoStage_ permet de récupérer le composite
2. _.get('helloVisible')_ permet de récupérer la valeur de propriété helloVisible du composite
3. La liste _helloVisible_ a deux valeurs chaines _"0"_ et _"1"_ correspondant aux libellés respectifs _"Visible"_ et _"Pas visible"_. La ligne helloVisible==="0" retourne donc _true_ si _helloVisible==="0"_ et _false_ sinon
![image](https://user-images.githubusercontent.com/9974702/35522423-95e20022-051c-11e8-901d-cb82e55e5555.png)
4. La valeur liée retournée est donc désormais bien un booléen

Il s'agit d'un mode de liaison plus avancé qui nécessite de saisir un peu de _javascript_ mais rien de très compliqué.

**Comment by WITNicolas** [comment]
Ok merci pour l'info, ça me permet aussi de comprendre un peu plus le fonctionnement de SYNAPPS a travers le javascript. Désolé d'aller un peu plus vite que la musique :)...

**Comment by ericvoignier** [comment]
Des tutos sur les composites et les événements Synapps s'imposent !
Nous attendons ton retour pour validation solution proposée

**Comment by WITNicolas** [comment]
En fait la scène qui utilise le composite fonctionne très bien mais je ne peux plus éditer le composite pour modification. Je tombe toujours sur le Screen du post précédent.

**Comment by ericvoignier** [comment]
Analyse en cours

**Comment by ericvoignier** [comment]
Déployé 1.3.3

**Comment by ericvoignier** [comment]
En attente confirmation résolution avec 1.3.3

**Comment by WITNicolas** [comment]
OK fonctionne parfaitement.
