### ISSUE TITLE
Valeur d'un additionnel de type booléen en "Undefined" si sa valeur par défaut est à 0

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#700]
Bonjour,

La valeur d'un additionnel de type booléen d'un acteur est détectée comme "Undefined" au lieu de 0 si sa valeur par défaut est à false.

Si quelqu'un rencontre ce problème, il faut mettre un script OnPostInit sur l'acteur pour dire que l'additionnel est à 0 et celui-ci est résolu.

**Comment by Raphwit** [comment]
Bonjour Jeremie,

C'est actuellement valable pour toutes les additionnelles, à partir du moment ou celles-ci sont établies à leur valeur par défaut, c'est assumé et cela pourra évoluer à l'avenir.

Pour fournir une petite explication technique, c'est pour des soucis de performances que les valeurs ne sont pas fournies lorsque l'additionnelle est établie à sa valeur par défaut.

C'est une bonne chose de renseigner l'additionnelle dans le "OnPostInit" si l'on a besoin explicitement d'une valeur.
Dans ton cas, le "undefined" peut être assimilé à un "false" lors de la vérification d'une condition avec un "if" il n'est donc pas forcément nécessaire de changer la valeur dans le PostInit, à voir comment est utilisé l'additionnelle.

**Comment by JeremieDENAEGEL** [comment]
Merci pour ce retour,
Dans mon cas, sans faire le OnPostInit, je devais cliquer 2 fois pour que ma scène avec un clavier virtuel s'affiche ce qui n'est pas pratique en terme d'expérience utilisateur. Mais peut-etre que je peux optimiser le script OnClick.
