### ISSUE TITLE
Charts Répartition

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#71]
Quand on sélectionne le **Charts Répartition** et que l'on veut lier la couleur à une couleur en librairie il y a plantage.
_Manipulation :_ 
![image](https://user-images.githubusercontent.com/33632664/35645903-c60089e2-06cd-11e8-9d54-e4c2c45e5233.png)

_Plantage :_ 
![image](https://user-images.githubusercontent.com/33632664/35645919-d262a512-06cd-11e8-8d3c-9db070f07dd4.png)

**Comment by ericvoignier** [comment]
Correction + modification du formulaire de configuration de la répartition avec la possibilité de **définir** et **appliquer** des **palettes de couleurs** aux secteurs  
![image](https://user-images.githubusercontent.com/9974702/36999867-c93b3266-20c1-11e8-9803-46090e31b59d.png)
