### ISSUE TITLE
Message d'erreur fournisseurs de données

### ISSUE THREAD

**Issue by Mathis554** [witsa/synapps#747]
Bonjours
Je n'es plus accès a mon fournisseurs de données
![image](https://github.com/witsa/synapps/assets/174346872/93485580-41b6-430c-a6c4-1e4cd6894d98)
![image](https://github.com/witsa/synapps/assets/174346872/f884a03c-9e3c-4cae-b5c6-b54c0ebd803b)
Version de Synapps studio 1.3.0

**Comment by Raphwit** [comment]
Bonjour, en effet, nous avons réglé ce bug et publions un correctif dans l'heure !

**Comment by Mathis554** [comment]
Oh bas merci beaucoup

**Comment by manufitoussiwit** [comment]
Salut, la révision est en ligne

**Comment by Mathis554** [comment]
Merci bien 😊
Après installation de la nouvelle version
![image](https://github.com/witsa/synapps/assets/174346872/08f3af87-8557-4d28-b317-7ca28f1a582a)
Cella refonctionne.
