### ISSUE TITLE
Redimensionnement Composite

### ISSUE THREAD

**Issue by KenneyClement** [witsa/synapps#749]
lorsqu'on modifie la taille du composite (en 1920 1080 px par ex) et quand je modifie un script et l'enregistre le composite ce redimensionne sur l'ancien format (les paramètres n'ont pas était modifié).

1-  
![image](https://github.com/witsa/synapps/assets/148433313/85d8888b-ad34-4605-8dc8-1041831e15a0)
2-
![image](https://github.com/witsa/synapps/assets/148433313/62ec3ca3-f04f-42db-9f1b-3cffafeb14d1)

**Comment by manufitoussiwit** [comment]
Bien vu! C'est corrigé dans la dernière révision `2024-07-12T11:00:00`
