### ISSUE TITLE
Page web SWEGON dans synapps

### ISSUE THREAD

**Issue by AmelieChaussonTEC** [witsa/synapps#781]
Bonjour, 
Je voudrais intégrer la page web d'un CTA Swegon dans mon synapps, mais je n'ai qu'un bandeau qui s'affiche. où est-ce que je pourrais remettre a l'échelle correctement ? 
![synapps_param](https://github.com/user-attachments/assets/18cf10c3-ddeb-4f00-bcc7-fe74edc69fad)
![synapps_vue cta](https://github.com/user-attachments/assets/558e7b5f-689e-442b-adb6-8debbbbfcfd8)
![vue cta a afficher](https://github.com/user-attachments/assets/925bf140-0a84-4e11-a4e8-ec1e2415de6d)

**Comment by WITNicolas** [comment]
Bonjour
Je pense que le  problème se situe au niveau de la boite à vue. La page en provenance de la CTA est déjà probablement en reponsive design. 
Du coup je ferais déjà un test simple : mettre directement StackAutorisation directement à la racine de la scene, sans passer par la viewbox, pour voir comment cela réagit.

**Comment by AmelieChaussonTEC** [comment]
Tu as raison, ca fonctionne comme ca. Merci beaucoup 
![synapps_vue_ok](https://github.com/user-attachments/assets/c9ee85dd-ece8-4547-9f61-d438f8bd2ab5)
