### ISSUE TITLE
Pertes de configurations de ressources et scènes.

### ISSUE THREAD

**Issue by AmauryPit1** [witsa/synapps#786]
Bonjour, lorsque je fais mon programme Synapps, il m'est arrivé plusieurs fois que lorsque je change de fenêtre de ressources ou de scène, un black screen se produit et je ne peux rien faire que de relancer Synapps. Quand ça arrive, je perds les ressources que j'ai configurées avec aucun moyen de les récupérer. Les ressources n'ont pas le même nom, car je sais que quand l'on importe des ressources venant d'autre fichier cela peut causer un problème, mais là ce n'est pas le cas. Le REDY PC est à jour (14.5.2) et Synapps aussi. Ci-joint le programme corrompu pour voir s'il n'y a pas un paramètre interne au programme.
[chaufferie boucherie.zip](https://github.com/user-attachments/files/17256037/chaufferie.boucherie.zip)

**Comment by manufitoussiwit** [comment]
Bonjour, 
Il semble que le composite Vanne left contient une instance de lui-même ce qui produit une boucle.

**Comment by manufitoussiwit** [comment]
Si c'était bien le seul pb, je clôture l'issue 😉. 
En attendant, il faudrait qu'on trouve un moyen pour que Studio soit moins sensible à ce genre de boucle.
