### ISSUE TITLE
Action d'un bouton non fonctionnelle dans une synapps ouverte à l'intérieure d'une autre synapps 

### ISSUE THREAD

**Issue by JeremieDENAEGEL** [witsa/synapps#792]
Bonjour,

Nous avons dans un synapps "esclave", affiché dans un acteur iframe d'un synapps "maitre", des boutons permettant l'ouverture ou la fermeture des portes.

L'action des boutons depuis le synapps "maitre" ne fonctionne pas. Par contre quand on est directement dans le synapps "esclave", les boutons fonctionnent parfaitement.

Toutes les actions sont autorisées dans l'acteur iframe, est-ce-que cela peut venir des nouvelles mesures de sécurité des navigateur ? (le problème se présente sur Chrome et Firefox)

A noter que le synapps "esclave" est déployé dans le même redy que le synapps "maitre".

**Comment by manufitoussiwit** [comment]
Salut! 
je pencherai plus pour une différence de droit entre l'utilisateur utilisé depuis la synapp maitresse et celui en accès direct.

**Comment by JeremieDENAEGEL** [comment]
Bien vu
Le client final a changé le niveau d'accès du compte utilisé pour l'ouverture de session dans les iframe sur certains des automates de la flotte en "invité"
Je vais voir avec lui pour ne plus toucher à ce compte là pour éviter que cela se reproduise.

**Comment by JeremieDENAEGEL** [comment]
Bien vu
Le client final a changé le niveau d'accès du compte utilisé pour l'ouverture de session dans les iframe sur certains des automates de la flotte en "invité"
Je vais voir avec lui pour ne plus toucher à ce compte là pour éviter que cela se reproduise.
