### ISSUE TITLE
Revoir ergonomie de gestion des palettes de couleur

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#88]
Il serait judicieux de ne pas rendre éditable les palettes de couleurs proposées par défauts. Forcement en bidouillant et testant j'ai supprimé les couleurs ou bien j'ai renommé la palette... et impossible de revenir en arrière.

Ce que vous proposez de base est parfait, que ce soit en terme de palette (qui respecte la roue chromatique) ou bien les noms choisis, juste pas modifiable je pense.

Ce qui n’empêche pas, bien sur, de laisser la possibilité de rajouter ses propres palettes pour la personnalisation comme vous l'avez fait.

Evidemment il ne s'agit que d'un ressenti de ma part.

**Comment by ericvoignier** [comment]
Il est possible de reprendre à tout moment une palette de référence pour l'ajouter dans la liste des palettes de la SynApp:
1.
![image](https://user-images.githubusercontent.com/9974702/37136767-4602d56e-22a3-11e8-8353-345f0b7fe42c.png)
2.
![image](https://user-images.githubusercontent.com/9974702/37136856-a4e4784e-22a3-11e8-9f5a-1db3cb50ab0f.png)
3.
![image](https://user-images.githubusercontent.com/9974702/37136896-c9651840-22a3-11e8-99fd-ef9663145a32.png)
4.
![image](https://user-images.githubusercontent.com/9974702/37137028-52a255e6-22a4-11e8-8799-ba93ba2a4822.png)

Est ce que cela répond au besoin ?

**Comment by WITNicolas** [comment]
J'ai du m'embrouiller entre les palettes de références et celles que tu rajoutes dans la liste personnalisée et l'édition.
Finalement c'est peut être ma compréhension qui n’était pas trop claire entre les différents boutons "ajouter", je ne savais pas trop me situer.

En fait il y a 3 modales qui sont imbriquées les unes sur les autres.
1.Explorateur de palette
2.Éditeur de palette
3.Recherche de palette

Le bouton FERMER, ferme la modale affichée mais pas les autres, ce que à quoi je m'attendais en fait.
Maintenant que je sais tout ça il n'y a plus de soucis (désolé)
Je suis parti du principe que sans documentation tout doit être limpide, ce que la majeure partie des utilisateurs auront comme première réaction. Mais avec une documentation en support ça passera.

Peut être dans le bouton mettre "Ajouter la palette" comme on a "Ajouter une couleur"
![image](https://user-images.githubusercontent.com/33632664/37142991-08163694-22ba-11e8-8f27-96a880df9684.png)

**Comment by ericvoignier** [comment]
👍 oui je comprends l'ambiguité, prévoir une revue ergo
