### ISSUE TITLE
Affichage des infos dans les secteur de l'acteur répartition

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#89]
Pouvoir afficher la valeur directement dans le secteur affiché.
Je pense à des affichages de type sensibilisation, les utilisateurs n'ont pas de souris pour survoler les zones.
Un affichage permanent serait un plus.

![image](https://user-images.githubusercontent.com/33632664/37121113-83541e74-225c-11e8-9919-69e58c491c1c.png)

**Comment by ericvoignier** [comment]
En effet, cela nécessite de faire évoluer le **WChart** [https://github.com/witsa/wchart/issues/1]()
