### ISSUE TITLE
Acteur Courbe de Chauffe

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#91]
Prévoir l'acteur métier Courbe de Chauffe (avec les déclinaisons, Courbe de chauffe avec influence d'ambiance).
On peut effectivement mettre des cases de saisies pour venir modifier les propriétés SP_M30 / SP_M25 etc..etc..
Seulement il n'y aurait pas le rendu graphique de la courbe qui donne une visibilité graphique plus agréable et compréhensible comme sur le REDY.
Le mieux serait donc d'avoir la courbe de chauffe à la "sauce" HTML5 avec le principe de faire glisser les points de courbe en pensant à la possibilité de faire cela sur du tactile.

**Comment by ericvoignier** [comment]
Effectivement, il faudrait prévoir une **modernisation de la "courbe de chauffe"** en mode RIA qui pourrait être intégrée dans SynApps de la même façon que le grapheur.
Cela dépasse le périmètre de SynApps, je maintiens l'issue ouverte pour suivi et adresse le besoin au sein de l'équipe création.
_Remarque:_ en attendant, il est possible d'intégrer la courbe de chauffe actuelle via un SynAptique dans SynApps ...

**Comment by WITNicolas** [comment]
Oui pour suivi et cela fait effectivement parti d'une demande d'évolution sur GLADYS.
Pour ta remarque, oui et ça fonctionne très bien pour une solution alternative.

**Comment by ericvoignier** [comment]
[Evolution courbe de chauffe sur Gladys](https://gladys.com/info/0155c0aabaa1b02ee18644637a032098)

**Comment by manufitoussiwit** [comment]
Le reflet Courbe de chauffe permettra tout ça
