### ISSUE TITLE
Bouton de Navigation

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#93]
Pour réaliser les synoptiques, on utilise souvent des icônes pour la navigation et l'aspect visuel. Dans l' acteur de navigation actuel il n'est pas possible d'associer une image.
J'ai essayé de mettre une image dans le contenu mais l'image n'est pas interprétée.

![image](https://user-images.githubusercontent.com/33632664/37490795-05341d3c-289c-11e8-8649-ea3170b4cb38.png)

**Comment by ericvoignier** [comment]
En effet, nous avons bien un acteur commutateur bouton prenant 2 images pour du bi-états ON/OFF mais pas sur le type bouton poussoir.
Nous pourrions proposer un acteur simple bouton image mais que nous devrions décliner sur les 2 acteurs _bouton poussoir_ et _navigation_ à évaluer sachant qu'il existe un moyen simple de réaliser ce que tu souhaites:
Il faut savoir que le contenu attendu du bouton est du HTML, il suffit donc de:
1. **Définir ce contenu** avec une balise HTML simple image: `<img src="{{monImage}}">`
![image](https://user-images.githubusercontent.com/9974702/37511142-061c46b8-28fe-11e8-9cfb-b019484ef87c.png)
2. Ajouter la **propriété additionnelle** de type _image_
![image](https://user-images.githubusercontent.com/9974702/37511233-5d63e1a6-28fe-11e8-973f-8a2eac6dfa0d.png)
3. **Glisser une image** dans _monImage_
![image](https://user-images.githubusercontent.com/9974702/37511372-d90ae4b2-28fe-11e8-9c6a-f81750f29ab8.png)

__Remarques:__ 

- Pour automatiser cela, il est possible de réaliser un **composite** avec en propriété publique l'image, c'est d'ailleurs pour cette raison qu'il ne me semble pas pertinent d'ajouter les 2 acteurs natifs mentionnés ci-dessus.
- De la même façon tu peux ajouter des [glyphicons bootstraps](https://getbootstrap.com/docs/3.3/components/) en définissant dans la propriété contenu
`<span class="glyphicon {{monGlyphicon}}" aria-hidden="true"></span>`. _monGlyphicon_ est alors une propriété additionnelle de type _text_ avec pour valeur le nom du glyphicon, 
Par exempe: `glyphicon-search`

**Comment by WITNicolas** [comment]
Okaaay ! 
Bon il va falloir que je me fasse vraiment à la mécanique via l'HTML et la personnalisation. ça va rentrer.
La documentation va être hyper importante.

Effectivement aucun intérêt de rajouter 2 nouveaux acteurs, un composite fera très bien l'affaire. 
L'issue peut être clôturée [sans intérêt].

**Comment by ericvoignier** [comment]
OK j'ajouterais que lorsqu'un mécanisme de partage simples des composites sera possible, il sera quasi transparent pour l'utilisateur qui réalise une SyApps d'ajouter un acteur qu'il soit composite ou natif.
On peut donc considérer ici qu'il s'agit d'un usage avancé pour un "power user" pour créer un composite nécessitant quelques connaissances en HTML !

**Comment by WITNicolas** [comment]
Je suis tout a fais d'accord, il faut que je me mette en tête que SYNAPPS est un outil de création/développement et non pas un "simple"outil figé comme peut l'être les Synoptiques actuels.
