### ISSUE TITLE
Bouton de choix maintenu enfoncé

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#94]
Dans le cas de bouton de sélection et/ou de navigation.
L'appui sur un bouton maintien le-dit bouton en position enfoncé et relâche automatiquement les autres boutons d'un même groupe.

Exemple : Groupe 1
Appui sur A
Bouton A enfoncé, Bouton B relâché, Bouton C relâché
![image](https://user-images.githubusercontent.com/33632664/37491383-f1f5f1da-289d-11e8-89ea-928dce289b18.png)

Appui sur B
Bouton A relâché, Bouton B enfoncé, Bouton C relâché
![image](https://user-images.githubusercontent.com/33632664/37491387-f7efa072-289d-11e8-8f31-a9a559941b65.png)

Cela permet de créer des menus avec visualisation du bouton enfoncé et mettre éventuellement un aspect différent entre Bouton Enfoncé ou Relâché.

**Comment by ericvoignier** [comment]
Oui nous proposerons un acteur menu avec ce comportement. En attendant, nous avons réalisé un acteur composite qui réalise cela.

**Comment by manufitoussiwit** [comment]
L'acteur liste de bouton répond à cette problématique
