### ISSUE TITLE
Valeur retour état du bouton poussoir pas systématiquement envoyée

### ISSUE THREAD

**Issue by ericvoignier** [witsa/synapps#95]
Lorsque clique trop rapide ...

**Comment by WITNicolas** [comment]
Oui constaté, j'ai oublié de le notifier.
Quand on fait un clic classique (quelques millisecondes), l'info n'est pas transmise à la Source.
Par contre si on maintient le clic 1 à 2 sec, la commande se fait bien sur le REDY.

**Comment by WITNicolas** [comment]
Je suis sur REDY K7 en version 9.50 beta
Différence de fonctionnement entre Chrome et Safari iPhone

Mon application : Gestion Ouverture / Fermeture des Volets Roulants.
Dans le cas de Chrome le bouton est fonctionnel, il est lié à une ressource de type Consigne Logique. (il faut le maintenir 1 sec pour que cela fonctionne comme dit précédemment)

Dans le cas de Safari sur iPhone, l'action ne part jamais, même en restant appuyer sur le bouton d'action.

**Comment by ericvoignier** [comment]
Le problème a été identifié et une **correction est en cours** qui ne sera **plus sensible à la durée du clique**.
Concernant _safari_,il est probable 'il s'agit d'un mode de fonctionnement par défaut proposant la sauvegarde de l'image lorsque le bouton est laissé en position appuyé, donc difficile à contourner. Dans ce cas, le fix du problème initial élimine cet effet.

**Comment by ericvoignier** [comment]
Pour mémo, utiliser les événements _touchstart_ et _touchend_ pour les devices de type smartphone.
[](https://developer.mozilla.org/fr/docs/Web/Guide/DOM/Events/Touch_events)
