### ISSUE TITLE
Gestion de la librairie d'image

### ISSUE THREAD

**Issue by WITNicolas** [witsa/synapps#96]
Permettre un drag n drop des images directement dans l'interface librairie par paquet entier.
Cela permettrait de remplir la librairie à la volée (modifiable par la suite), avec comme label le nom du fichier.
Si les images sont labellisées comme vous l'attendez (longueur, espace, accent, etc..) l'objet se crée en librairie, sinon label automatique.

ça évite de faire (par image !): 
Creation
Labellisation
DragNDrop de l'image

**Comment by ericvoignier** [comment]
_SynApps Maker_ va évoluer en mode desktop (<>Web) ou chaque ressource de la SynApp: _scene_, _librairie_, etc sera un f**ichier physique dans un dossier**. Avec ce mécanisme, il suffira de copier directement ces fichiers dans le dossier _librairie/image_..
Nous permettrons également un import/export de ces mêmes ressources afin de permettre l'échange entre utilisateurs.
Issue conservée ouverte pour suivi...

**Comment by manufitoussiwit** [comment]
On va en tenir compte pour l'implémenter dans Studio
